  - nombre: "Logitech G502 HERO"
    imagen: "images/raton-gaming-Logitech-G502-HERO.webp"
    lo_mejor: "🎯 Sensor HERO 25K con peso ajustable y 11 botones"
    a_tener_en_cuenta: "🔊 Algo ruidoso si no te gusta la rueda con clics"
    enlace: "https://amzn.to/4jUd5r2"

  - nombre: "Razer Basilisk V3 X HyperSpeed"
    imagen: "images/raton-gaming-Razer-Basilisk-V3-X-HyperSpeed.webp"
    lo_mejor: "🔋 Hasta 285h de batería, dual wireless"
    a_tener_en_cuenta: "🖱 Sin RGB ni sensor de gama alta"
    enlace: "https://amzn.to/4cRYLNz"

  - nombre: "Razer Basilisk V3"
    imagen: "images/raton-gaming-Razer-Basilisk-V3.webp"
    lo_mejor: "💡 Rueda inteligente, RGB y sensor Focus+"
    a_tener_en_cuenta: "📦 Algo pesado para quienes buscan ligereza"
    enlace: "https://amzn.to/4cY6WrA"

  - nombre: "Logitech G403 HERO"
    imagen: "images/raton-gaming-Logitech-G403-HERO.webp"
    lo_mejor: "⚖️ Ligero, ergonómico y preciso"
    a_tener_en_cuenta: "🎮 Sólo 6 botones programables"
    enlace: "https://amzn.to/3EDfyar"

  - nombre: "ASUS ROG SPATHA X"
    imagen: "images/raton-gaming-ASUS-ROG-SPATHA-X.webp"
    lo_mejor: "🔧 12 botones, base carga y diseño robusto"
    a_tener_en_cuenta: "📐 Muy grande, sólo apto para manos grandes"
    enlace: "https://amzn.to/3ETZfWC"

  - nombre: "Logitech G402 Hyperion Fury"
    imagen: "images/raton-gaming-Logitech-G402-Hyperion-Fury.webp"
    lo_mejor: "🚀 Sensor Fusion Engine y tasa 1000Hz"
    a_tener_en_cuenta: "❌ Sin RGB, diseño algo anticuado"
    enlace: "https://amzn.to/3SaQwme"

  - nombre: "SteelSeries Aerox 5 Wireless"
    imagen: "images/raton-gaming-SteelSeries-Aerox-5-Wireless.webp"
    lo_mejor: "🪶 Ultraligero y perforado, IP54"
    a_tener_en_cuenta: "⛽ Autonomía menor que otros (180h)"
    enlace: "https://amzn.to/4dvGiqo"

  - nombre: "Razer Viper V3 HyperSpeed"
    imagen: "images/raton-gaming-Razer-Viper-V3-HyperSpeed.webp"
    lo_mejor: "🎮 Sensor 30K DPI y diseño ambidiestro"
    a_tener_en_cuenta: "🔋 Usa una pila AA, no batería recargable"
    enlace: "https://amzn.to/43fJXDN"

  - nombre: "Corsair NIGHTSWORD"
    imagen: "images/raton-gaming-Corsair-NIGHTSWORD.webp"
    lo_mejor: "⚖️ Pesos ajustables y 10 botones"
    a_tener_en_cuenta: "📏 Muy orientado a manos grandes"
    enlace: "https://amzn.to/4kijY6h"

  - nombre: "Razer DeathAdder V3"
    imagen: "images/raton-gaming-Razer-DeathAdder-V3.webp"
    lo_mejor: "🧠 Precisión quirúrgica y peso ultraligero"
    a_tener_en_cuenta: "🕹️ No apto para zurdos"
    enlace: "https://amzn.to/4jZTlTt"
