productos:
- nombre: Logitech G502 HERO
  brand: Logitech
  imagen: images/raton-gaming-Logitech-G502-HERO.webp
  valoracion: 5
  descripcion: He usado el Logitech G502 HERO durante varias sesiones intensas y destaca
    por su precisión extrema y ergonomía perfecta para manos grandes. Su peso ajustable
    y botones configurables lo hacen ideal para shooters. Algo que me encantó es la
    respuesta táctil de los clics, muy definidos y con una sensación mecánica muy
    satisfactoria. Además, su rueda con dos modos (libre o por pasos) es muy útil
    tanto para jugar como para tareas de oficina. Un ratón muy completo que se adapta
    a cualquier situación.
  caracteristicas:
  - Sensor HERO 25K con seguimiento 1:1
  - 11 botones programables y personalizables
  - Pesos ajustables para un balance a medida
  - 'Rueda con dos modos: libre y por pasos'
  - Diseño ergonómico, ideal para manos grandes
  enlace: https://amzn.to/4jUd5r2
  lo_mejor: 🎯 Sensor HERO 25K con peso ajustable y 11 botones
  a_tener_en_cuenta: 🔊 Algo ruidoso si no te gusta la rueda con clics
- nombre: Razer Basilisk V3 X HyperSpeed
  brand: Razer
  imagen: images/raton-gaming-Razer-Basilisk-V3-X-HyperSpeed.webp
  valoracion: 4.5
  descripcion: 'Probé este ratón inalámbrico y me sorprendió su rendimiento: sin lags
    perceptibles y una batería de larga duración. La comodidad y los botones laterales
    lo convierten en mi favorito para juegos tipo MOBA y RPG. Lo mejor es que puedes
    cambiar entre Bluetooth e HyperSpeed según el dispositivo o necesidad, lo que
    te da una gran versatilidad. Su forma se adapta bien a diferentes tamaños de mano
    y los clics tienen buena respuesta. Ideal si buscas movilidad sin perder rendimiento.'
  caracteristicas:
  - 'Conectividad dual: HyperSpeed y Bluetooth'
  - Autonomía de hasta 285 horas
  - Diseño ergonómico adaptable a varias manos
  - Buena respuesta de los clics y botones laterales
  - Ideal para juegos tipo MOBA y RPG
  enlace: https://amzn.to/4cRYLNz
  lo_mejor: 🔋 Hasta 285h de batería, dual wireless
  a_tener_en_cuenta: 🖱 Sin RGB ni sensor de gama alta
- nombre: Razer Basilisk V3
  brand: Razer
  imagen: images/raton-gaming-Razer-Basilisk-V3.webp
  valoracion: 4
  descripcion: En mis pruebas con el Basilisk V3, noté una gran mejora en velocidad
    de respuesta y personalización. Su rueda inteligente y efectos RGB avanzados son
    un plus tanto para estética como funcionalidad. Es especialmente útil para juegos
    donde alternas entre tareas de precisión y desplazamientos rápidos. El software
    Synapse permite configurar perfiles, macros y ajustar cada aspecto del ratón al
    detalle. Muy recomendable para jugadores que disfrutan afinando su setup al máximo.
  caracteristicas:
  - Rueda inteligente con desplazamiento adaptativo
  - Sensor Focus+ con hasta 26.000 DPI
  - RGB Chroma personalizable por zonas
  - Compatible con Synapse para macros y perfiles
  - Alta velocidad de respuesta en juegos competitivos
  enlace: https://amzn.to/4cY6WrA
  lo_mejor: 💡 Rueda inteligente, RGB y sensor Focus+
  a_tener_en_cuenta: 📦 Algo pesado para quienes buscan ligereza
- nombre: Logitech G403 HERO
  brand: Logitech
  imagen: images/raton-gaming-Logitech-G403-HERO.webp
  valoracion: 4
  descripcion: Este ratón me pareció ideal para quienes buscan un diseño simple pero
    con grandes prestaciones. Su sensor es extremadamente preciso, y su comodidad
    me permitió jugar horas sin molestias. Es más ligero que otros modelos, lo que
    lo hace muy adecuado para quienes prefieren movimientos rápidos. A nivel estético
    es más sobrio, pero su rendimiento no decepciona. Una opción sólida para quien
    busca calidad sin artificios.
  caracteristicas:
  - Sensor HERO de alta precisión
  - Diseño ergonómico y ligero
  - 6 botones programables
  - Ideal para largas sesiones de juego
  - Buena opción calidad-precio sin estética llamativa
  enlace: https://amzn.to/3EDfyar
  lo_mejor: ⚖️ Ligero, ergonómico y preciso
  a_tener_en_cuenta: 🎮 Sólo 6 botones programables
- nombre: ASUS ROG SPATHA X
  brand: Asus
  imagen: images/raton-gaming-ASUS-ROG-SPATHA-X.webp
  valoracion: 4
  descripcion: Tras probarlo, el SPATHA X me impresionó por su robustez, conectividad
    dual y sus 12 botones programables. Es un ratón premium ideal para juegos MMO
    o cualquier configuración avanzada. Lo utilicé en títulos como Final Fantasy XIV
    y World of Warcraft, donde tener accesos rápidos es crucial. Su base de carga
    magnética es cómoda y elegante, y el diseño, aunque grande, se siente sólido y
    cómodo. Si necesitas funcionalidad máxima, este es de los más completos.
  caracteristicas:
  - 12 botones programables, ideal para MMOs
  - Conectividad por cable e inalámbrica
  - Base de carga magnética incluida
  - Diseño robusto y de gran tamaño
  - Perfecto para jugadores con manos grandes
  enlace: https://amzn.to/3ETZfWC
  lo_mejor: 🔧 12 botones, base carga y diseño robusto
  a_tener_en_cuenta: 📐 Muy grande, sólo apto para manos grandes
- nombre: Logitech G402 Hyperion Fury
  brand: Logitech
  imagen: images/raton-gaming-Logitech-G402-Hyperion-Fury.webp
  valoracion: 4
  descripcion: Este ratón me ha sorprendido por su increíble velocidad de respuesta,
    ideal para shooters como CS2. Su sensor Fusion Engine es muy preciso incluso con
    movimientos rápidos, y se nota especialmente en partidas intensas. Su diseño ergonómico
    es cómodo para largas sesiones y sus botones están bien ubicados para accesos
    rápidos. Aunque no tiene RGB llamativo, su rendimiento compensa. Lo recomiendo
    para quien busca rendimiento puro sin lujos.
  caracteristicas:
  - Sensor Fusion Engine con seguimiento ultra rápido
  - Diseño ergonómico para agarre tipo palma
  - 8 botones programables
  - Tasa de sondeo de 1000 Hz
  - Ideal para shooters como CS2 o Apex Legends
  enlace: https://amzn.to/3SaQwme
  lo_mejor: 🚀 Sensor Fusion Engine y tasa 1000Hz
  a_tener_en_cuenta: ❌ Sin RGB, diseño algo anticuado
- nombre: SteelSeries Aerox 5 Wireless
  brand: SteelSeries
  imagen: images/raton-gaming-SteelSeries-Aerox-5-Wireless.webp
  valoracion: 4.5
  descripcion: 'Al probar el Aerox 5 Wireless, lo que más me impresionó fue su ligereza:
    apenas notas que lo tienes en la mano. Está diseñado para ofrecer velocidad y
    precisión en juegos rápidos. Su sensor es de alta gama y no tiene lag apreciable
    gracias a su conexión inalámbrica fiable. Me ha resultado muy cómodo y su diseño
    perforado ayuda a mantener la mano fresca durante sesiones intensas. Ideal para
    jugadores competitivos que valoran agilidad y ergonomía.'
  caracteristicas:
  - Diseño ultraligero de solo 74g con carcasa perforada
  - Sensor óptico TrueMove Air para precisión milimétrica
  - Conectividad 2.4 GHz y Bluetooth
  - Hasta 180 horas de batería
  - Resistencia al agua y al polvo (IP54)
  enlace: https://amzn.to/4dvGiqo
  lo_mejor: 🪶 Ultraligero y perforado, IP54
  a_tener_en_cuenta: ⛽ Autonomía menor que otros (180h)
- nombre: Razer Viper V3 HyperSpeed
  brand: Razer
  imagen: images/raton-gaming-Razer-Viper-V3-HyperSpeed.webp
  valoracion: 4.5
  descripcion: El Viper V3 HyperSpeed me ha encantado por su ligereza y precisión
    extrema. Su sensor de 30.000 DPI se nota especialmente en juegos donde cada movimiento
    cuenta, como Valorant o Apex. Me impresionó la rapidez con la que responde y la
    comodidad del diseño ambidiestro. Además, la batería dura muchísimo y puedes olvidarte
    del cable durante días. Un ratón perfecto si buscas velocidad y portabilidad sin
    comprometer el rendimiento.
  caracteristicas:
  - Sensor óptico de hasta 30.000 DPI
  - Conectividad inalámbrica HyperSpeed de baja latencia
  - Hasta 280 horas de autonomía
  - Diseño ambidiestro y ligero (82g)
  - Compatible con Razer Synapse para personalización
  enlace: https://amzn.to/43fJXDN
  lo_mejor: 🎮 Sensor 30K DPI y diseño ambidiestro
  a_tener_en_cuenta: 🔋 Usa una pila AA, no batería recargable
- nombre: Corsair NIGHTSWORD
  brand: Corsair
  imagen: images/raton-gaming-Corsair-NIGHTSWORD.webp
  valoracion: 4
  descripcion: El Corsair NIGHTSWORD es una bestia pensada para quienes quieren ajustar
    su experiencia al milímetro. Su sistema de pesas permite modificar el centro de
    gravedad y el peso total según tu estilo. Lo probé tanto en shooters como en MOBAs,
    y se adaptó perfectamente. Además, su sensor es ultra preciso y el diseño ergonómico
    ayuda en sesiones largas. Un ratón robusto, con muchas opciones y muy orientado
    al rendimiento.
  caracteristicas:
  - Sensor óptico PixArt PMW3391 de 18.000 DPI
  - Sistema avanzado de pesos ajustables
  - Diseño ergonómico para diestros
  - 10 botones totalmente programables
  - Iluminación RGB dinámica
  enlace: https://amzn.to/4kijY6h
  lo_mejor: ⚖️ Pesos ajustables y 10 botones
  a_tener_en_cuenta: 📏 Muy orientado a manos grandes
- nombre: Razer DeathAdder V3
  brand: Razer
  imagen: images/raton-gaming-Razer-DeathAdder-V3.webp
  valoracion: 5
  descripcion: El DeathAdder V3 me ha parecido una auténtica joya para shooters. Es
    tan ligero que parece flotar sobre la alfombrilla, y el sensor Focus Pro 30K responde
    con una precisión quirúrgica. Además, los clics son rapidísimos gracias a los
    switches ópticos de tercera generación. Lo he probado en Valorant y Apex, y la
    diferencia se nota en cada flick y cada movimiento rápido. Es sin duda uno de
    los mejores ratones competitivos del momento.
  caracteristicas:
  - Sensor óptico Focus Pro 30K de altísima precisión
  - 'Peso ultraligero: solo 63g'
  - Diseño ergonómico optimizado para diestros
  - Switches ópticos Razer de 3.ª generación
  - Conectividad inalámbrica Razer HyperSpeed
  enlace: https://amzn.to/4jZTlTt
  lo_mejor: 🧠 Precisión quirúrgica y peso ultraligero
  a_tener_en_cuenta: 🕹️ No apto para zurdos
