productos:
  - ASIN: B0953X73TP
    a_tener_en_cuenta: ⏱ Sin métricas avanzadas 🧭 No incluye altímetro barométrico
    brand: Garmin
    caracteristicas:
      - GPS rápido y fiable incluso en ciudad
      - Autonomía de hasta 20 días en modo reloj
      - Sugerencias de entrenamiento diario según tu estado
      - Pantalla legible incluso con sol directo
      - Diseño ligero, apenas lo notas en carrera
    descripcion: >-
      El Garmin Forerunner 55 es el reloj ideal para quienes se inician en el running y buscan fiabilidad sin
      complicaciones. Durante mis entrenamientos urbanos y alguna tirada larga, me convenció por su rapidez de conexión
      al GPS y su comodidad. No tiene métricas avanzadas, pero cumple con nota en lo esencial. Su interfaz es clara, y
      la batería aguanta perfectamente varias sesiones por semana. Un modelo perfecto para empezar sin renunciar a
      calidad.
    enlace: https://amzn.to/44hrBDc
    imagen: https://m.media-amazon.com/images/I/41JLtkUPhCL._SL500_.jpg
    lo_mejor: ✅ Fácil de usar 📡 GPS rápido 🪶 Ligero 🏃 Ideal para principiantes
    nombre: Garmin Forerunner 55
    valoracion: 4
    precio: "159,20\_€"
    precioOriginal: "199,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41MkKHvISEL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41EAK82P8LL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/4143ePjT2yL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51q+966COYL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41zmVxs3y1L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0B553HT2B
    a_tener_en_cuenta: 💰 Precio más alto 📱 Requiere cierta curva de aprendizaje
    brand: Garmin
    caracteristicas:
      - GPS multibanda de alta precisión
      - Hasta 30 h de autonomía con GPS
      - 'Mediciones avanzadas: HRV, VO2Max, carga aguda'
      - Muy cómodo para llevar todo el día
      - Compatible con planes de entrenamiento y Strava
    descripcion: >-
      Probé el Forerunner 255 mientras preparaba una media maratón y fue como tener un entrenador en la muñeca. El GPS
      multibanda clava los recorridos, incluso en zonas difíciles, y las métricas de recuperación y carga de
      entrenamiento me ayudaron a ajustar las sesiones. La autonomía es sobresaliente y la experiencia general, redonda.
      Un modelo versátil y potente para corredores comprometidos.
    enlace: https://amzn.to/3HQ4EiU
    imagen: https://m.media-amazon.com/images/I/419Jvlp-MrL._SL500_.jpg
    lo_mejor: 📊 Métricas completas 🔋 Gran autonomía 📡 GPS multibanda 🏃 Para corredores serios
    nombre: Garmin Forerunner 255
    valoracion: 5
    precio: "203,99\_€"
    precioOriginal: "349,99\_€"
    disponibilidad: Disponible para envío en 1 o 2 días
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51d7SESG-VL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51FOtcZg97L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/512q+5ObgsL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51jdzEpTLfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Wh2nmoUKL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51+a4VgEx+L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0CWB662HK
    a_tener_en_cuenta: 🔋 Autonomía algo menor que otros Garmin ⚙️ Menos funciones avanzadas
    brand: Garmin
    caracteristicas:
      - Pantalla AMOLED nítida y brillante
      - GPS fiable con buen rendimiento en exteriores
      - Seguimiento de salud y recuperación
      - Compatible con entrenamientos por zonas de pulso
      - Interfaz táctil intuitiva
    descripcion: >-
      Este reloj destaca por su pantalla AMOLED, que se ve increíble tanto en interior como a pleno sol. Lo estuve
      usando en sesiones mixtas de ciudad y montaña, y el GPS se mantuvo estable. Tiene lo justo y necesario para
      corredores que quieren algo más que lo básico pero sin irse a modelos premium. La navegación por menús es muy
      fluida gracias a la pantalla táctil.
    enlace: https://amzn.to/40ex9Nf
    imagen: https://m.media-amazon.com/images/I/31lO0J0XTaL._SL500_.jpg
    lo_mejor: 🖥 Pantalla espectacular 📈 Buenas métricas 🎯 Equilibrado y fácil de usar
    nombre: Garmin Forerunner 165
    valoracion: 4
    precio: "299,00\_€"
    precioOriginal: "329,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41rrE4czoiL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41c1A5XG5GL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51CT7kIAmAL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41r+Tllzb6L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41foABJnOTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41RfNwy+vRL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0CC2MK4LV
    a_tener_en_cuenta: 📱 App menos intuitiva que Garmin 💡 Pantalla no AMOLED
    brand: Suunto
    caracteristicas:
      - GPS preciso con buena cobertura en montaña
      - Hasta 40 h de batería con GPS activo
      - Altímetro barométrico y métricas avanzadas
      - Diseño robusto, ideal para exteriores
      - Compatible con rutas y navegación giro a giro
    descripcion: >-
      El SUUNTO Race está claramente orientado a deportistas que hacen entrenamientos largos y variados. Lo llevé en una
      ruta de montaña de 20 km con bastante desnivel y el GPS clavó cada tramo. Las métricas de altitud y esfuerzo son
      muy precisas, y la batería aguantó sin problema. Eso sí, la interfaz es algo menos intuitiva que en Garmin, pero
      si estás acostumbrado al ecosistema Suunto, te encantará.
    enlace: https://amzn.to/4jVLzJi
    imagen: https://m.media-amazon.com/images/I/41tS9LabReL._SL500_.jpg
    lo_mejor: 🏔 Muy robusto ⚡ Preciso en montaña 🔋 Autonomía top 🔄 Ideal para trail y ultras
    nombre: SUUNTO Race
    valoracion: 4
    precio: "368,00\_€"
    precioOriginal: "399,00\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41zaxb529aL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51qIQDF1gnL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51Y44PnnTeL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41FK0oMt+bL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51tSDQ+8GAL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51ax40cqyyL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/519RORLD8AL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41YYB5eAYCL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41jy4yMwQzL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 400
  - ASIN: B0B64J7YQC
    a_tener_en_cuenta: ⚙️ Menús algo lentos ⛰️ Menos potente en trail que otros SUUNTO
    brand: Suunto
    caracteristicas:
      - Diseño fino y elegante con materiales premium
      - Más de 25 h de autonomía con GPS
      - Buen sensor óptico y análisis de sueño
      - Navegación básica pero funcional
      - 'Ligero: apenas 52 gramos'
    descripcion: >-
      El SUUNTO 9 Peak combina estética y resistencia como pocos. Lo llevé durante una semana completa y aún me sobraba
      batería. Es muy fino y ligero, pero aguanta entrenamientos duros con solvencia. Ideal si haces tanto trail como
      deporte urbano y no quieres ir cambiando de reloj.
    enlace: https://amzn.to/4n6YGdk
    imagen: https://m.media-amazon.com/images/I/41l7iWk4f7L._SL500_.jpg
    lo_mejor: 🪶 Muy ligero y cómodo 💎 Diseño elegante 📊 Buenas métricas básicas
    nombre: SUUNTO 9 Peak
    valoracion: 4
    precio: "259,00\_€"
    precioOriginal: "349,00\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51LtElxPkxL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41XV4UfOL4L._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51TZ3gkOCkL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51jatyz2OhL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41S6FlQbnKL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41u0AuHP0rL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51ARz4o8Y-L._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/51ESftdbkYL._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41qrQFEQr0L._SL500_.jpg
        width: 400
        height: 500
      - url: https://m.media-amazon.com/images/I/41K1sUQPPdL._SL500_.jpg
        width: 400
        height: 500
    imagenHeight: 500
    imagenWidth: 400
  - ASIN: B07WQGY2RW
    a_tener_en_cuenta: 📺 Pantalla básica 🧓 Diseño algo anticuado
    brand: Polar
    caracteristicas:
      - Sensor óptico fiable en carrera continua
      - Pantalla monocromo visible en cualquier condición
      - Hasta 8 h con GPS activo
      - Sincronización con Polar Flow y exportación a Strava
      - Buen ajuste en muñeca y menú sencillo
    descripcion: >-
      El Polar M430 ya lleva años en el mercado, pero sigue siendo una opción sólida para quienes no necesitan
      florituras. Lo he usado en sesiones básicas de running y su GPS y sensor óptico cumplen con nota. La pantalla no
      es la más moderna, pero es muy legible. Lo mejor, sin duda, es su fiabilidad y sencillez. Perfecto si solo quieres
      salir a correr y registrar bien tus datos sin pagar de más.
    enlace: https://amzn.to/45xfHHA
    imagen: https://m.media-amazon.com/images/I/414EGaCilIL._SL500_.jpg
    lo_mejor: 🧭 Fiable y preciso 💰 Muy buen precio 📉 Ideal para corredores básicos
    nombre: Polar M430
    valoracion: 3
    precio: "149,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41kmzKXLNzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41-i73jTqIL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31L6cTfNUsL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51aknVTz2aL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0CFQQ9FDL
    a_tener_en_cuenta: 📦 Ecosistema menos conocido que Garmin o Polar
    brand: COROS
    caracteristicas:
      - GPS multibanda ultra preciso
      - Hasta 38 h de batería con GPS
      - 'Ligero: solo 30g'
      - Ideal para entrenamientos avanzados por potencia
      - App COROS muy completa e intuitiva
    descripcion: >-
      El COROS Pace 3 es uno de los relojes más sorprendentes del último año. Lo usé en pista y en trail, y la precisión
      de su GPS multibanda es sencillamente increíble. Es muy ligero, intuitivo y con una batería que aguanta lo que le
      eches. Además, su app es de las más claras y completas del mercado. Por el precio que tiene, es una auténtica
      joya.
    enlace: https://amzn.to/3HMMiiC
    imagen: https://m.media-amazon.com/images/I/41k6eLvveVL._SL500_.jpg
    lo_mejor: 🛰 GPS perfecto 💪 Muy completo 💸 Relación calidad-precio insuperable
    nombre: COROS Pace 3
    valoracion: 5
    precio: "249,00\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41pT8spn5VL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ROEa2IFiL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41XlckXO3FL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Y7JxWu8sL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41jT+ojYIWL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41hvwxIrxgL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51UUFGnoZhL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
