# _config.yml

title: Recomendador.net
description: Guías de compra realizadas por expertos.
url: "https://recomendador.net" # tu dominio en producción
baseurl: "" # déjalo vacío si el sitio está en la raíz del dominio
author:
  name: "Carlos López"
  email: recomendadorwebnet@gmail.com
lang: es
timezone: Europe/Madrid

# Directorios
include: ["_pages"]
exclude: ["node_modules/", "vendor/", "Gemfile", "Gemfile.lock", "README.md"]

# Permalink limpio
permalink: /:categories/:title/

# Markdown por defecto
markdown: kramdown

plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll/tagging
  - jekyll-seo-tag

# Soporte para includes con relative_url
defaults:
  - scope:
      path: ""
    values:
      layout: default

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  auto: true
  indexpage: 'index.html'

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty
tag_permalink: '/tag/:name/'

jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layouts:
    year: archive
    month: archive
    tag: archive
    category: archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    tag: '/tag/:name/'
    category: '/categoria/:name/'