productos:
  - ASIN: B0DYYMWB8Y
    a_tener_en_cuenta: No incluye complementos
    caracteristicas:
      - Diseño triangular tipo pico 🧵
      - Disponible en varios colores ✨
      - Bordado con acabado brillante 💮
      - Ligero y fácil de plegar 👜
      - Perfecto para ferias o bailes 💃
    descripcion: >-
      Mantón clásico de estilo Manila con forma triangular y bordados elegantes. Disponible en múltiples colores, ideal
      para ferias, espectáculos o eventos culturales.
    enlace: https://amzn.to/4mm5q5R
    lo_mejor: Muchos colores disponibles 🎨, ideal para eventos tradicionales
    nombre: Mantón de Manila Mujer de Pico en Triángulo
    valoracion: 4.6
    brand: Yusons
    precio: Sin precio
    precioOriginal: No especificado
    disponibilidad: Sin info
    imagen: https://m.media-amazon.com/images/I/41TNOw2psUL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51NiumzLomL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41OqxinIs+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41hK6V5RJXL._SL500_.jpg
        width: 401
        height: 500
      - url: https://m.media-amazon.com/images/I/515394sTGDL._SL500_.jpg
        width: 359
        height: 500
      - url: https://m.media-amazon.com/images/I/41+kP4IIxRL._SL500_.jpg
        width: 458
        height: 500
      - url: https://m.media-amazon.com/images/I/419h57azfWL._SL500_.jpg
        width: 454
        height: 500
    caracteristicasAmazon:
      - 'Material: 100% poliéster. Mantón tradicional popular con estampado de flores.'
      - 'Mantón de manilla de gran tamaño: Mira foto de medida de cada modelo, son medidas adultos.'
      - Talla única, una variedad de colores para elegir, fucsia, negro, blanco, rojo......
      - >-
        Ligero y suave, úsalo como chal, ya sea sobre los hombros o la cabeza. Ideal para la fiesta de abril, baile de
        flamenco español tradicional.
      - >-
        Regalo perfecto: esta gran bufanda se puede presentar como un regalo a tu familia, amigos e incluso a ti mismo
        en Acción de Gracias, Navidad, cumpleaños, Día de la Madre o algunos días especiales.
  - ASIN: B0F5N45BR5
    a_tener_en_cuenta: Es grande, no apto para niñas pequeñas
    caracteristicas:
      - Bordado floral llamativo 🌸
      - Acabado en flecos largos ✂️
      - Tela suave y fluida 🧣
      - Ideal para ferias y bailes 🎶
      - Disponible en varios tonos vivos 🌈
    descripcion: >-
      Elegante mantón bordado con flores grandes, pensado para uso adulto. Su tacto suave y sus acabados lo hacen ideal
      para celebraciones o trajes regionales.
    enlace: https://amzn.to/3UC7R8G
    lo_mejor: Muchos colores disponibles 🌺, muy vistoso sobre vestido liso
    nombre: Mantón Bordado en Flores Para Adulto
    valoracion: 4.7
    brand: MUNDDY
    precio: "9,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41Viob2u66L._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 499
    imagenesVariantes: []
    caracteristicasAmazon:
      - Mantón de manila bordado de Flores con acabado en pico
      - >-
        Disponible en varios colores y diseños diferentes para que elija el que más le guste y mejor se adapte a sus
        necesidades.
      - Fabricado 100% en poliester de gran calidad. Sus medidas son 150x70cm (adulta)
      - >-
        Perfecto para todo tipo de eventos o celebraciones o para llevarlo en el día a día. Muy elegante y conjuntará
        perfectamente con el look que elija.
      - Envio desde madrid por pàquete estandar o Express segun su nesecidad.
  - ASIN: B0F66Y545P
    a_tener_en_cuenta: Algo voluminoso si se dobla mal
    caracteristicas:
      - Flecos largos y resistentes 🪡
      - Diseño floral bordado 🎨
      - Tacto agradable y liviano 🪶
      - Ideal para trajes de feria 💃
      - Disponible en varios colores 💫
    descripcion: >-
      Mantón de gran tamaño con flores bordadas en diferentes tonos. Pensado para complementar trajes flamencos o
      regionales, añade elegancia y color.
    enlace: https://amzn.to/4l7X154
    lo_mejor: Muchos colores disponibles 🌹, realza cualquier vestido
    nombre: Mantón Bordado en Flores Para Adulto
    valoracion: 4.8
    brand: MUNDDY
    precio: "8,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51kjG1JL1PL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 499
    imagenesVariantes: []
    caracteristicasAmazon:
      - Mantón de manila bordado de Flores con acabado en pico
      - >-
        Disponible en varios colores y diseños diferentes para que elija el que más le guste y mejor se adapte a sus
        necesidades.
      - Fabricado 100% en poliester de gran calidad. Sus medidas son 150x70cm (adulta)
      - >-
        Perfecto para todo tipo de eventos o celebraciones o para llevarlo en el día a día. Muy elegante y conjuntará
        perfectamente con el look que elija.
      - Envio desde madrid por pàquete estandar o Express segun su nesecidad.
  - ASIN: B07TJZ8WQ1
    a_tener_en_cuenta: Tamaño reducido para uso infantil
    caracteristicas:
      - Diseño ligero y cómodo 👧
      - Flecos cortos y seguros ✂️
      - Colores vivos y alegres 🌟
      - Perfecto para actuaciones escolares 🎭
      - Bordado bonito y sencillo 🌼
    descripcion: >-
      Mantón infantil con bordado floral y flecos suaves, pensado para niñas en fiestas o eventos escolares. Muy cómodo
      de llevar.
    enlace: https://amzn.to/4fhhinp
    lo_mejor: Muchos colores disponibles 🎈, ideal para niñas pequeñas
    nombre: Mantón Bordado en Flores Para niña
    valoracion: 4.5
    brand: MUNDDY
    precio: "10,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51lIVUhV6wL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/519mhHterML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31URLUc6cyL._SL500_.jpg
        width: 500
        height: 373
    caracteristicasAmazon:
      - Mantón de manila bordado de Flores con acabado en pico
      - >-
        Disponible en varios colores y diseños diferentes para que elija el que más le guste y mejor se adapte a sus
        necesidades.
      - Fabricado 100% en poliester de gran calidad. Sus medidas son 100x45cm(niña)
      - >-
        Perfecto para todo tipo de eventos o celebraciones o para llevarlo en el día a día. Muy elegante y conjuntará
        perfectamente con el look que elija.
      - Envio desde madrid por pàquete estandar o Express segun su nesecidad.
  - ASIN: B07TJZ383Z
    a_tener_en_cuenta: No lleva bordado
    caracteristicas:
      - Tela lisa sin estampado 🧵
      - Disponible en colores intensos 🌈
      - Diseño versátil y elegante 👗
      - Se pliega fácilmente 👜
      - Ideal como complemento de diario o feria 🎉
    descripcion: >-
      Mantón liso sin bordado, ideal para quienes buscan un look más sencillo. Disponible en colores lisos pero
      vistosos, combina con cualquier traje.
    enlace: https://amzn.to/40JMVA8
    lo_mejor: Muchos colores disponibles 🧡, diseño más minimalista
    nombre: Mantón de Colores Liso Para Adulto
    valoracion: 4.4
    brand: MUNDDY
    precio: "11,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41uUze5nUjL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51lTuT79reL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31gKHsKLU1L._SL500_.jpg
        width: 500
        height: 373
    caracteristicasAmazon:
      - Mantón de manila de Color liso con acabado en pico
      - >-
        Disponible en varios colores y diseños diferentes para que elija el que más le guste y mejor se adapte a sus
        necesidades.
      - Fabricado 100% en poliester de gran calidad. Sus medidas son 150x70cm (adulta)
      - >-
        Perfecto para todo tipo de eventos o celebraciones o para llevarlo en el día a día. Muy elegante y conjuntará
        perfectamente con el look que elija.
      - Envio desde madrid por pàquete estandar o Express segun su nesecidad.
  - ASIN: B06XY2S6Z7
    a_tener_en_cuenta: Tamaño algo justo si se desea cubrir hombros anchos
    caracteristicas:
      - Talla M (ideal para adultos) 📏
      - Diseño de flores tradicionales 🌺
      - Con flecos decorativos 🧵
      - Tejido ligero pero resistente 💪
      - Disponible en múltiples colores 🎨
    descripcion: >-
      Clásico mantón de flamenco con bordado tradicional. Talla media, ideal para mujeres adultas. Disponible en varios
      colores intensos.
    enlace: https://amzn.to/4m5wgj5
    lo_mejor: Muchos colores disponibles 🔥, bordado clásico muy vistoso
    nombre: Mantón de Manila de Flamenco Talla M
    valoracion: 4.6
    brand: La Senorita
    precio: "26,95\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/510TQv5hVNL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 320
    imagenesVariantes: []
    caracteristicasAmazon:
      - >-
        *PARA CLASES DE FLAMENCO & TODAS LAS EDADES: Su tamaño [160 x 80 cm] excluyendo flecos. se adapta perfectamente
        a la mayoría de las siluetas. Es el mantón perfecto para llevar con tu vestido de flamenca, o para las niñas que
        van a clases de baile flamenco o sevillanas. ¡Mantones flamencos para hijas y mamás!
      - >-
        *MANTÓN TRIANGULAR & TEXTURA LIGERA: Los mantones de flamenca tienen que ser ligeros que te permitan tener
        flexibilidad y dinamismo en el baile. Los mantones de La Señorita están pensados para que los puedas colocar
        fácilmente sobre los hombros y con la consistencia adecuada para que el vuelo del mantón sea perfecto mientras
        que bailas. Bordado a una cara. 6 flecos por nudo!!! Flecos: 23cm
      - >-
        *MIL MANERAS DE LLEVAR UN MANTÓN DE MANILA. Hay muchas formas de ponerse un mantón de manila. Lo importante es
        que el modelo que elijas se adapte a cómo quieres colocártelo. Entre las formas más tradicionales tienes echado
        en forma de pico sobre los hombros, anudado en la cintura al más puro estilo zíngaro o echado simplemente por
        uno de los hombros. ¡Tú eliges!
      - >-
        *COMPLEMENTO PARA BODAS Y EVENTOS. Este mantón de manila es ese chal con flecos que siempre debes tener en tu
        fondo de armario para acudir a una boda o evento. Por su tamaño, colores y textura, lo puedes utilizar como chal
        y se combina fácilmente con cualquier tipo de prendas, desde las más clásicas hasta las más urbanas.
      - >-
        *CUIDADO FÁCIL: Los mantones La Señorita están realizados en poliéster de alta calidad para que sea muy fácil su
        cuidado y mantenimiento. Recomendamos el lavado a mano para que los flecos y el bordado permanezca intacto
        durante mucho tiempo.
  - ASIN: B07JGYWHQY
    a_tener_en_cuenta: Requiere saber colocarlo bien por su tamaño
    caracteristicas:
      - Talla L para mayor cobertura 📐
      - Flecos largos y bien rematados ✂️
      - Diseño clásico bordado 🌹
      - Amplia variedad de colores 💫
      - Perfecto para bailes o exhibiciones 🔥
    descripcion: >-
      Mantón bordado de gran tamaño para flamenco, ideal para cubrir bien los hombros. Estilo clásico con flecos largos
      y colores variados.
    enlace: https://amzn.to/3INSgAq
    lo_mejor: Muchos colores disponibles 💃, cubre perfectamente la espalda
    nombre: Mantón de Manila de Flamenco Talla L
    valoracion: 4.7
    brand: La Senorita
    precio: "29,95\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41ChFHsIMFL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 283
    imagenesVariantes: []
    caracteristicasAmazon:
      - >-
        *PARA CLASES DE FLAMENCO & TODAS LAS EDADES: Su tamaño [190 x 90 cm] GRANDE, excluyendo flecos. se adapta
        perfectamente a la mayoría de las siluetas. Es el mantón perfecto para llevar con tu vestido de flamenca, o para
        las niñas que van a clases de baile flamenco o sevillanas. ¡Mantones flamencos para hijas y mamás!
      - >-
        *MANTÓN TRIANGULAR & TEXTURA LIGERA: Los mantones de flamenca tienen que ser ligeros que te permitan tener
        flexibilidad y dinamismo en el baile. Los mantones de La Señorita están pensados para que los puedas colocar
        fácilmente sobre los hombros y con la consistencia adecuada para que el vuelo del mantón sea perfecto mientras
        que bailas. Bordado a una cara, 6 flecos por nudo!!! Flecos: 23cm
      - >-
        *MIL MANERAS DE LLEVAR UN MANTÓN DE MANILA. Hay muchas formas de ponerse un mantón de manila. Lo importante es
        que el modelo que elijas se adapte a cómo quieres colocártelo. Entre las formas más tradicionales tienes echado
        en forma de pico sobre los hombros, anudado en la cintura al más puro estilo zíngaro o echado simplemente por
        uno de los hombros. ¡Tú eliges!
      - >-
        *COMPLEMENTO PARA BODAS Y EVENTOS. Este mantón de manila es ese chal con flecos que siempre debes tener en tu
        fondo de armario para acudir a una boda o evento. Por su tamaño, colores y textura, lo puedes utilizar como chal
        y se combina fácilmente con cualquier tipo de prendas, desde las más clásicas hasta las más urbanas.
      - >-
        *CUIDADO FÁCIL: Los mantones La Señorita están realizados en poliéster de alta calidad para que sea muy fácil su
        cuidado y mantenimiento. Recomendamos el lavado a mano para que los flecos y el bordado permanezca intacto
        durante mucho tiempo.
  - ASIN: B0CW1ZWZX8
    a_tener_en_cuenta: Solo 3 colores disponibles
    caracteristicas:
      - Incluye flor y peine a juego 💄
      - Bordado floral delicado 🌸
      - Tejido suave y ligero 🪶
      - Ideal para ferias y espectáculos 🎭
      - Disponible en blanco, negro y rojo ⚫🔴⚪
    descripcion: >-
      Este set incluye un mantón bordado y varios accesorios como flor y peine. Ideal para vestir completo en eventos o
      ferias.
    enlace: https://amzn.to/4fePoZg
    lo_mejor: Incluye complementos 💐, disponible en blanco, negro y rojo
    nombre: Mantón Bordado en Flores con set de complementos
    valoracion: 4.8
    brand: Generic
    precio: "19,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51sUeO1LLEL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41Cb1YNeo8L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41qq-UNNVDL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41OEpeuHOJL._SL500_.jpg
        width: 289
        height: 500
      - url: https://m.media-amazon.com/images/I/41rI7OyJfeL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31eWOAysNpL._SL500_.jpg
        width: 281
        height: 500
    caracteristicasAmazon:
      - Este paquete incluye mantón, collar, flor y peineta flamenca para adultos.
      - Chal de baile flamenco español bordado en flores para adulto.
      - 'Talla única para la mayoría: 156 cm de ancho x 78 cm de alto. ¡Excluyendo flecos!'
      - Agradable para combinar con los zapatos y vestidos de flamenco español.
