productos:
  - ASIN: B0CMZNNRZF
    a_tener_en_cuenta: A partir de 1 año
    brand: HOMCOM
    caracteristicasAmazon:
      - >-
        LICENCIA DE VESPA: Esta moto eléctrica cuenta con licencia oficial de VESPA y está recomendada para niños
        mayores de 18 meses (bajo la supervisión de un adulto) y soporta un peso de hasta 25 kg. Perfecta para jugar
        tanto en exteriores como en interiores
      - >-
        FÁCIL DE USAR CON VELOCIDAD DE SEGURIDAD: Al ser una moto pensada para los más pequeños es muy fácil de manejar,
        simplemente accionando el pedal irá hacia adelante con una velocidad máxima de 3 km/h
      - >-
        SEGURA Y ESTABLE: Sus 4 ruedas, 2 anchas y 2 ruedines auxiliares, aseguran que tu bebé viaje de forma estable y
        segura. Además, el asiento amplio de PP, es muy cómodo para su uso
      - >-
        CONDUCCIÓN REALISTA: Incluso los más peques de la casa pueden disfrutar de una conducción realista con esta moto
        que tiene faro (delantero con luz real), manillar con bocina y pedal como las de verdad. El faro delantero se
        ilumina al pisar el pedal
      - >-
        AUTONOMÍA DE 45 MINUTOS: Cuenta con una batería de 6 V que se recomienda cargar durante 9-10 horas la primera
        vez, y unas 8 horas las siguientes. De este modo (dependiendo del tipo de uso) puede tener una autonomía de
        hasta 45 minutos. Medidas totales: 66,5x38x52 cm (LxANxAL)
    descripcion: >-
      Probamos la HOMCOM Moto Eléctrica Vespa en casa y también en el parque, ¡y fue un éxito total! Esta moto eléctrica
      cuenta con licencia oficial de VESPA y está recomendada para niños mayores de 18 meses (bajo la supervisión de un
      adulto) y soporta un peso de hasta 25 kg. Perfecta para jugar tanto en exteriores como en interiores, que le dan
      un toque muy realista. Ideal para dar sus primeros paseos con una sonrisa de oreja a oreja.
    disponibilidad: En stock
    enlace: https://amzn.to/4l4UVD2
    imagen: https://m.media-amazon.com/images/I/41SaPf29KBL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41JEEUOk34L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/511MhK-WicL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41M8jRQ4diL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41m6R1rYwQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51dtQ471+SL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41E3zsDlWXL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41KoKYONwVL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/4125M8rJaAL._SL500_.jpg
        width: 500
        height: 500
    nombre: HOMCOM Moto Eléctrica Vespa
    precio: "82,99\_€"
    precioOriginal: "87,99\_€"
  - ASIN: B07MT59Z1D
    a_tener_en_cuenta: 1 a 3 años
    brand: HOMCOM
    caracteristicasAmazon:
      - >-
        CON LICENCIA BMW: Esta moto infantil tiene licencia oficial BMW, concretamente del modelo S1000RR, y es ideal
        para niños de entre 18 y 36 meses. Además, incorpora música y faros para una conducción más realista
      - >-
        FÁCIL DE MANEJAR Y SEGURA: Esta moto eléctrica para niños es muy fácil de conducir. Solo necesitas pulsar el
        botón de arranque/parada y pisar el pedal para acelerar. Además, tiene ruedas extra anchas y una velocidad
        máxima de 2,5 km/h
      - >-
        FUNCIONES DE MÚSICA Y FAROS: Esta motocicleta de 3 ruedas cuenta con música integrada y faros, lo que la hace
        más realista y ofrece a tu pequeño momentos emocionantes y divertidos mientras juega
      - >-
        AUTONOMÍA: Después de una carga completa (normalmente de 8 a 12 horas, 4 a 6 horas la primera vez), esta moto
        eléctrica infantil tiene una autonomía aproximada de 45 minutos (dependiendo del tipo de uso)
      - >-
        MEDIDAS TOTALES: 66x37x44 cm (LxANxAL). Peso máximo soportado: 20 kg. Edad recomendada: 18-36 meses. Cumple con:
        EN71-1,2,3,EMC,EN62115 y CE RoHS. Requiere montaje
    descripcion: >-
      Probamos la HOMCOM Moto Eléctrica para Niños en casa y también en el parque, ¡y fue un éxito total! El montaje fue
      sencillo y en pocos minutos ya estaba lista para rodar. Esta moto infantil tiene licencia oficial BMW,
      concretamente del modelo S1000RR, y es ideal para niños de entre 18 y 36 meses. Además, incorpora música y faros
      para una conducción más realista. Una opción estupenda para que empiecen a disfrutar de la conducción desde
      pequeños.
    disponibilidad: En stock
    enlace: https://amzn.to/4moj88C
    imagen: https://m.media-amazon.com/images/I/41rw7ie1wgL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51nhelHDVtL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/5195FZWLEOL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51b-HWw0COL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51hI9y0pyKL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/514qr4X3WnL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41iLDiCkBOL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51IZXdba3nL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41BxrtuTXlL._SL500_.jpg
        width: 500
        height: 500
    nombre: HOMCOM Moto Eléctrica para Niños
    precio: "71,99\_€"
    precioOriginal: "78,99\_€"
  - ASIN: B08J82PGH6
    a_tener_en_cuenta: A partir de 2 años
    brand: TURBO CHALLENGE
    caracteristicasAmazon:
      - >-
        A TODO GAS: Este vehículo proporcionará horas de diversión a todos los pilotos en ciernes durante 45 minutos a
        toda velocidad. Lo mejor: el scooter tiene un pedal de aceleración y el claxon suena.
      - >-
        CONTENIDO: La caja contiene: 1 vehículo vespa gts, equipado con una batería de 30W que le permite moverse a una
        velocidad de 2 km/h, manteniéndose estable y controlable. Viene con 1 batería de 6V y cargador USB incluidos.
      - >-
        DENTRO Y FUERA: Nuestro vehículo está fabricado con plástico para garantizar una durabilidad máxima. El tiempo
        de carga es de 8/10 horas para una autonomía de 40 minutos. Se puede utilizar tanto en interiores como en
        exteriores.
      - >-
        SOBRE RUEDAS: Velocidad, aventuras y emociones fuertes, es lo que los numerosos vehículos de control remoto
        desarrollados por Turbo Challenge ofrecen a los pequeños pilotos.
      - >-
        SOBRE RUEDAS: Velocidad, aventuras y emociones fuertes, es lo que los numerosos vehículos de control remoto
        desarrollados por Turbo Challenge ofrecen a los pequeños pilotos.
    descripcion: >-
      Hemos estado usando la TURBO CHALLENGE Baby Driver Vespa GTS estos días y la verdad es que ha sido todo un
      acierto. Mis hijos se sintieron seguros desde el primer momento. Este vehículo proporcionará horas de diversión a
      todos los pilotos en ciernes durante 45 minutos a toda velocidad. Sin duda, repetiría la compra viendo lo bien que
      se lo pasan.
    disponibilidad: En stock
    enlace: https://amzn.to/4o7Bz2S
    imagen: https://m.media-amazon.com/images/I/41jtL9g6N9L._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51QUZvqyd2L._SL500_.jpg
        width: 471
        height: 500
      - url: https://m.media-amazon.com/images/I/51an4pmxveL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41YapsptSTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41wgqYTvp8L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/61lrymVbIIL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51NE8f6XsnL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51xbuAZNJPL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51vGgKMhz7L._SL500_.jpg
        width: 500
        height: 500
    nombre: TURBO CHALLENGE Baby Driver Vespa GTS
    precio: "99,90\_€"
    precioOriginal: No especificado
  - ASIN: B0BJDKDV86
    a_tener_en_cuenta: A partir de 2 años
    brand: HOMCOM
    caracteristicasAmazon:
      - >-
        CONDUCCIÓN REALISTA: Esta motocicleta BMW HP4, acabada con imitación fibra de carbono, está equipada con faros,
        acelerador en el pedal, botón de avance y retroceso, velocidad de 2,5 km/h y música para que tus hijos disfruten
        de una experiencia de conducción auténtica
      - >-
        AUTONOMÍA: Tras una carga completa (normalmente 10 h, 8-12 h la primera vez), esta motocicleta de juguete para
        niños tiene una autonomía aproximada de 45 minutos (según el tipo de uso), tiempo suficiente para que los niños
        puedan jugar y disfrutar de un agradable paseo
      - >-
        CON MÚSICA: Esta moto eléctrica infantil ofrece múltiples opciones de música (sonidos/ canciones/botón de
        aprendizaje de canciones para niños), entradas TF, USB y AUX para conectarse a un dispositivo y multiplicar las
        opciones de entretenimiento y diversión
      - >-
        MÁXIMA SEGURIDAD: Esta motocicleta eléctrica para niños tiene un asiento amplio y cómodo, 3 ruedas texturizadas
        extra anchas y un manillar para mantener el equilibrio mientras conduces. Esta moto para niños permite que tu
        hijo se divierta con total seguridad
      - >-
        MEDIDAS TOTALES: 82,5x42x54 cm (LxANxAL). Peso máximo soportado: 30 kg. Apto para niños de 18 a 60 meses.
        Requiere montaje
    descripcion: >-
      La HOMCOM Moto Eléctrica BMW HP4 fue un regalo reciente para mi peque y no ha dejado de jugar con ella. Esta
      motocicleta, acabada con imitación fibra de carbono, está equipada con faros, acelerador en el pedal, botón de
      avance y retroceso, velocidad de 2,5 km/h y música para que tus hijos disfruten de una experiencia de conducción
      auténtica. Tras una carga completa (normalmente 10 h, 8-12 h la primera vez), esta motocicleta de juguete para
      niños tiene una autonomía aproximada de 45 minutos (según el tipo de uso), tiempo suficiente para que los niños
      puedan jugar y disfrutar de un agradable paseo. Sin duda, repetiría la compra viendo lo bien que se lo pasan.
    disponibilidad: En stock
    enlace: https://amzn.to/4l6m2ha
    imagen: https://m.media-amazon.com/images/I/41RgnKmdpwL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51PoaQRIitL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51oB+68826L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51fRrgPVwaL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Rucs1zx2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/512mmE+MsfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51tJqoE0DBL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51VUsUknK4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51jvS5w8j6L._SL500_.jpg
        width: 500
        height: 500
    nombre: HOMCOM Moto Eléctrica BMW HP4
    precio: "99,99\_€"
    precioOriginal: "103,99\_€"
  - ASIN: B0DJM8FKMR
    a_tener_en_cuenta: A partir de 2 años
    brand: AIYAPLAY
    caracteristicasAmazon:
      - >-
        MÁXIMA DIVERSIÓN: Los niños disfrutarán pilotando esta motocicleta eléctrica infantil que se mueve hacia
        adelante y hacia atrás, con una divertida función de hacer burbujas mientras suena música. Esto garantiza horas
        de entretenimiento sin fin (líquido para burbujas no incluido)
      - >-
        CON LUZ DE VERDAD: Los pequeños se divertirán explorando incluso al anochecer con esta moto a batería para niños
        equipada con un faro funcional para iluminar el camino y tres ruedas estables que aseguran su seguridad en todo
        momento
      - >-
        DISEÑO LLAMATIVO Y FUNCIONAL: Esta moto para niños combina diversión y seguridad con un diseño práctico en un
        vibrante color verde. Es ideal para acompañar a los pequeños en sus aventuras diarias, ofreciendo horas de
        entretenimiento
      - >-
        VELOCIDAD SEGURA Y AJUSTABLE: Con una velocidad ajustable entre 2,5 y 3 km/h, esta motocicleta eléctrica está
        diseñada para seguir el ritmo de un adulto caminando, garantizando una conducción segura y adecuada para los
        niños
      - >-
        MEDIDAS TOTALES: 80x36x43,5 cm (LxANxAL). Peso máximo soportado: 30 kg. Requiere montaje. Cumple con la
        normativa: EN71-1-2-3, EN62115
    descripcion: >-
      Hemos estado usando la AIYAPLAY Moto Eléctrica para Niños estos días y la verdad es que ha sido todo un acierto.
      Los niños disfrutarán pilotando esta motocicleta eléctrica infantil que se mueve hacia adelante y hacia atrás, con
      una divertida función de hacer burbujas mientras suena música. Esto garantiza horas de entretenimiento sin fin
      (líquido para burbujas no incluido), que le dan un toque muy realista. Una opción estupenda para que empiecen a
      disfrutar de la conducción desde pequeños.
    disponibilidad: En stock
    enlace: https://amzn.to/3UDLjUW
    imagen: https://m.media-amazon.com/images/I/41Tq4YK3HKL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51oSI9BGw7L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51apn6441UL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51b5RXb6YuL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ILrNNvxoL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51dFMJ4RaVL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41dbPGLH4FL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41jOGPwWTxL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41OJZME66nL._SL500_.jpg
        width: 500
        height: 500
    nombre: AIYAPLAY Moto Eléctrica para Niños
    precio: "48,75\_€"
    precioOriginal: "52,69\_€"
titulo_a_tener_en_cuenta: Edad recomendada
