productos:
  - ASIN: B0CM61498D
    a_tener_en_cuenta: hasta 12 años
    enlace: https://amzn.to/3H2yBMz
    nombre: RCB TECH R9X Moto Eléctrica Infantil
    brand: RCB TECH
    precio: "299,99\_€"
    precioOriginal: "339,99\_€"
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41-mVwXDybL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/510pIlBGFGL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Z+gm7GjUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51zEOh8MRmL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51msduEf2vL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ZPi9jVzEL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51MRrVZDB6L._SL500_.jpg
        width: 500
        height: 500
    caracteristicasAmazon:
      - >-
        Potente motocicleta para niños: motocicleta todoterreno RCB TECH para niños velocidad máxima 25KM/H, batería de
        alta calidad 36V 4AH, autonomía máxima 15KM (depende de las condiciones de la carretera, velocidad y peso).
      - >-
        Buen rendimiento de seguridad: diseño de alta elasticidad de doble absorción de impactos con frenos de tambor,
        proporcionan garantía para los viajes seguros de los niños
      - >-
        Ajuste de tres velocidades: diseño de ajuste de tres velocidades de la moto eléctrica todoterreno 8Km/H 12Km/H
        25Km/H, para satisfacer los requisitos de velocidad de diferentes escenarios.
      - >-
        Cómoda experiencia de conducción: La motocicleta eléctrica está equipada con ruedas de goma de 12 pulgadas, que
        son resistentes al desgaste y proporcionan un agarre más fuerte. El asiento antideslizante de alta densidad está
        diseñado ergonómicamente para proporcionar una experiencia de conducción cómoda para los niños.
      - >-
        Diseño con estilo: diseño de forma todoterreno, combinación de colores brillantes, enciende la pasión de los
        niños por la exploración y la aventura.
  - ASIN: B0CQYMNKTC
    a_tener_en_cuenta: hasta 12 años
    enlace: https://amzn.to/4lW2jlm
    nombre: RCB R9X Moto Eléctrica Infantil
    brand: RCB
    precio: "299,99\_€"
    precioOriginal: "369,99\_€"
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41SWpGRO4yL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51NfzCExT5L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/513RQrME-NL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ME7mFEN+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Ka4zLrbqL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51hZikD1HDL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51XiLib8SdL._SL500_.jpg
        width: 500
        height: 500
    caracteristicasAmazon:
      - >-
        🏍️【Minimotocicleta de Gran Potencia】：Diseñado para niños de 3 a 12 años, el patinete eléctrico RCB tiene una
        potente potencia de 300 W y puede alcanzar una velocidad máxima de 25 km/h (las cifras pueden variar en función
        del modo de velocidad, la carga de peso, la batería, la temperatura, las condiciones de la carretera, etc.).
      - >-
        🏍️【Rendimiento de Larga Duración】:La larga duración de la batería de 36V 4AH del moto eléctrico para niños RCB
        proporciona una autonomía de carga completa de hasta 15 kilómetros.
      - >-
        🏍️【Proporciona una garantía más segura】: Diseño de doble amortiguación con frenos de tambor, duraderos y
        fuertes, para proteger los viajes seguros de los niños.
      - >-
        🏍️【Experiencia de conducción confortable】: La moto eléctrica está equipada con ruedas de goma de 12 pulgadas,
        que son resistentes al desgaste y proporcionan un adherencia más fuerte. El asiento antideslizante de alta
        densidad está diseñado ergonómicamente para proporcionar una experiencia de conducción cómoda para los niños.
      - >-
        🏍️【El mejor regalo para su hijo】: El motor produce ondas sonoras que imitan un rugido, añadiendo diversión a la
        conducción. El diseño de estilo todoterreno y la combinación de colores brillantes encienden la pasión de los
        niños por la exploración y la aventura.
  - ASIN: B0BTM3GDC4
    a_tener_en_cuenta: hasta 12 años
    enlace: https://amzn.to/4oi1GEp
    nombre: EVERCROSS EV12M Motocicleta Eléctrica Niños
    brand: EVERCROSS
    precio: "299,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51rjRU0ZZSL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51SsaRE2KlL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51W51QiLvlL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51XAJUGPp4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/517je04T3pL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/61WbnA3yXyL._SL500_.jpg
        width: 500
        height: 500
    caracteristicasAmazon:
      - >-
        AVISO: Esta Moto Eléctrica es pesada, así que asegúrese de que la instalen dos adultos con cuidado. ¡Verifique
        que el vehículo esté correctamente montado antes de conducir! El motor produce una onda de sonido que imita un
        rugido, lo que se suma al placer de conducir.
      - >-
        POTENTE MOTOCICLETA: Diseñada para niños de 3 a 12 años, esta Motocicleta para niños viene con una potente
        potencia de 300 W que le permite alcanzar una velocidad máxima de 15,5 MPH (25 KM/H), y la capacidad de carga
        máxima es de 65 kg. (Los datos pueden variar según factores como el modo de velocidad, la carga de peso, la
        batería, la temperatura, las condiciones de la carretera, etc.)
      - >-
        VELOCIDAD DEL RAYO Y LARGO ALCANCE: La batería de 36V 4AH de la EVERCROSS EV12M Moto Eléctrica ofrece un
        kilometraje completamente cargado de hasta 15KM. La motocicleta eléctrica también cuenta con tres modos de
        velocidad ajustables: 8 KMH, 12 KMH y 25 KMH.
      - >-
        SUSPENSIÓN DE ALTO RENDIMIENTO: Equipada con un sistema de suspensión de alta elasticidad, la motocicleta para
        niños tiene una gran capacidad de absorción de impactos que reduce el impacto de los baches en la carretera
        sobre el conductor. Este sistema se utiliza junto con un sistema de freno de tambor, que es duradero y potente
        para garantizar la seguridad de los niños.
      - >-
        DISEÑO CÓMODO: La Moto Eléctrica cuenta con ruedas de goma resistentes al desgaste de gran tamaño de 12 "que
        brindan un agarre más fuerte. El asiento antideslizante de alta densidad se ajusta al diseño ergonómico y es más
        suave y transpirable, lo que garantiza un cómodo y Experiencia de conducción extrema para niños.
  - ASIN: B0D4QS35W1
    a_tener_en_cuenta: hasta 12 años
    enlace: https://amzn.to/4mf4r8h
    nombre: EVERCROSS EV08M Motocicleta Eléctrica para Niños
    brand: EVERCROSS
    precio: "229,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51XzOezuHQL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51CZZ+XqZoL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41m8jqcV54L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51n6Gf+WRSL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51NXYxDiTzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51FlkFIZSUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51PrReazkKL._SL500_.jpg
        width: 500
        height: 500
    caracteristicasAmazon:
      - >-
        ✨⚫️Potente Motor con Velocidad Dual---Equipado con un motor de 150W, este EVERCROSS EV08M alcanza una velocidad
        máxima de 16KM/H. Además, cuenta con dos marchas de velocidad (8KM/H y 16KM/H) para proporcionar un paseo
        emocionante pero seguro como su hijo crece y gana confianza.
      - >-
        ✨⚫️Batería de Larga Duración y Gran Autonomía---Con una batería de alta eficiencia de 14,4V/4AH, el EV08M ofrece
        una autonomía de aproximadamente 10KM por carga, Esto asegura que los niños puedan disfrutar de un tiempo de
        juego prolongado sin necesidad de recargas frecuentes, por lo que es perfecto para excursiones y paseos más
        largos. (Los datos pueden variar en función del modo de velocidad, el peso del conductor, la batería, la
        temperatura, las condiciones de la carretera, etc.)
      - >-
        ✨⚫️Sistema de Freno Simple para una Mayor Seguridad---El EV08M está equipado con un sistema de freno fácil de
        usar, permitiendo a los niños detener fácilmente el motocross cuando sea necesario. Este sencillo y eficaz
        mecanismo de frenado garantiza que los niños puedan protegerse y mantenerse seguros durante sus paseos.
      - >-
        ✨⚫️Diseño Duradero con Seguridad Mejorada---El moto soporta una carga máxima de 50KG y cuenta con ruedas
        neumáticas de 12 pulgadas para una conducción suave en diversas superficies. La adición de luces delanteras y un
        pedal robusto mejora la seguridad y la visibilidad.
      - >-
        ✨⚫️Diseño Vintage con Características Modernas---La EV08M presenta un diseño retro y una innovadora combinación
        de colores que encantará a los niños. La inclusión de ruedas neumáticas, una luz delantera y un pedal sólido,
        junto con los modos de velocidad dual, garantiza una experiencia de conducción versátil y agradable para los
        niños.
  - ASIN: B0CS2WQKRX
    a_tener_en_cuenta: hasta 12 años
    enlace: https://amzn.to/4ovnyfM
    nombre: EVERCROSS EV05M Moto Eléctrica para Niños
    brand: EVERCROSS
    precio: "207,57\_€"
    precioOriginal: "218,49\_€"
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41y-w-HYYsL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/5162GWA0RfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41waTSoAXmL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41cr00CRHiL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Wkbag77CL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51qcvxfNwAL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51akpBWJpbL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/515hKi90ISL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51LgfwSUA1L._SL500_.jpg
        width: 500
        height: 500
    caracteristicasAmazon:
      - >-
        Nota: Esta motocicleta eléctrica para niños es pesada y debe ser instalada cuidadosamente por dos adultos.
        Asegúrese de que el vehículo está instalado correctamente antes de conducirlo. El motor eléctrico genera ondas
        sonoras que imitan un rugido, lo que contribuye a aumentar el placer de conducir.
      - >-
        POTENTE: La motocicleta eléctrica EVERCROSS está equipada con un motor de alta potencia de 150 vatios, con una
        capacidad de carga máxima de 40 kg, adecuada para niños de 3 a 12 años. (Los datos pueden variar en función del
        modo de velocidad, el peso de la carga, la batería, la temperatura, las condiciones de la carretera, etc.)
      - >-
        MÚLTIPLES VELOCIDADES Y LARGA DISTANCIA: La batería de 14,4 V y 4 Ah de la EVERCROSS EV05M tiene una autonomía
        extra larga de hasta 10 kilómetros (6,2 millas). La motocicleta eléctrica también dispone de dos modos de
        velocidad ajustables: 8 km/h y 16 km/h.
      - >-
        DISEÑO PERFECTO: La moto todoterreno para niños está equipada con grandes ruedas de goma de 12 pulgadas
        resistentes al desgaste para proporcionar un agarre más fuerte. El asiento antideslizante de alta densidad tiene
        un diseño ergonómico, es más suave y transpirable, lo que garantiza una conducción cómoda para los niños.
      - >-
        SEGURIDAD: La bicicleta eléctrica para niños se apoya en un sólido armazón de hierro, que es más resistente y
        duradero. Se utiliza junto con el sistema de freno de sujeción para garantizar la seguridad de los niños.
      - >-
        EL MEJOR REGALO: Regale a sus hijos esta motocicleta eléctrica para cultivar su valor, su pasión por la
        exploración y la aventura a través de una conducción excelente y bajo la protección de la seguridad.
