productos:
- nombre: Razer Huntsman V2 Analog
  lo_mejor: Switches óptico-analógicos con doble acción, construcción premium en aluminio,
    RGB espectacular y reposamuñecas cómodo
  a_tener_en_cuenta: Diseñado para gamers avanzados y pros; gama alta con funciones
    únicas
  enlace: https://amzn.to/43eeeTx
  imagen: images/teclado-gaming-Razer-Huntsman-V2-Analog.webp
  valoracion: 5
  descripcion: 'El Huntsman V2 Analog es un teclado brutal si buscas lo mejor en tecnología
    y precisión. Sus switches ópticos-analógicos permiten programar dos funciones
    por tecla según la presión, algo espectacular en juegos o edición avanzada. La
    construcción es impecable: aluminio, cable trenzado y retroiluminación RGB impresionante.
    Lo he usado con shooters, MOBAs y productividad y siempre me ha respondido al
    máximo nivel. Viene con reposamuñecas y se nota que es un teclado pensado para
    pros.'
  caracteristicas:
  - Switches óptico-analógicos Razer™ Analog
  - Teclas programables con doble acción por presión
  - Iluminación RGB Razer Chroma individual por tecla
  - Reposamuñecas ergonómico incluido
  - Cuerpo de aluminio con acabado premium
  brand: Razer
- nombre: Razer BlackWidow V4 X
  lo_mejor: Switches mecánicos Green muy responsivos, RGB por tecla, rueda multifunción,
    teclas multimedia dedicadas
  a_tener_en_cuenta: No incluye reposamuñecas, pero excelente calidad-precio dentro
    de gama media-alta
  enlace: https://amzn.to/3ZgarUw
  imagen: images/teclado-gaming-Razer-BlackWidow-V4-X.webp
  valoracion: 5
  descripcion: Este teclado combina rendimiento, diseño y funcionalidades avanzadas.
    Sus switches Green son táctiles y muy responsivos, ideales para juegos competitivos
    o escribir con rapidez. Destaco la rueda multifunción y las teclas multimedia
    dedicadas, perfectas para controlar el volumen y música sin salir del juego. El
    RGB por tecla es brillante y se configura fácilmente desde Synapse. Un teclado
    robusto y personalizable sin llegar al precio extremo del V4 Pro.
  caracteristicas:
  - Switches Razer Green (táctiles y clicky)
  - Iluminación RGB individual por tecla
  - Rueda multifunción con funciones personalizables
  - Teclas multimedia dedicadas
  - Estructura sólida con acabados premium
  brand: Razer
- nombre: Razer Ornata V3 X
  lo_mejor: Membrana silenciosa, diseño fino y cómodo, teclas planas y resistentes
    al agua, ideal para trabajar y jugar
  a_tener_en_cuenta: Buena opción económica si no necesitas un teclado mecánico
  enlace: https://amzn.to/3FdWzmU
  imagen: images/teclado-gaming-Razer-Ornata-V3-X.webp
  valoracion: 3.5
  descripcion: El Ornata V3 X es ideal para quienes buscan un teclado económico pero
    con estilo gamer. Su perfil bajo y membrana silenciosa lo hacen perfecto para
    oficina o juegos tranquilos. Me gustó su diseño fino, con teclas planas que se
    sienten suaves y cómodas. Además, es resistente a líquidos, algo muy útil en entornos
    compartidos. No es mecánico, pero cumple bien en navegación y juegos casuales.
    Buena elección por un precio muy reducido.
  caracteristicas:
  - Perfil ultrabajo con teclas planas
  - Membrana silenciosa
  - Iluminación RGB por zonas
  - Resistente a salpicaduras
  - Diseño ligero y cómodo para oficina o gaming
  brand: Razer
- nombre: Razer Apex 3
  lo_mejor: Teclado silencioso con resistencia IP32 al agua, RGB por zonas y controles
    multimedia dedicados
  a_tener_en_cuenta: Perfecto para setups compartidos o nocturnos; sin iluminación
    por tecla
  enlace: https://amzn.to/4j4AKEe
  imagen: images/teclado-gaming-Apex-3.webp
  valoracion: 4
  descripcion: Lo que más me gustó del Apex 3 es lo silencioso que es. Las teclas
    son suaves, ideales para trabajar o jugar sin molestar a nadie. A pesar de ser
    de membrana, su construcción se nota cuidada. Incluye controles multimedia dedicados
    y reposamuñecas. Además, es resistente al agua (IP32), algo poco común. Su iluminación
    RGB por zonas también le da un toque atractivo al setup. Muy recomendable si buscas
    algo silencioso y bien hecho sin romper el presupuesto.
  caracteristicas:
  - Teclas silenciosas de membrana
  - Iluminación RGB por zonas
  - Resistencia IP32 a líquidos
  - Reposamuñecas desmontable
  - Controles multimedia dedicados
  brand: Razer
- nombre: Mars Gaming MKPRO
  lo_mejor: Switches mecánicos OUTEMU, chasis de aluminio, RGB completo y reposamuñecas
    desmontable
  a_tener_en_cuenta: Excelente para empezar en mecánicos sin gastar mucho
  enlace: https://amzn.to/4j6eppL
  imagen: images/teclado-Mars-Gaming-MKPRO.webp
  valoracion: 4.5
  descripcion: El MKPRO es una de las mejores sorpresas de gama baja. Tiene switches
    mecánicos OUTEMU que, si bien no están al nivel de los Cherry o Razer, ofrecen
    una buena experiencia de tecleo. Me sorprendió su construcción en aluminio, que
    lo hace muy robusto para su precio. Además, cuenta con iluminación RGB y un reposamuñecas
    desmontable. Es ideal si quieres un teclado mecánico sin gastar demasiado y sin
    renunciar a estética ni funcionalidades básicas.
  caracteristicas:
  - Switches mecánicos OUTEMU rojos
  - Iluminación RGB completa
  - Reposamuñecas desmontable
  - Chasis de aluminio reforzado
  - Formato completo con anti-ghosting
  brand: Mars
- nombre: Logitech G213 Prodigy
  lo_mejor: Membrana con buena respuesta, RGB por zonas, reposamuñecas integrado,
    resistente a líquidos
  a_tener_en_cuenta: Alternativa silenciosa y cómoda si no necesitas mecánico
  enlace: https://amzn.to/43gMyNV
  imagen: images/g213-gallery-1-nb.webp
  valoracion: 3.5
  descripcion: El G213 es un teclado que ha resistido bien el paso del tiempo. Aunque
    no es mecánico, su membrana ofrece una buena respuesta y es bastante silenciosa.
    Lo he usado tanto para juegos como para escribir y me ha dado resultados sólidos.
    La iluminación RGB por zonas se ve muy bien y se puede configurar con Logitech
    G Hub. Incluye un reposamuñecas integrado muy cómodo. Ideal para presupuestos
    ajustados o setups híbridos.
  caracteristicas:
  - Teclas de membrana silenciosas
  - Iluminación RGB por zonas
  - Reposamuñecas integrado
  - Resistente a salpicaduras
  - Software Logitech G HUB
  brand: Logitech
- nombre: Corsair K55 RGB PRO
  lo_mejor: Teclas macro y multimedia dedicadas, resistencia IP42, RGB por zonas y
    compatible con iCUE
  a_tener_en_cuenta: Ideal para productividad y MMO si no necesitas switches mecánicos
  enlace: https://amzn.to/44FysIo
  imagen: images/K55-RGB-PRO.webp
  valoracion: 4
  descripcion: 'Uno de los teclados más completos por su precio. Me sorprendió la
    cantidad de funciones: tiene teclas dedicadas para macros, multimedia y controles
    rápidos. La iluminación RGB por zonas es bastante llamativa y el software iCUE
    permite personalizar todo. El diseño es sobrio pero robusto, y cuenta con certificación
    IP42 contra derrames. Me ha funcionado genial para MMO y productividad. Muy recomendable
    si no necesitas switches mecánicos.'
  caracteristicas:
  - Teclas macro dedicadas
  - Iluminación RGB por zonas
  - Resistencia al polvo y líquidos (IP42)
  - Controles multimedia dedicados
  - Compatible con Corsair iCUE
  brand: Corsair
- nombre: Razer BlackWidow V3 TKL
  lo_mejor: Formato compacto sin pad numérico, switches Green, RGB individual y diseño
    robusto
  a_tener_en_cuenta: Perfecto para shooters y escritorios con poco espacio
  enlace: https://amzn.to/4j4Gxdc
  imagen: images/blackwidow-v3-tenkeyless.webp
- nombre: Logitech G512
  lo_mejor: Switches GX (Brown, Red o Blue), chasis de aluminio, RGB por tecla y puerto
    USB integrado
  a_tener_en_cuenta: Equilibrio perfecto entre calidad, rendimiento y estética
  enlace: https://amzn.to/4k1m36q
  imagen: images/teclado-gaming-Logitech-G512.webp
  valoracion: 4.5
  descripcion: El Logitech G512 me ha sorprendido por su tacto preciso y construcción
    sólida. Utiliza switches GX mecánicos (puedes elegir entre Brown, Red o Blue),
    muy estables y con buen recorrido. El chasis de aluminio le da un acabado premium
    y muy resistente. El RGB por tecla se ve espectacular, y es totalmente personalizable
    con Logitech G HUB. Perfecto para quienes buscan un teclado mecánico fiable y
    elegante sin complicarse con florituras innecesarias.
  caracteristicas:
  - Switches mecánicos GX (Brown, Red o Blue)
  - Iluminación RGB individual por tecla
  - Estructura de aluminio cepillado
  - Puerto USB passthrough integrado
  - Compatible con Logitech G HUB
  brand: Logitech
- nombre: Logitech G413 TKL SE
  lo_mejor: Diseño TKL compacto, retroiluminación blanca clara, carcasa de aluminio
    y switches táctiles
  a_tener_en_cuenta: Diseño limpio y resistente para setups minimalistas
  enlace: https://amzn.to/3Ziwxpk
  imagen: images/g413-se-tkl-gallery-1-new.webp
  valoracion: 4
  descripcion: La versión TKL del G413 mantiene todo lo bueno del modelo grande, pero
    con un tamaño más compacto. Perfecto para jugadores que quieren más espacio para
    mover el ratón. Es robusto, con carcasa de aluminio y switches táctiles de buena
    respuesta. No tiene RGB, solo luz blanca, pero es muy visible y elegante. Me ha
    resultado muy cómodo en juegos como Apex y Warzone. Cumple con lo esencial sin
    florituras.
  caracteristicas:
  - Formato TKL para mayor espacio en el escritorio
  - Switches táctiles duraderos
  - Chasis de aluminio cepillado
  - Retroiluminación blanca funcional
  - Diseño limpio y sin distracciones
  brand: Logitech