productos:
  - ASIN: B07WFGYJ6R
    a_tener_en_cuenta: Carece de teclado numérico; óptimo para shooters y setups con poco espacio
    brand: Mars Gaming
    caracteristicas:
      - Diseño TKL ultra-compacto que optimiza el espacio en tu escritorio.
      - Switches mecánicos OUTEMU SQ que ofrecen una respuesta rápida y precisa.
      - Retroiluminación RGB con 10 perfiles de luz predefinidos para personalizar tu ambiente de juego.
      - Estructura de ABS que garantiza durabilidad y resistencia al uso intensivo.
      - Incluye reposamuñecas ergonómico para mayor comodidad durante largas sesiones.
    descripcion: >-
      He probado el Mars Gaming MKXTKL durante varias sesiones de juego y ha superado mis expectativas. Su diseño
      compacto TKL me permitió mover el ratón con mayor libertad, algo esencial en shooters. Los switches OUTEMU SQ
      ofrecen una respuesta nítida y rápida, muy útil en situaciones de presión. El teclado se siente firme sobre la
      mesa, sin deslizamientos, y la iluminación RGB es sobria pero efectiva. Además, el reposamuñecas desmontable
      mejora el confort durante sesiones largas sin añadir volumen innecesario.
    enlace: https://amzn.to/4d6kqS9
    imagen: https://m.media-amazon.com/images/I/510yeEk7wkL._SL500_.jpg
    lo_mejor: Switches OUTEMU SQ azules, diseño TKL robusto, reposamuñecas ergonómico, y retroiluminación RGB dinámica
    nombre: Mars Gaming MKXTKL
    valoracion: 4
    precio: "22,90\_€"
    precioOriginal: "24,90\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51+QYTGvEFL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41UbVTckQZL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41HgcgkQquL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51exvEgzzzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/515eMbBV9uL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41FNhRrWQTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41sGNd+swXL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B09MJC4XL5
    a_tener_en_cuenta: Diseño compacto pero incluye teclado numérico; ideal para trabajo y juego
    brand: Mars Gaming
    caracteristicas:
      - Formato full-compacto al 96% que combina funcionalidad completa en un diseño compacto.
      - Switches OUTEMU SQ anti-polvo que prolongan la vida útil del teclado.
      - Teclas PBT Pudding de doble inyección que ofrecen una experiencia de escritura superior.
      - Iluminación RGB CHROMA con efectos personalizables para un estilo único.
      - Conexión USB-C desmontable que facilita el transporte y la organización del cableado.
    descripcion: >-
      El Mars Gaming MKULTRA lo he usado tanto para trabajo como para gaming y se comporta muy bien en ambos casos. Su
      formato 96% conserva el teclado numérico sin ocupar tanto espacio como uno full-size. Los switches son agradables
      al tacto, con una pulsación silenciosa y estable. El reposamuñecas incluido mejora bastante la postura en sesiones
      largas. La iluminación RGB es intensa gracias a las teclas PBT Pudding, y el software permite muchas opciones de
      personalización.
    enlace: https://amzn.to/44sorhy
    imagen: https://m.media-amazon.com/images/I/4141uu0sUfL._SL500_.jpg
    lo_mejor: Formato 96%, switches OUTEMU SQ rojos silenciosos, teclas PBT pudding, y software para personalización RGB
    nombre: Mars Gaming MKULTRA
    valoracion: 5
    precio: "95,88\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51FmcV-qGzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Tnt9yBZaL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51aCeccGK4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/510O1Dx8c4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Y+8lhrDqL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0BGLKLRNP
    a_tener_en_cuenta: Buen rendimiento por el precio; sin reposamuñecas ni software de control
    brand: Mars Gaming
    caracteristicas:
      - Diseño TKL compacto que ahorra espacio sin sacrificar funcionalidades esenciales.
      - Switches mecánicos OUTEMU que proporcionan una pulsación precisa y satisfactoria.
      - Iluminación RGB con 12 efectos dinámicos que mejoran la estética de tu setup.
      - Teclas de doble inyección que aseguran una mayor durabilidad y resistencia al desgaste.
      - Función anti-ghosting avanzada que permite pulsaciones simultáneas sin errores.
    descripcion: >-
      He utilizado el MK80 durante varios días y me ha parecido una opción muy sólida para quienes buscan buen
      rendimiento a bajo coste. Su tamaño TKL es ideal si necesitas más espacio para el ratón. Los switches ofrecen una
      pulsación mecánica firme, sin excesivo ruido. La iluminación RGB se puede ajustar fácilmente con combinaciones de
      teclas. En general, ofrece una experiencia mecánica bastante completa para su rango de precio.
    enlace: https://amzn.to/43654bC
    imagen: https://m.media-amazon.com/images/I/41kupb44JvL._SL500_.jpg
    lo_mejor: Switches OUTEMU marrones, iluminación RGB ajustable, tamaño TKL y construcción sólida
    nombre: Mars Gaming MK80
    valoracion: 4.5
    precio: "39,65\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41gkSaZLVjL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/519VTXnjCpL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51eu3-JX1DL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51tKtZmZ2XL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51iAzCSuYCL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 375
    imagenWidth: 500
  - ASIN: B0DHCNKM3C
    a_tener_en_cuenta: Ultracompacto, sin teclas F ni pad numérico; ideal para movilidad
    brand: Mars Gaming
    caracteristicas:
      - Formato ultra-compacto al 60% ideal para espacios reducidos y fácil transporte.
      - Switches mecánicos hot-swappable que permiten personalizar la experiencia de escritura.
      - Iluminación RGB completa con efectos en la parte trasera y lateral para un diseño envolvente.
      - Cable USB-C desmontable que facilita la conexión y organización del escritorio.
      - Teclas de doble inyección que ofrecen una mayor resistencia y tacto mejorado.
    descripcion: >-
      He probado el MKMINIPRO en un entorno de escritorio minimalista y también como teclado portátil. Su diseño 60%
      ayuda a liberar espacio y resulta cómodo de transportar. Los switches hot-swap permiten personalizar la
      experiencia sin herramientas. Pese a su tamaño, la construcción es muy sólida y estable. Su iluminación RGB
      dinámica es vibrante y configurable, ideal para setups llamativos.
    enlace: https://amzn.to/42VvpJi
    imagen: https://m.media-amazon.com/images/I/41eI9tQ13+L._SL500_.jpg
    lo_mejor: Formato 60%, switches hot-swap, RGB envolvente y cable USB-C extraíble
    nombre: Mars Gaming MKMINIPRO
    valoracion: 4
    precio: "29,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41zZY7GCiiL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51G8I3vsIUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41VXy1eKl+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41-31yGwhCL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41XQoy-HT0L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0F383W18C
    a_tener_en_cuenta: Una de las opciones más completas para gamers y profesionales exigentes
    brand: Mars Gaming
    caracteristicas:
      - Diseño completo con todas las teclas necesarias para una experiencia de escritura óptima.
      - Switches mecánicos hot-swap que permiten cambiar los interruptores sin soldadura.
      - Iluminación RGB CHROMA personalizable para adaptar el teclado a tu estilo.
      - Rueda de control multifunción que facilita el ajuste de volumen y otras funciones.
      - Software avanzado para la configuración de macros y personalización de teclas.
    descripcion: >-
      Tras varios días de uso intensivo con el MKPRO, puedo confirmar que es un teclado robusto y fiable. Los switches
      mecánicos ofrecen una pulsación precisa, ideal tanto para gaming como para tareas de escritura. La carcasa de
      aluminio transmite una gran sensación de calidad. Además, la retroiluminación RGB es completamente configurable y
      muy brillante. En mi experiencia, es una opción muy completa para quienes buscan un teclado profesional sin gastar
      una fortuna.
    enlace: https://amzn.to/4k3ywXj
    imagen: https://m.media-amazon.com/images/I/41fSYMkeoIL._SL500_.jpg
    lo_mejor: Switches hot-swap, RGB Chroma completo, chasis de aluminio y rueda de control multifunción
    nombre: Mars Gaming MKPRO
    valoracion: 5
    precio: "40,89\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41rFx5MEjSL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/415zS5GQufL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51BPF2QhV5L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41gRp5Are1L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41nKTeb6z5L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0972ZH4KN
    a_tener_en_cuenta: No tiene teclas dedicadas ni pad numérico; pensado para setups reducidos
    brand: Mars Gaming
    caracteristicas:
      - Diseño ultra-compacto al 60% para optimizar el espacio.
      - Switches mecánicos OUTEMU PRO de alta precisión.
      - Iluminación RGB personalizable con múltiples efectos.
      - Construcción robusta para una mayor durabilidad.
      - Ideal para setups minimalistas y portabilidad.
    descripcion: >-
      He estado utilizando el MKMINIBES durante mis sesiones de juego y trabajo, y su diseño ultra-compacto al 60% ha
      sido una ventaja para mantener un escritorio ordenado. Los switches mecánicos OUTEMU PRO ofrecen una respuesta
      precisa y una durabilidad notable. La iluminación RGB es vibrante y personalizable, lo que añade un toque estético
      a mi setup. Además, su construcción sólida transmite confianza en su uso diario.
    enlace: https://amzn.to/3Zeu3s3
    imagen: https://m.media-amazon.com/images/I/417bxE0cmDS._SL500_.jpg
    lo_mejor: Diseño 60% minimalista, switches OUTEMU PRO, retroiluminación RGB personalizable y gran portabilidad
    nombre: Mars Gaming MKMINIBES
    valoracion: 4
    precio: "43,08\_€"
    precioOriginal: "48,60\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51VQpud9GrS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Tnubsq3vS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51-NxxmnbpS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51gXQqZOSlS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41gXsAbH2HS._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0BDFGWCMX
    a_tener_en_cuenta: Estilo visual moderno y limpio; sin funciones multimedia dedicadas
    brand: Mars Gaming
    caracteristicas:
      - Formato ultra-compacto al 60% para máxima eficiencia.
      - Switches mecánicos para una respuesta táctil precisa.
      - Iluminación FRGB Rainbow con efectos dinámicos.
      - Diseño en blanco para un estilo elegante.
      - Construcción de alta calidad para uso prolongado.
    descripcion: >-
      El MK60 Rainbow White ha sido una grata sorpresa. Su formato ultra-compacto al 60% es perfecto para espacios
      reducidos sin sacrificar funcionalidad. Los switches mecánicos proporcionan una experiencia de escritura fluida y
      precisa. La iluminación FRGB Rainbow es intensa y añade un toque llamativo al escritorio. Su diseño en blanco le
      da un aspecto limpio y moderno.
    enlace: https://amzn.to/43u74Me
    imagen: https://m.media-amazon.com/images/I/41ur6yGMYyL._SL500_.jpg
    lo_mejor: Formato 60% blanco, switches mecánicos antipolvo, retroiluminación FRGB vibrante
    nombre: Mars Gaming MK60 Rainbow White
    valoracion: 4.5
    precio: "47,66\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51bwmnnjDHL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51spSwaxaIL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51fKnCvZrsL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51mguhl9jQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51dB5mslwML._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B09MJ7CGCL
    a_tener_en_cuenta: Ideal para usuarios que quieren estética clara sin perder funcionalidad
    brand: Mars Gaming
    caracteristicas:
      - Diseño full-compact al 96% para funcionalidad completa.
      - Switches OUTEMU SQ marrones para una pulsación suave.
      - Iluminación RGB personalizable con software dedicado.
      - Acabado en blanco para un estilo moderno.
      - Construcción sólida y duradera.
    descripcion: >-
      El MKULTRA Blanco ha sido una excelente adición a mi equipo. Su formato full-compact al 96% ofrece todas las
      teclas necesarias en un diseño más compacto. Los switches OUTEMU SQ marrones brindan una pulsación suave y
      silenciosa, ideal para largas sesiones de escritura o juego. La iluminación RGB es brillante y se puede
      personalizar fácilmente. Su acabado en blanco le da un toque sofisticado.
    enlace: https://amzn.to/4jTuEYt
    imagen: https://m.media-amazon.com/images/I/41Xm7WP8i0L._SL500_.jpg
    lo_mejor: Versión blanca con switches OUTEMU SQ, teclas PBT pudding y RGB Chroma con software
    nombre: Mars Gaming MKULTRA Blanco
    valoracion: 5
    precio: "74,78\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/514GVGtU1rL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518n-WoZLgL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ZsBSPpPUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51w1q7M3xML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41GXTWyepBL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B09SV594P2
    a_tener_en_cuenta: Conectividad inalámbrica muy cómoda; ideal para setups coloridos o portátiles
    brand: Mars Gaming
    caracteristicas:
      - Conectividad inalámbrica para mayor libertad de movimiento.
      - Formato compacto al 75% con todas las teclas esenciales.
      - Switches OUTEMU SQ PRO rojos para respuesta rápida.
      - Iluminación RGB personalizable y sincronizable.
      - Diseño en rosa para un estilo distintivo.
    descripcion: >-
      El MKCLOUDPRES destaca por su conectividad inalámbrica y diseño compacto al 75%. Los switches OUTEMU SQ PRO rojos
      ofrecen una respuesta rápida y lineal, ideal para juegos que requieren velocidad. La iluminación RGB es vibrante y
      se sincroniza bien con otros dispositivos. Su diseño en rosa añade un toque único y atractivo.
    enlace: https://amzn.to/4mi3g8c
    imagen: https://m.media-amazon.com/images/I/41ZPlO97CvL._SL500_.jpg
    lo_mejor: Formato 75% inalámbrico, switches OUTEMU SQ PRO, RGB y diseño rosa único
    nombre: Mars Gaming MKCLOUDPRES
    valoracion: 4.5
    precio: Sin precio
    precioOriginal: No especificado
    disponibilidad: Sin info
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51nDRSRqnsL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51rP++7+qDL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51TpddmXa9L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/512YMwFYkQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51lmZCaUACL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0F3839TXY
    a_tener_en_cuenta: Una opción premium con estética clara y funcionalidades completas
    brand: Mars Gaming
    caracteristicas:
      - Diseño completo con todas las teclas y funciones esenciales.
      - Switches mecánicos hot-swap para personalización.
      - Iluminación RGB Chroma totalmente configurable.
      - Acabado en blanco para un estilo sofisticado.
      - Construcción robusta y duradera para uso intensivo.
    descripcion: >-
      El MKPRO Blanco es una opción premium que combina estética y rendimiento. Su diseño completo ofrece todas las
      funcionalidades necesarias para profesionales y gamers. Los switches mecánicos hot-swap permiten personalizar la
      experiencia de escritura. La iluminación RGB Chroma es intensa y totalmente configurable. Su acabado en blanco le
      da un aspecto elegante y profesional.
    enlace: https://amzn.to/431xAfX
    imagen: https://m.media-amazon.com/images/I/31TrKlegrPL._SL500_.jpg
    lo_mejor: Diseño completo en blanco, switches hot-swap, RGB Chroma y rueda de control
    nombre: Mars Gaming MKPRO Blanco
    valoracion: 5
    precio: "41,89\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41xElGEWUjL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41wgpX2KaJL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41gIQsGsIqL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41aMndJaA+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31Cl54r27-L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
