productos:
  - ASIN: B07VL4V3J5
    a_tener_en_cuenta: 🎯 Sensor básico para gaming casual
    brand: Mars Gaming
    caracteristicas:
      - Inalámbrico con sensor óptico preciso
      - Hasta 3200 DPI ajustables para distintos juegos
      - Diseño ergonómico y peso muy ligero
      - Buena autonomía con batería recargable
      - 'Plug & Play: funciona al instante sin configuraciones'
    descripcion: >-
      He probado el Mars Gaming MMW durante una semana y me sorprendió su ligereza y libertad gracias a su conexión
      inalámbrica. Perfecto para gaming casual, edición o navegación. Tiene un diseño ergonómico que se adapta bien a la
      mano y sus botones ofrecen buena respuesta. Lo que más me gustó fue su facilidad de uso desde el primer momento,
      sin necesidad de software adicional. Además, es ideal para quien quiere un ratón fiable sin gastar mucho.
    enlace: https://amzn.to/4ke99Sg
    imagen: https://m.media-amazon.com/images/I/31rFwLYjiML._SL500_.jpg
    lo_mejor: 🔋 Inalámbrico con buena autonomía 🖱️ Peso muy ligero ⚡ Plug & Play sin software 🎮 DPI hasta 3200
    nombre: Mars Gaming MMW
    valoracion: 5
    precio: "18,08\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes: []
    imagenHeight: 303
    imagenWidth: 500
  - ASIN: B09TFJ3CFP
    a_tener_en_cuenta: 🔌 Cableado, aunque flexible
    brand: Mars Gaming
    caracteristicas:
      - Peso ultraligero de solo 55g, ideal para juegos rápidos
      - Sensor óptico de hasta 12800 DPI
      - Switches mecánicos HUANO de gran precisión
      - Diseño panal ventilado con iluminación RGB
      - Cable Paracord ultraflexible y sin fricción
    descripcion: >-
      He estado usando el MM55 Blanco durante varias sesiones de juego intenso y me ha sorprendido su agilidad. Con solo
      55 gramos, el ratón vuela sobre la alfombrilla y resulta especialmente cómodo para juegos FPS. Su diseño panal
      ayuda a mantener la mano fresca, y los switches HUANO tienen un clic firme y satisfactorio. Además, el cable
      Paracord casi parece inalámbrico de lo flexible que es. Un ratón ligero, veloz y con mucho estilo.
    enlace: https://amzn.to/4dokCfv
    imagen: https://m.media-amazon.com/images/I/41cYvlDPkTL._SL500_.jpg
    lo_mejor: 🪶 55g de peso 💨 Sensor 12800 DPI 🎛️ Switches HUANO 💡 RGB ventilado
    nombre: Mars Gaming MM55 Blanco
    valoracion: 4.5
    precio: "12,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41ObIpk2BXL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41z6qYNCi-L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41rt4ZEfHYL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51jd-L0ZBhL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/414RiXSJesL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31vbRuPx3lL._SL500_.jpg
        width: 340
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B08XZM2DF4
    a_tener_en_cuenta: 💸 Para jugadores exigentes
    brand: Mars Gaming
    caracteristicas:
      - Sensor PixArt 3389PRO con hasta 32000 DPI
      - Switches ópticos ultrarrápidos y duraderos
      - Diseño HIVE de 75g ligero pero resistente
      - Cable Feather Paracord sin tirones
      - RGB y software para ajustes personalizados
    descripcion: >-
      Probé el MMEX con shooters y RTS, y la experiencia fue excelente. Los switches ópticos responden al instante y se
      nota que están un paso por delante de los mecánicos convencionales. El sensor PixArt es extremadamente preciso
      incluso a altas velocidades. También me gustó el diseño HIVE, que lo hace ligero sin perder rigidez. Muy buena
      opción si buscas rendimiento puro y personalización.
    enlace: https://amzn.to/3YTw78R
    imagen: https://m.media-amazon.com/images/I/41phEY7X3AL._SL500_.jpg
    lo_mejor: 🎯 Sensor PixArt 3389PRO ⏱️ Switches ópticos 🪶 Diseño HIVE 🧠 Personalizable
    nombre: Mars Gaming MMEX
    valoracion: 5
    precio: "16,90\_€"
    precioOriginal: "22,90\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41SE2x4NQIL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41gQCvivcaL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41k3AhADawL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51NQlZVGwNL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41lomHn00AL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51bmZbjej7L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41F+uSVlD9L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0DN6C3D39
    a_tener_en_cuenta: 🎮 No apto para eSports
    brand: Mars Gaming
    caracteristicas:
      - Diseño vertical ergonómico para cuidar la postura
      - Conectividad inalámbrica 2.4GHz estable
      - Sensor óptico preciso de hasta 3200 DPI
      - Switches HUANO con buen tacto
      - Agarre natural y superficie Pro-Grip
    descripcion: >-
      Llevo varios días usando el ERGO VERTI en mi trabajo y la diferencia en la postura es notable. Su diseño vertical
      cambia completamente la manera en la que sujetas el ratón, aliviando la presión en la muñeca. Es inalámbrico y muy
      fácil de conectar. Me parece una alternativa fantástica para quien pasa horas frente al ordenador y busca evitar
      dolores o lesiones.
    enlace: https://amzn.to/3YTwkc9
    imagen: https://m.media-amazon.com/images/I/31oiIRfQS+L._SL500_.jpg
    lo_mejor: 🧍 Diseño vertical 🔋 Inalámbrico 2.4GHz 🖱️ Sensor 3200 DPI 🧲 Pro-Grip
    nombre: Mars Gaming ERGO VERTI
    valoracion: 4
    precio: "25,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41untTrlFQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41P1MOq8eoL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41wxtKwNNcL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41JxSi6zIML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31dJHdfn1PL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B09VPTPL76
    a_tener_en_cuenta: 🎮 No tiene software dedicado
    brand: Mars Gaming
    caracteristicas:
      - Diseño translúcido con RGB que llama la atención
      - Peso de 58g sin perforaciones visibles
      - Sensor de hasta 12800 DPI con buena respuesta
      - Switches HUANO duraderos
      - Cable Paracord flexible y resistente
    descripcion: >-
      Tuve la oportunidad de probar el MMR Translúcido en un entorno mixto de trabajo y gaming, y cumplió muy bien en
      ambos. El diseño translúcido con iluminación RGB es simplemente espectacular. A pesar de ser muy ligero, no se
      siente frágil. Su sensor responde con precisión, y el cable es tan suave que apenas se nota. Perfecto si quieres
      algo llamativo sin renunciar a la calidad.
    enlace: https://amzn.to/43oi4d2
    imagen: https://m.media-amazon.com/images/I/31t7Byl7ItL._SL500_.jpg
    lo_mejor: 💡 RGB translúcido 🪶 58g ⚡ Sensor 12800 DPI 🔌 Cable flexible
    nombre: Mars Gaming MMR Translúcido
    valoracion: 4
    precio: "12,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51f3D8GRsKL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41oHtpyV7XL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41en2HShsxL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41KE8Q9Fu+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41w79iMnDzL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B08PKXHLYD
    a_tener_en_cuenta: 🎯 Sensor básico para gaming casual
    brand: Mars Gaming
    caracteristicas:
      - Ergonómico y cómodo para largas sesiones
      - Sensor óptico de 3200 DPI ajustable
      - Conexión inalámbrica 2.4GHz estable y rápida
      - Switches mecánicos KAILH de buena calidad
      - Diseño antideslizante y multiplataforma
    descripcion: >-
      He estado alternando el MMWERGO en sesiones de trabajo y edición, y el confort es lo primero que notas. Su forma
      ergonómica encaja de forma natural en la mano y reduce el esfuerzo incluso tras horas de uso. La conexión
      inalámbrica funciona sin cortes y los switches Kailh tienen una respuesta excelente. Una opción equilibrada para
      quienes buscan ergonomía sin complicaciones.
    enlace: https://amzn.to/43llWLx
    imagen: https://m.media-amazon.com/images/I/31dMcW+Ef0L._SL500_.jpg
    lo_mejor: 🔋 Inalámbrico con buena autonomía 🖱️ Peso muy ligero ⚡ Plug & Play sin software 🎮 DPI hasta 3200
    nombre: Mars Gaming MMWERGO
    valoracion: 4.5
    precio: "9,90\_€"
    precioOriginal: "12,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/4195rfVrZEL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31i7ihXMJGL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31UgkJS+NGL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31fimcnJSsL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31+zOxlozgL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31TCFEIckyL._SL500_.jpg
        width: 411
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B098X1S8JQ
    a_tener_en_cuenta: ⚙️ Software básico
    brand: Mars Gaming
    caracteristicas:
      - Sensor óptico de alta precisión con hasta 10000 DPI
      - Iluminación RGB con efectos personalizables
      - Ergonomía pensada para largas sesiones de juego
      - Cable trenzado que no se enreda fácilmente
      - Compatible con software de configuración básica
    descripcion: >-
      El MMPRO es uno de los ratones Mars Gaming más completos que he probado. Ofrece un sensor preciso y una ergonomía
      ideal para sesiones largas. Además, la iluminación RGB le da un toque profesional y el cable trenzado evita
      enredos molestos. Lo estuve usando en shooters y juegos de estrategia, y la respuesta fue perfecta. El software de
      personalización es sencillo pero funcional, ideal para ajustar el ratón a tu gusto.
    enlace: https://amzn.to/4kgyyux
    imagen: https://m.media-amazon.com/images/I/31PKCSogveL._SL500_.jpg
    lo_mejor: 🎯 Sensor 10000 DPI 💡 RGB efectos 🧍 Muy cómodo 🔌 Cable trenzado
    nombre: Mars Gaming MMPRO
    valoracion: 5
    precio: "13,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41gTmB8UCxS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41eWLQfzeVS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/514qUx3nTmS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41J0xLJbQSS._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41jubomwvpL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0B2115VF7
    a_tener_en_cuenta: 🎯 Sensor básico para gaming casual
    brand: Mars Gaming
    caracteristicas:
      - Diseño ultraligero tipo panal con estética moderna
      - Conexión inalámbrica sin latencia apreciable
      - RGB personalizable con varios modos
      - Hasta 12800 DPI configurables desde software
      - Puerto USB-C para recarga rápida y práctica
    descripcion: >-
      Probé el MMW3 por su promesa de ligereza y la cumplió con creces. Ideal para FPS o MOBAs, su diseño perforado
      reduce el peso al máximo. Además, la batería tiene muy buena duración y se recarga fácilmente por USB-C. El agarre
      es cómodo y no se resbala incluso en partidas intensas. Me gustó especialmente su velocidad de respuesta, sin
      cortes ni retrasos.
    enlace: https://amzn.to/4m7YD0s
    imagen: https://m.media-amazon.com/images/I/41Y0HsJJKmL._SL500_.jpg
    lo_mejor: 🔋 Inalámbrico con buena autonomía 🖱️ Peso muy ligero ⚡ Plug & Play sin software 🎮 DPI hasta 3200
    nombre: Mars Gaming MMW3
    valoracion: 4
    precio: "12,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41MhMyEPYhL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/511OeTaOm1L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41n9TcdHlCL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41j9l8TppiL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41lQg06pDQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31D+RVif10L._SL500_.jpg
        width: 369
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B09PBRLWVC
    a_tener_en_cuenta: 🎮 Más estético que competitivo
    brand: Mars Gaming
    caracteristicas:
      - RGB 360º con efectos llamativos para setups gaming
      - Sensor óptico con buen rendimiento en juegos
      - Hasta 10000 DPI configurables
      - Diseño llamativo pero también funcional
      - Botones principales con clic definido y firme
    descripcion: >-
      El MMGLOW destaca por su espectacular iluminación RGB. Lo he usado en mi setup principal durante varios días y
      siempre llama la atención. A pesar de su precio asequible, tiene un sensor muy preciso y buenos materiales. Es
      ideal si buscas algo vistoso que también funcione bien. El clic es nítido y su construcción sólida lo hace parecer
      de gama más alta.
    enlace: https://amzn.to/434JYui
    imagen: https://m.media-amazon.com/images/I/31H8ocIEiUL._SL500_.jpg
    lo_mejor: 💡 RGB 360º 🎯 10000 DPI 🖱️ Clic firme ⚙️ Diseño llamativo
    nombre: Mars Gaming MMGLOW
    valoracion: 4
    precio: "17,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31BIDLIN5ML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31iXS19EMrL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31EAa+0+nSL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31vm1zWqLNL._SL500_.jpg
        width: 320
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0CTQMZZ9F
    a_tener_en_cuenta: 🎮 Mejor para productividad/MMO
    brand: Mars Gaming
    caracteristicas:
      - 9 botones totalmente programables para macros o accesos
      - Sensor óptico preciso con hasta 10000 DPI
      - Diseño profesional y acabado mate antideslizante
      - Ideal para juegos tipo MMO o productividad
      - Iluminación LED sutil configurable desde software
    descripcion: >-
      El MM-XT BLACK 9B me impresionó por su gran número de botones personalizables. Ideal para MMO, edición o
      productividad, puedes adaptar cada acción a tu estilo de juego. Su diseño negro mate también le da un toque serio
      y elegante. Lo estuve usando en edición de vídeo y juegos como WoW, y se agradecen los accesos rápidos. Su
      software permite asignar funciones fácilmente.
    enlace: https://amzn.to/437m813
    imagen: https://m.media-amazon.com/images/I/31LmBINshyL._SL500_.jpg
    lo_mejor: 🖱️ 9 botones 🎯 10000 DPI 🧍 Diseño cómodo 💡 LED configurable
    nombre: Mars Gaming MM-XT BLACK 9B
    valoracion: 4.5
    precio: "15,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41HFH3Hm30L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/417R-PnRAML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41p4cTMAKgL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51f33ng-fUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41bFjj0cGmL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
