productos:
  - ASIN: B088X3VSH4
    a_tener_en_cuenta: 3 a 6 años
    brand: ATAA
    caracteristicasAmazon:
      - 🏍️🏍️Moto eléctrica para niños oficial Aprilia
      - ⚙️⚙️Dos motores en ruedas tarseras
      - 💺💺Asiento en piel acolchado y ruedas goma EVA
      - 💡💡Música y luces. Reproductor mp3
      - 💎💎Una obra maestra por parte de Aprilia
    descripcion: >-
      La ATAA Aprilia Dorsoduro 12v Moto eléctrica Infantil tiene un estilo tan chulo que hasta los adultos se giran a
      mirarla. Tiene buena fuerza para caminos lisos y las ruedas de goma EVA aportan una gran estabilidad. Una
      experiencia muy divertida y segura para los peques.
    disponibilidad: En stock
    enlace: https://amzn.to/46BZO35
    imagen: https://m.media-amazon.com/images/I/418kofvR2AL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41aPETfjKbL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41FlVaJGK4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41sAI9DCuZL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31bKX1mRByL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/4129gGw+dnL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/410H0c8ZcoL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41QrQ-VjyrL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51UtaGIaj9L._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Ruedas EVA
      - Luces LED
    nombre: ATAA Aprilia Dorsoduro 12v Moto eléctrica Infantil
    precio: "176,54\_€"
    precioOriginal: "229,99\_€"
    valoracion: 4.3
  - ASIN: B085H35QJG
    a_tener_en_cuenta: 3 a 6 años
    brand: INJUSA
    caracteristicasAmazon:
      - >-
        🏍️ MOTO ELÉCTRICA INFANTIL – Para niños desde los 3 hasta los 6 años, ideal para desarrollar el equilibrio y la
        coordinación a la vez que aprenden a conducir su primera moto. Cuenta con licencia oficial de la marca Repsol.
      - >-
        🔋 BATERÍA RECARGABLE – Incluye batería de 12V y cargador para diversión prolongada. Alcanza hasta 6 km/h
        gracias a su puño acelerador, y dispone de freno eléctrico para que la moto se detenga cuando el niño deja de
        acelerar.
      - >-
        💡 EFECTOS REALISTAS – Con faros LED delanteros y traseros, entrada MP3 y MicroSD, sonidos y detalles que imitan
        a las motos reales de carreras.
      - >-
        🛞 RUEDAS ANCHAS Y ESTABILIDAD – Gracias a sus ruedas con bandas de goma que evitan los derrapes, y a sus ruedas
        de apoyo, proporciona seguridad y confort al conducir tanto en interiores como exteriores.
      - >-
        🇪🇸 FABRICADA EN ESPAÑA – Con materiales duraderos, cumpliendo normativa europea CE, la más exigente del mundo.
        Tiene una altura de asiento de 47 cm y una altura de manillar de 53 cm. Sus medidas son 114 x 53 x 62 cm.
    descripcion: >-
      La Moto Eléctrica Niños Repsol ha superado nuestras expectativas: potencia, diseño y diversión asegurada. Con su
      batería de buena duración, aguanta varios paseos sin tener que cargarla cada poco. En casa estamos todos
      encantados. Muy buena compra.
    disponibilidad: En stock
    enlace: https://amzn.to/4lr2Jzr
    imagen: https://m.media-amazon.com/images/I/41hyZ0vz2nL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41JKA+qevXL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41h5fxbEWfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/513vdkAk4xL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41HyAmF+FcL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Licencia oficial Repsol
      - Buena batería
    nombre: Moto Eléctrica Niños Repsol
    precio: "259,99\_€"
    precioOriginal: No especificado
    valoracion: 4.4
  - ASIN: B084VTCVYF
    a_tener_en_cuenta: 3 a 6 años
    brand: INJUSA
    caracteristicasAmazon:
      - >-
        🏍️ MOTO ELÉCTRICA INFANTIL – Para niños desde los 3 hasta los 6 años, ideal para desarrollar el equilibrio y la
        coordinación a la vez que aprenden a conducir su primera moto.
      - >-
        🔋 BATERÍA RECARGABLE – Incluye batería de 6V y cargador para diversión prolongada. Alcanza hasta 5-6 km/h
        gracias a su puño acelerador, y dispone de freno eléctrico para que la moto se detenga cuando el niño deja de
        acelerar.
      - >-
        💡DISEÑO OFICIAL DE CROSS – Con detalles que replican a las motos reales de cross, como los guardabarros, el
        motor o los cubremanetas.
      - >-
        🛞 RUEDAS DE APOYO Y ESTABILIDAD – Gracias a sus ruedas de apoyo, proporciona seguridad y confort al conducir
        tanto en interiores como exteriores.
      - >-
        🇪🇸 FABRICADA EN ESPAÑA – Con materiales duraderos, cumpliendo normativa europea CE. Tiene una altura de
        asiento de 53 cm y una altura de manillar de 73 cm. Sus medidas son 111 x 56 x 76 cm.
    descripcion: >-
      Montar en la Moto Eléctrica Niños Injusa Verde se ha convertido en el mejor plan de cada tarde. Los dos motores
      traseros se notan en la aceleración: va fluida y con respuesta rápida. Ideal para niños que ya quieren emociones
      un poco más fuertes, pero seguras.
    disponibilidad: En stock
    enlace: https://amzn.to/4l8L1Ai
    imagen: https://m.media-amazon.com/images/I/517xFsZdXmL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51dyaCNOQcL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ueYcrXAUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41e96DfJROL._SL500_.jpg
        width: 500
        height: 370
    lo_mejor:
      - Buena batería
      - Freno eléctrico
    nombre: Moto Eléctrica Niños Injusa Verde
    precio: "139,99\_€"
    precioOriginal: No especificado
    valoracion: 4.3
  - ASIN: B0CBQ174WS
    a_tener_en_cuenta: 3 a 6 años
    brand: INJUSA
    caracteristicasAmazon:
      - >-
        🏍️ MOTO ELÉCTRICA INFANTIL – Para niños desde los 3 hasta los 6 años, ideal para desarrollar el equilibrio y la
        coordinación a la vez que aprenden a conducir su primera moto.
      - >-
        🔋 BATERÍA RECARGABLE – Incluye batería de 12V y cargador para diversión prolongada. Alcanza hasta 5-6 km/h
        gracias a su puño acelerador, y dispone de freno eléctrico para que la moto se detenga cuando el niño deja de
        acelerar.
      - >-
        💡DISEÑO OFICIAL DE CROSS – Con detalles que replican a las motos reales de cross, como los guardabarros, el
        motor o los cubremanetas.
      - >-
        🛞 RUEDAS DE APOYO Y ESTABILIDAD – Gracias a sus ruedas de apoyo, proporciona seguridad y confort al conducir
        tanto en interiores como exteriores.
      - >-
        🇪🇸 FABRICADA EN ESPAÑA – Con materiales duraderos, cumpliendo normativa europea CE. Tiene una altura de
        asiento de 53 cm y una altura de manillar de 73 cm. Sus medidas son 115 x 52 x 82 cm.
    descripcion: >-
      Montar en la Moto Eléctrica Niños Injusa Thunder Max se ha convertido en el mejor plan de cada tarde. El diseño
      deportivo le da un aspecto muy realista, y el asiento es realmente cómodo. Después de esta experiencia, ya está
      pidiendo una carrera con su primo.
    disponibilidad: En stock
    enlace: https://amzn.to/3J0sc4Z
    imagen: https://m.media-amazon.com/images/I/41brSc7obvL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51-u+ZnB89L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ODGG2SbAL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51cDLAZ5jTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41EHOIPvwQL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31u+fYLprxL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41066YbfPAL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41kGEiFkN4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41mvlgoXTeL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/519wcxcBZXL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Buena batería
      - Réplica motocross
    nombre: Moto Eléctrica Niños Injusa Thunder Max
    precio: "139,00\_€"
    precioOriginal: No especificado
    valoracion: 4.3
  - ASIN: B0B1JGL7Q3
    a_tener_en_cuenta: 3 a 6 años
    brand: Babycar
    caracteristicasAmazon:
      - >-
        🏍️Honda CBR 1000 - Moto niño 3 años hasta 6 años con batería de 12V 3.5AH y 1 motor de 30W. Muy sencilla y
        súper rápida de montar
      - >-
        📱Design - Esta mini moto presenta un diseño realista que copia a la perfección y al detalle la Honda original.
        Disponible tanto en blanco como en rojo, esta moto también tiene ruedas para añadir según las necesidades de tu
        pequeño piloto
      - >-
        🛠️Información técnica - moto bateria niño con carga inicial de 10 horas la primera vez. Mide 87,5 X 42,8 X 51,5
        cm y soporta un peso de hasta 30 kg; con luces LED, entradas USB, Mp3 y sistema de arranque suave para evitar
        arranques peligrosos
      - >-
        🏁Puedes montar en cualquier sitio: nuestra moto infantiles puede circular por cualquier terreno, tanto en
        interiores como en exteriores, sobre grava, arena, tierra y hierba.
      - >-
        💯 ¿Por qué elegir BabyCar - concesionario de motos electricas infantiles entre los más grandes de Europa; marca
        joven y dinámica de conducción realista con atención a la seguridad y servicio de asistencia al cliente siempre
        disponible
    descripcion: >-
      La Moto eléctrica Infantil Honda CBR tiene un estilo tan chulo que hasta los adultos se giran a mirarla. El diseño
      deportivo le da un aspecto muy realista, y el asiento es realmente cómodo. La recomendamos 100%, sobre todo si
      buscas una moto con buena presencia.
    disponibilidad: En stock
    enlace: https://amzn.to/41jrNkp
    imagen: https://m.media-amazon.com/images/I/51EynsEyMjL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41rE9RAnBgL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51FsTeTfrvL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Cl9krPtbL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51FJQeW2R2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51ymqDus5-L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518H8LwNomL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51I46SFpzKL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41w9J4ea9+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51FWtchxPiL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Buena batería
      - Luces LED
    nombre: Moto eléctrica Infantil Honda CBR
    precio: "188,90\_€"
    precioOriginal: No especificado
    valoracion: 4.3
