productos:
  - ASIN: B072JCB6MF
    a_tener_en_cuenta: 3 a 5 años
    brand: Famosa
    caracteristicasAmazon:
      - >-
        La Motorbike Cross 400F es una moto eléctrica que incluye luces en los faros delanteros, sonidos de motor y
        claxon, y dos ruedines para mejorar la estabilidad, brindando una experiencia de conducción realista y segura.
      - >-
        Equipada con un pulsador para acelerar y frenar, esta moto alcanza una velocidad de hasta 3 km/h, ofreciendo un
        control sencillo y seguro para los más pequeños.
      - >-
        Diseñada para niños y niñas de 3 a 5 años, la Motorbike Cross 400F soporta un peso máximo de 25 kg, haciendo que
        sea ideal para los primeros años de conducción.
      - >-
        La moto incluye una batería de 6V y un cargador, proporcionando hasta 40 minutos de juego continuo. Perfecta
        para que los niños disfruten de largos paseos sin interrupciones.
      - >-
        Con unas medidas de 102 cm de largo, 53 cm de ancho y 66 cm de altura, y un peso de 11,2 kg, esta moto eléctrica
        es lo suficientemente compacta para manejarla y almacenarla fácilmente, sin sacrificar la diversión.
    descripcion: >-
      Esta semana estuvimos con la Motorbike Cross 400F FEBER y les encantó desde el primer momento. El montaje fue más
      sencillo de lo que pensaba y en seguida pudimos estrenarla. Muy recomendable si buscas una moto eléctrica segura y
      entretenida.
    disponibilidad: En stock
    enlace: https://amzn.to/3GRNuRR
    imagen: https://m.media-amazon.com/images/I/31PnVU0ZUXL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/312W1r3buNL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31VPOb-AsGL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Buena batería
      - Luces LED
    nombre: Motorbike Cross 400F FEBER
    precio: "107,95\_€"
    precioOriginal: No especificado
    valoracion: 4.3
  - ASIN: B0BDFCMVCX
    a_tener_en_cuenta: 3 a 5 años
    brand: HOMCOM
    caracteristicasAmazon:
      - >-
        CON LICENCIA DE HONDA: Esta motocicleta eléctrica para niños con licencia de Honda es la elección perfecta para
        cualquier niño. Con una bonita combinación de colores y un aspecto realista, los más pequeños se sentirán como
        auténticos pilotos
      - >-
        FÁCIL DE CONTROLAR: La dirección simple le da a tu hijo una sensación de control mientras aprende a conducir. La
        batería recargable de 6 V ofrece energía suficiente para que los más pequeños puedan disfrutar de un viaje
        seguro y emocionante de hasta 45 minutos después de una carga completa
      - >-
        EXPERIENCIA AUTÉNTICA: Solo hace falta pisar el pedal eléctrico para comenzar la aventura en esta bonita moto
        eléctrica infantil. Con faros realistas y sonidos de motor y música para que tus hijos disfruten de una
        auténtica experiencia de conducción
      - >-
        MÁXIMA SEGURIDAD: Los niños pueden ir en esta motocicleta con total seguridad gracias a su velocidad de hasta 3
        km/h, que es un poco más lenta que la del paseo medio para que puedas seguir el paso de tu hijo en todo momento.
        Tiene dos ruedas anchas de plástico texturizado que aseguran un movimiento suave y ruedas laterales pequeñas
        para un mayor equilibrio
      - >-
        MEDIDAS TOTALES: 90x44x52 cm (LxANxAL). Medidas del asiento: 16,5x14x37 cm (LxANxAL). Peso máximo soportado: 30
        kg. Certificaciones: EN 71-1-2-3, EN 62115. Apto para niños de 3-5 años. Requiere montaje
    descripcion: >-
      Probamos la HOMCOM Moto Eléctrica con Licencia Honda tanto en casa como al aire libre y el resultado fue genial.
      Es muy fácil de manejar, y el sonido del motor le da un toque muy auténtico. Perfecta para esos primeros paseos en
      moto con total seguridad.
    disponibilidad: En stock
    enlace: https://amzn.to/45gwMnd
    imagen: https://m.media-amazon.com/images/I/512jLqANBRL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/514NlPTy7aL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/61kXcpsJDkL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/510aKCYlIoL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518nZxen6AL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51p1Lqxz9RL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51z9WAbaYkL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51WNqUb2HYL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51+4SOQ77vL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Licencia oficial Honda
      - Buena batería
    nombre: HOMCOM Moto Eléctrica con Licencia Honda
    precio: "109,99\_€"
    precioOriginal: "133,99\_€"
    valoracion: 4.4
  - ASIN: B0DBCGXFH9
    a_tener_en_cuenta: A partir de 3 años
    brand: AIYAPLAY
    caracteristicasAmazon:
      - >-
        MOTO ELÉCTRICA PARA NIÑOS CON LICENCIA DE HONDA: Este modelo de moto de batería para niños cuenta con la
        licencia oficial de Honda, ofreciendo una experiencia de conducción que emula la emoción y la adrenalina de las
        carreras de motos reales. Es el vehículo perfecto para los pequeños aventureros a partir de 3 años
      - >-
        MÚLTIPLES FUNCIONALIDADES: Esta motocicleta de batería para niños arranca con un solo botón y ofrece múltiples
        opciones musicales, faros funcionales y programas de educación inicial. Estas características enriquecen la
        diversión y proporcionan valiosas oportunidades de aprendizaje, favoreciendo el desarrollo cognitivo y de
        habilidades motoras
      - >-
        ESTABILIDAD ASEGURADA: Equipada con dos ruedas auxiliares, esta moto eléctrica para niños garantiza un manejo
        estable y seguro en variadas superficies como asfalto, ladrillo o cemento
      - >-
        VELOCIDAD DE SEGURIDAD: Con una velocidad máxima de 3 km/h y equipada con motores duales, esta moto para niños
        asegura una conducción divertida y segura
      - >-
        MEDIDAS TOTALES: 107x46x75 cm (LxANxAL). Peso máximo soportado: 30 kg. Edad recomendada: a partir de 3 años.
        Cumple con: EN71-1-2-3, EN62115. Se requiere montaje
    descripcion: >-
      Probamos la AIYAPLAY Moto Eléctrica para Niños tanto en casa como al aire libre y el resultado fue genial. Nos
      sorprendió lo estable que es, incluso cuando toma las curvas con entusiasmo. Una opción ideal para los más
      pequeños que empiezan a explorar sobre ruedas.
    disponibilidad: En stock
    enlace: https://amzn.to/45aV9T9
    imagen: https://m.media-amazon.com/images/I/41aBHsHJl4L._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51V7YzXUPaL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51fwNV81yzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51TNSpWJy3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/516z1NoKNZL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51RR+EShu0L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51it2KkZxTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41S-PN6gC8L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51gaXbU1AXL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Licencia oficial Honda
      - Buena batería
    nombre: AIYAPLAY Moto Eléctrica para Niños
    precio: "159,99\_€"
    precioOriginal: No especificado
    valoracion: 4.4
  - ASIN: B09C1NXQGF
    a_tener_en_cuenta: A partir de 3 años
    brand: HOMCOM
    caracteristicasAmazon:
      - >-
        MOTO ELÉCTRICA CON 3 RUEDAS: Ideal para que los niños disfruten de una moto eléctrica sin preocuparse por tener
        que balancear su peso para equilibrar la moto. Como tiene 3 ruedas grandes y un amplio asiento resulta muy fácil
        de conducir
      - >-
        VELOCIDAD LIMITADA: Esta moto infantil arranca a baja velocidad, permitiendo que los pequeños puedan responder
        oportunamente a situaciones inesperadas. Con una velocidad máxima limitada de 3 km por hora, este coche para
        niños permite que su hijo se divierta y esté seguro. Además, se controla fácilmente mediante su pedal acelerador
      - >-
        AUTONOMÍA: Después de una carga completa (8-12 h habitualmente), esta moto para niños a batería tiene una
        autonomía de unos 45 minutos aproximadamente (según el tipo de uso)
      - >-
        LUCES Y SONIDOS: Los faros de esta moto de batería se encienden de verdad y además incluye música que se activa
        mediante un botón. Los peques se lo pasarán genial mientras promueven habilidades como la coordinación, la
        orientación y su autoconfianza a una edad temprana. Les encantará sentirse como auténticos conductores como sus
        padres
      - >-
        MEDIDAS TOTALES: 86x42x52 cm (LxANxAL). Peso máximo soportado: 25 kg. Recomendado para niños a partir de 3 años.
        Utilizar bajo la supervisión de un adulto
    descripcion: >-
      Esta semana estuvimos con la HOMCOM Moto Eléctrica Infantil con 3 Ruedas y les encantó desde el primer momento.
      Aunque al principio iba con cuidado, en minutos ya se sentía como un piloto profesional. Perfecta para esos
      primeros paseos en moto con total seguridad.
    disponibilidad: En stock
    enlace: https://amzn.to/4lXlP16
    imagen: https://m.media-amazon.com/images/I/41GJJBZZDXL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51QG1kTGczL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518gIkuOq3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Hy111T1aL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51BaoUXEfbL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Ta5h1uZFL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51PI+nlxw3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/514r3mhPexL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51yGYS9GAeL._SL500_.jpg
        width: 500
        height: 500
    lo_mejor:
      - Autonomía destacada
      - Luces y sonidos
    nombre: HOMCOM Moto Eléctrica Infantil con 3 Ruedas
    precio: "68,99\_€"
    precioOriginal: "74,99\_€"
    valoracion: 4.3
