productos:
- a_tener_en_cuenta: No tiene GPS ni NFC, y para algunas funciones necesitas la app
    Mi Fitness.
  brand: Xiaomi
  caracteristicas:
  - Pantalla AMOLED 1,62″, 60 Hz y hasta 1200 nits
  - 'Seguimiento: pulso, SpO₂, estrés, sueño y ciclo'
  - Más de 150 modos deportivos
  - Resistencia al agua 5 ATM
  - Autonomía de hasta 21 días
  descripcion: Probé la Xiaomi Smart Band 9 y me sorprendió lo ligera y completa que
    es. La pantalla AMOLED de 1,62″ se ve genial incluso bajo el sol, y todo fluye
    con su tasa de 60 Hz. Tiene seguimiento continuo de salud (pulso, SpO₂, estrés,
    sueño), más de 150 modos deportivos y una batería que me duró casi tres semanas.
    Ideal si buscas una pulsera potente, cómoda y sin complicaciones.
  enlace: https://amzn.to/4jVdXeD
  imagen: 'images/Xiaomi-Smart-Band-9.webp'
  lo_mejor: Pantalla muy brillante y fluida, gran autonomía y funciones completas
    de salud en un diseño súper ligero.
  nombre: Xiaomi Smart Band 9
  valoracion: 4.4
- a_tener_en_cuenta: No tiene pantalla AMOLED ni GPS; algunos datos de salud no son
    tan precisos como en gamas más altas.
  brand: Xiaomi
  caracteristicas:
  - Pantalla TFT de 1,47″, 60 Hz
  - 'Muy ligera: solo 16,2 g'
  - Seguimiento de pulso, SpO₂ y sueño
  - Más de 50 modos deportivos
  - Hasta 18 días de autonomía
  descripcion: Esta versión Active de la Smart Band 9 me ha parecido ideal si buscas
    una pulsera económica pero muy completa. Tiene una pantalla TFT de 1,47″ que se
    ve nítida, es muy ligera (solo 16,2 g) y la batería me ha aguantado unos 2 días
    con uso intenso, o más de 2 semanas en uso normal. Mantiene funciones clave como
    el seguimiento de sueño, pulso y SpO₂, y su diseño cómodo la hace perfecta para
    llevarla todo el día sin darte cuenta.
  enlace: https://amzn.to/3SXn8QJ
  imagen: 'images/Xiaomi-Smart-Band-9-Active.webp'
  lo_mejor: Comodísima para uso diario, con buena autonomía y funciones básicas de
    salud que cumplen bien.
  nombre: Xiaomi Smart Band 9 Active
  valoracion: 4.3
- a_tener_en_cuenta: No tiene GPS ni funciones deportivas avanzadas; algunas funciones
    requieren Fitbit Premium.
  brand: Google
  caracteristicas:
  - Pantalla AMOLED táctil a color
  - Seguimiento continuo del estrés, sueño y FC
  - Diseño fino y muy cómodo
  - Hasta 10 días de autonomía
  - Compatible con app Fitbit + Google Fit
  descripcion: 'La Inspire 3 me ha parecido una pulsera sencilla pero con datos de
    salud bastante precisos. Tiene un diseño fino y muy ligero, y lo que más me gustó
    fue su enfoque en el bienestar: estrés, sueño, frecuencia cardíaca y niveles de
    actividad. La batería me duró fácilmente más de una semana, y su pantalla AMOLED
    pequeña pero nítida permite ver lo esencial sin distracciones.'
  enlace: https://amzn.to/3HMEnlj
  imagen: 'images/Fitbit-Inspire-3.webp'
  lo_mejor: Buena precisión en los datos de salud y excelente para quienes priorizan
    el bienestar y el descanso.
  nombre: Google Fitbit Inspire 3
  valoracion: 4.2
- a_tener_en_cuenta: No incluye GPS; algunas funciones requieren app Mi Fitness.
  brand: Xiaomi
  caracteristicas:
  - Pantalla AMOLED 1,62″ con 600 nits
  - Modos deportivos con análisis profesional
  - Sensor de pulso, SpO₂, estrés y sueño
  - 'Diseño adaptable: muñeca o zapatilla'
  - Hasta 16 días de batería
  descripcion: 'La Mi Smart Band 8 me ha sorprendido por su versatilidad. No solo
    puedes llevarla en la muñeca, también incluye accesorios para usarla como clip
    en la zapatilla y registrar carrera de forma más precisa. La pantalla AMOLED de
    1,62″ es muy brillante, y tiene sensores de salud completos. Lo mejor: la autonomía
    ronda las dos semanas incluso con notificaciones activas.'
  enlace: https://amzn.to/3HI6SRg
  imagen: 'images/Xiaomi-Smart-Band-8.webp'
  lo_mejor: Versátil y precisa, ideal si corres o haces deporte y te gusta monitorizar
    el rendimiento.
  nombre: Xiaomi Smart Band 8
  valoracion: 4.4
- a_tener_en_cuenta: Sin GPS; algunas funciones avanzadas requieren app Huawei Health.
  brand: Huawei
  caracteristicas:
  - Pantalla AMOLED de 1,47″ sin bordes
  - Seguimiento de SpO₂, pulso, sueño y estrés
  - Carga rápida (100% en 45 min)
  - Resistencia al agua 5 ATM
  - Hasta 14 días de batería
  descripcion: 'La HUAWEI Band 8 tiene un diseño que parece de gama alta: delgada,
    ligera y con pantalla AMOLED de gran calidad. Me gustó su precisión al medir sueño,
    frecuencia cardíaca y saturación de oxígeno. Incluye funciones interesantes como
    ejercicios de respiración, y la autonomía supera los 10 días sin despeinarse.'
  enlace: https://amzn.to/40az45s
  imagen: 'images/Huawei-band-8.webp'
  lo_mejor: Elegante y muy completa. La mejor opción si quieres estilo sin renunciar
    a sensores fiables.
  nombre: HUAWEI Band 8
  valoracion: 4.6
- a_tener_en_cuenta: No tiene GPS ni NFC, y requiere app de Huawei para estadísticas
    detalladas.
  brand: Huawei
  caracteristicas:
  - Pantalla AMOLED de 1,52″
  - Más de 100 modos deportivos
  - Sensor TruSeen 5.5 para FC y SpO₂
  - Carga rápida en 45 minutos
  - Autonomía de hasta 14 días
  descripcion: 'Probé la Band 10 y lo primero que destaca es su diseño rectangular
    ultrafino y pantalla AMOLED clara incluso en exteriores. Tiene más de 100 modos
    deportivos, medición de estrés, sueño y salud cardíaca bastante precisa. Y lo
    mejor: se carga al 100 % en solo 45 minutos.'
  enlace: https://amzn.to/45nH4nj
  imagen: 'images/HUAWEI-Band-10.webp'
  lo_mejor: Diseño moderno, datos de salud precisos y batería muy duradera. Se siente
    como un smartwatch.
  nombre: HUAWEI Band 10
  valoracion: 4.6
- a_tener_en_cuenta: No tiene GPS ni NFC; requiere Samsung Health para seguimiento
    completo.
  brand: Samsung
  caracteristicas:
  - Pantalla AMOLED de 1,6″
  - Más de 100 modos de entrenamiento
  - Seguimiento de sueño, pulso y estrés
  - Control de notificaciones y llamadas
  - Hasta 13 días de autonomía
  descripcion: La Galaxy Fit3 es una de las pulseras más completas que he probado.
    Su pantalla AMOLED de 1,6″ es amplia y muy cómoda de usar. Incluye sensores de
    salud (pulso, estrés, sueño), más de 100 modos de ejercicio y una batería que
    aguanta hasta 13 días. Además, permite controlar llamadas y notificaciones fácilmente
    desde la muñeca.
  enlace: https://amzn.to/3Tr4WPz
  imagen: 'images/galaxy-fit3.webp'
  lo_mejor: Pantalla grande y fluida, funciones de smartwatch y excelente batería
    para uso diario.
  nombre: Samsung Galaxy Fit3
  valoracion: 4.4
