productos:
  - nombre: Kit Ring Alarm S
    brand: Ring
    imagen: images/kit-ring-alarm-s.webp
    valoracion: 5
    descripcion: >
      Ideal para pisos pequeños o viviendas de 1 dormitorio. Este kit básico incluye lo necesario para empezar: estación base, teclado, sensor de movimiento y sensor de contacto. Es perfecto si quieres probar Ring Alarm sin gastar de más.
    caracteristicas:
      - Para pisos de hasta 1 dormitorio
      - Cubre 1 puerta o ventana
      - Incluye sensor de movimiento para una estancia
      - Instalación sencilla sin obras
      - Compatible con Alexa y app móvil gratuita
    enlace: https://amzn.to/43W7Q51
    lo_mejor: "👍 Ideal para iniciarse con Ring, 📦 Compacto y funcional"
    a_tener_en_cuenta: "🚪 Cubre solo 1 acceso, 🔊 Sirena exterior no incluida"
  - nombre: Kit Ring Alarm M
    brand: Ring
    imagen: images/kit-ring-alarm-m.webp
    valoracion: 5
    descripcion: >
      El equilibrio ideal entre protección y precio. Este kit está diseñado para hogares medianos, con sensores suficientes para 2 puertas o ventanas y 2 sensores de movimiento. Apto para la mayoría de pisos y casas pequeñas.
    caracteristicas:
      - Recomendado para 2 dormitorios
      - Cubre 2 accesos (puertas o ventanas)
      - Detección de movimiento en 2 estancias
      - Fácilmente ampliable
      - Compatible con Alexa
    enlace: https://amzn.to/44lqHFF
    lo_mejor: "⚖️ Buen equilibrio entre precio y cobertura"
    a_tener_en_cuenta: "📦 No incluye sirena exterior por defecto"
  - nombre: Kit Ring Alarm L
    brand: Ring
    imagen: images/kit-ring-alarm-L.webp
    valoracion: 5
    descripcion: >
      Este pack está pensado para viviendas más grandes o familias. Con sensores para 4 accesos y 3 zonas de movimiento, cubre muy bien casas de 2 o 3 dormitorios. Es la mejor opción si buscas una instalación duradera.
    caracteristicas:
      - Cubre 4 puertas o ventanas
      - 3 sensores de movimiento incluidos
      - Ampliable con accesorios Ring
      - Control por app o voz (Alexa)
      - Sirena exterior opcional
    enlace: https://amzn.to/4kPozNi
    lo_mejor: "🏡 Ideal para casas medianas, 🔧 Muy personalizable"
    a_tener_en_cuenta: "🔊 Sirena exterior no incluida"
  - nombre: Kit Ring Alarm XL
    brand: Ring
    imagen: images/kit-ring-alarm-xl.webp
    valoracion: 5
    descripcion: >
      El kit más completo de Ring Alarm. Perfecto para casas grandes, chalets o viviendas con varios accesos. Incluye sensores suficientes y la sirena exterior de serie. Es la opción más profesional sin depender de empresas de seguridad.
    caracteristicas:
      - Para casas de más de 3 dormitorios
      - Cubre 6 accesos
      - Incluye 3 sensores de movimiento
      - Incluye sirena de exterior
      - Instalación sencilla, todo en un solo pack
    enlace: https://amzn.to/4kV8TYV
    lo_mejor: "💪 Protección total, 🚫 Sin cuotas ni contratos"
    a_tener_en_cuenta: "🏗️ Volumen de sensores elevado, requiere tiempo para instalar"
