productos:
  - ASIN: B0F2L6JTH9
    nombre: Vestido profesional de Flamenca de Lunares
    brand: Genérico
    enlace: https://amzn.to/40G8YYu
    valoracion: 5
    descripcion: >-
      Vestido de flamenca rojo con lunares negros, confeccionado en poliéster y elastano. Ajuste cómodo y favorecedor,
      ideal para ferias y espectáculos. El tejido conserva el color y la forma incluso al estirarse.
    lo_mejor: Diseño clásico muy favorecedor y tejido resistente
    a_tener_en_cuenta: Solo disponible en tallas S y M
    caracteristicas:
      - 95% poliéster y 5% elastano
      - Estampado de lunares duradero
      - Ajuste perfecto al cuerpo
      - Corte tradicional de flamenca
      - No destiñe ni se deforma al estirar
    precio: "75,00\_€"
    precioOriginal: No especificado
    disponibilidad: Envío en 4 a 5 días
    imagen: https://m.media-amazon.com/images/I/51R3DAdCS2L._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 249
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51AcTQvPFVL._SL500_.jpg
        width: 241
        height: 500
      - url: https://m.media-amazon.com/images/I/51fw1rEs9eL._SL500_.jpg
        width: 306
        height: 500
      - url: https://m.media-amazon.com/images/I/51SEhxtin2L._SL500_.jpg
        width: 241
        height: 500
      - url: https://m.media-amazon.com/images/I/51KVo-cViAL._SL500_.jpg
        width: 375
        height: 500
    caracteristicasAmazon:
      - Diseño color rojo con lunares negros
  - ASIN: B0F5BWR1DM
    nombre: Vestido Flamenco Mujer con Volantes
    brand: AMARU SANCHESU
    enlace: https://amzn.to/46vrh6l
    valoracion: 4.7
    descripcion: >-
      Vestido entallado con escote cuadrado, mangas 3/4 de encaje y cuatro volantes en la falda. El tejido elástico se
      adapta bien al cuerpo, ideal para bailarinas o eventos temáticos.
    lo_mejor: Estiliza mucho y es cómodo para bailar
    a_tener_en_cuenta: Es largo hasta el tobillo, puede no ser apto para niñas o personas bajas
    caracteristicas:
      - Tejido flexible de alta calidad
      - Escote cuadrado con mangas transparentes
      - Falda con volantes escalonados
      - Estampado floral y liso combinado
      - Ideal para ferias, espectáculos o romerías
    precio: "49,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41hLyzE8AFL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 344
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31gBrUrCK1L._SL500_.jpg
        width: 337
        height: 500
      - url: https://m.media-amazon.com/images/I/310LVwrjPsL._SL500_.jpg
        width: 394
        height: 500
      - url: https://m.media-amazon.com/images/I/315cE+X4qLL._SL500_.jpg
        width: 500
        height: 258
    caracteristicasAmazon:
      - Diseño entallado con volantes que realzan la silueta y aportan movimiento elegante.
  - ASIN: B08BDDT63M
    nombre: Traje Profesional 2 Piezas Lunares Gojoy Shop
    brand: Gojoy shop
    enlace: https://amzn.to/41a4Yj2
    valoracion: 4.5
    descripcion: >-
      Conjunto de body con mangas de volante y falda de lunares. Pensado para bailar sevillanas o flamenco. Disponible
      en múltiples colores y tallas. Muy cómodo y fácil de poner.
    lo_mejor: Incluye todo lo necesario para bailar y tiene muy buen ajuste
    a_tener_en_cuenta: No incluye complementos como flor ni peineta
    caracteristicas:
      - Body de manga con doble volante
      - Falda de lunares con volante ancho
      - Tejido elástico y adaptable
      - Se puede lavar a mano o máquina
      - Disponible en 6 colores
    precio: "39,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/413wpjhVUgL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 393
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/413NzkVr2sL._SL500_.jpg
        width: 500
        height: 459
      - url: https://m.media-amazon.com/images/I/41L6TarE+yL._SL500_.jpg
        width: 500
        height: 474
      - url: https://m.media-amazon.com/images/I/41lyptlmsAL._SL500_.jpg
        width: 492
        height: 500
      - url: https://m.media-amazon.com/images/I/41Ns1a6bFFL._SL500_.jpg
        width: 369
        height: 500
      - url: https://m.media-amazon.com/images/I/413wpjhVUgL._SL500_.jpg
        width: 393
        height: 500
    caracteristicasAmazon:
      - >-
        Nuestra tienda en Amazon: Gojoy Shop, tenemos varios modelos de disfraces vestidos de baile para adultos y
        niños. Este Traje de Body con Doble Volantes en Manga y Falda de Lunares con Un Volante en 6 Colores
        Disponibles. Ideal para Baile Danza Flamenco o Sevillanas para Mujer.
      - Tejido de alta calidad y elástico.
      - '<br> Fácil de usar: nuestras prendas están hechas de tejido elástico para un uso fácil de vestirse o quitarse.'
      - Este artículo cumple las normas vigentes de la C.E..
      - Contiene Body con Doble Volantes en Manga y Falda de Lunares con Un Volante en 6 Colores Disponibles.
  - ASIN: B0829SK8LN
    nombre: Vestido Flamenco Rojo Lunares Negro (Infantil)
    brand: Flamifeel
    enlace: https://amzn.to/4o9Hswp
    valoracion: 4.6
    descripcion: >-
      Vestido flamenco infantil rojo con lunares, mangas con volantes y escote en V. Parte superior elástica para mayor
      comodidad. Ideal para niñas en ferias o espectáculos.
    lo_mejor: Ligero, cómodo y muy bonito para niñas
    a_tener_en_cuenta: No incluye complementos
    caracteristicas:
      - Parte superior elástica
      - Mangas con dos volantes
      - Tres volantes decorados con raso
      - Escote en V
      - Disponible en varias tallas infantiles
    precio: "35,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41za+f2JwiL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 322
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41ALx8feomL._SL500_.jpg
        width: 434
        height: 500
      - url: https://m.media-amazon.com/images/I/41HQJer5WBL._SL500_.jpg
        width: 434
        height: 500
      - url: https://m.media-amazon.com/images/I/31lXhncsJTL._SL500_.jpg
        width: 500
        height: 424
    caracteristicasAmazon:
      - Vestido de mujer para niños de Sevillana
      - Mango con dos volantes
      - El fondo en 3 volantes decorados con una tira de raso
      - La parte superior del vestido es elástica para adaptarse mejor al cuerpo
      - Escote en V
  - ASIN: B0CKM95RTP
    nombre: Vestido Flamenca con Flor (Infantil)
    brand: ReliBeauty
    enlace: https://amzn.to/4fenahp
    valoracion: 4.6
    descripcion: >-
      Traje de flamenca para niña con tocado de flor incluido. Diseño clásico rojo y negro. Material suave y resistente,
      perfecto para disfraces, ferias o actuaciones escolares.
    lo_mejor: Incluye flor a juego y tiene muy buena calidad para el precio
    a_tener_en_cuenta: Las tallas pueden venir algo justas, conviene revisar medidas
    caracteristicas:
      - Incluye flor de tocado a juego
      - Tejido cómodo y suave
      - Estilo clásico con lunares
      - Ideal para fiestas y cosplay
      - Buen ajuste para niñas de 3 a 12 años
    precio: "33,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41tpY1vI4UL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 398
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41KXo5RGY8L._SL500_.jpg
        width: 398
        height: 500
      - url: https://m.media-amazon.com/images/I/510KTKEs6BL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/417N1QbfnaL._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/41Vv2xfBf8L._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/31rDnnZafwL._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/41MLz5to9wL._SL500_.jpg
        width: 500
        height: 334
    caracteristicasAmazon:
      - 'El paquete incluye: Un vestido de flamenca y un tocado de flor.'
      - >-
        Diseño exclusivo: Traje de baile flamenco clásico en una bonita combinación de colores rojo y negro. Diseño
        único con tocado a juego, ideal para interpretar a bailarinas sevillanas y estimular el interés de las niñas por
        el baile flamenco.
      - >-
        Ocasiones: Adecuado para todos los eventos, actuaciones, fiestas de cumpleaños, fiestas de baile, Navidad,
        Halloween, carnaval, Feria de Abril, cosplay, fiestas temáticas, etc. Ideal para regalos de cumpleaños y
        Navidad.
      - >-
        Calidad: Material de alta calidad, suave y cómodo. Relibeauty siempre se centra en la calidad del producto, por
        favor, estar seguro de ordenar.
      - 'Atención: Por favor, compruebe la tabla de tallas en la imagen antes de realizar un pedido.'
  - ASIN: B08BCS4PG4
    nombre: Traje Profesional 2 Piezas Volante en Manga
    brand: Gojoy shop
    enlace: https://amzn.to/4o7CJeM
    valoracion: 4.8
    descripcion: >-
      Conjunto profesional de flamenca con body y falda de volantes. Muy cómodo gracias al tejido elástico. Disponible
      en varios colores, ideal para baile o espectáculos.
    lo_mejor: Ideal como vestuario completo para clases de baile
    a_tener_en_cuenta: El diseño es más funcional que vistoso
    caracteristicas:
      - Incluye body y falda de flamenca
      - Tejido elástico de fácil colocación
      - Mangas con volantes
      - Se lava a mano o a máquina
      - Varias tallas y colores disponibles
    precio: "29,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41L1JcvjGVL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 281
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41lyptlmsAL._SL500_.jpg
        width: 492
        height: 500
      - url: https://m.media-amazon.com/images/I/41L6TarE+yL._SL500_.jpg
        width: 500
        height: 474
      - url: https://m.media-amazon.com/images/I/41908l5QWnL._SL500_.jpg
        width: 365
        height: 500
      - url: https://m.media-amazon.com/images/I/41L1JcvjGVL._SL500_.jpg
        width: 281
        height: 500
      - url: https://m.media-amazon.com/images/I/417FjOQ1uLL._SL500_.jpg
        width: 369
        height: 500
    caracteristicasAmazon:
      - >-
        Nuestra tienda en Amazon: Gojoy Shop, tenemos varios modelos de disfraces vestidos de baile para adultos y
        niños. Este Traje de Body con Doble Volante en Manga y Falda Ideal para Baile Danza Flamenco o Sevillanas para
        Mujer.
      - Tejido de alta calidad y elástico.
      - '<br> Fácil de usar: nuestras prendas están hechas de tejido elástico para un uso fácil de vestirse o quitarse.'
      - Este artículo cumple las normas vigentes de la C.E..
      - Contiene Body y Falda con Doble Volante en Manga.
  - ASIN: B09YT8TL7J
    nombre: Vestido de Flamenco Largo y Elegante
    brand: Tandada
    enlace: https://amzn.to/40H13dw
    valoracion: 4.7
    descripcion: >-
      Vestido largo para danza con vuelo de 360°, tela suave y transpirable. Ideal para ballet moderno, flamenco o
      espectáculos. Disponible hasta talla 3XL.
    lo_mejor: Amplio vuelo y gran comodidad para moverse
    a_tener_en_cuenta: No es un diseño tradicional de flamenca
    caracteristicas:
      - Tela ligera con buena caída
      - Falda con vuelo de 360 grados
      - Cómodo para practicar y bailar
      - Ideal para flamenco, lírico o contemporáneo
      - Disponible en tallas grandes
    precio: "58,00\_€"
    precioOriginal: No especificado
    disponibilidad: Envío en 2 a 3 días
    imagen: https://m.media-amazon.com/images/I/41vz4uEAzpL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 500
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/416osuWnXuL._SL500_.jpg
        width: 364
        height: 500
      - url: https://m.media-amazon.com/images/I/41U9XW9XjoL._SL500_.jpg
        width: 366
        height: 500
      - url: https://m.media-amazon.com/images/I/41WVQFHvPrL._SL500_.jpg
        width: 500
        height: 491
      - url: https://m.media-amazon.com/images/I/410Eonf1TsL._SL500_.jpg
        width: 490
        height: 500
      - url: https://m.media-amazon.com/images/I/41yI4bMcP6L._SL500_.jpg
        width: 500
        height: 241
      - url: https://m.media-amazon.com/images/I/411olGgqoxL._SL500_.jpg
        width: 385
        height: 500
    caracteristicasAmazon:
      - >-
        [Calidad creíble] Hecho de tela de alta calidad, gran sensación de drapeado, transpirable y agradable para la
        piel, ofrece comodidad durante todo el día al bailar, adecuado para todos los amantes del baile.
      - >-
        [Diseño elegante] Falda completa simple y elegante, la falda larga y grande puede alcanzar los 360 grados para
        adaptarse a sus diferentes posturas de baile, perfectas para girar y hacer movimientos dinámicos. La elección
        perfecta para bailarines de ballet/líricos modernos.
      - >-
        [Multipropósito] Perfecto para danza lírica moderna, ceremonia, latín, vals, clase de baile, ballet, baile
        estándar nacional, banquete, etc. También es ideal para usar en vacaciones, gimnasia, playa, cócteles, fiestas
        nocturnas, representaciones teatrales, bailes, accesorios fotográficos y otras ocasiones especiales.
      - >-
        [Cómodas] Son suaves y elegantes. En la práctica de la danza, el vestido hace que el practicante se sienta
        cómodo y cumpla con los requisitos de la práctica de la danza.
      - >-
        [Talla y servicio]Mujer talla S, M, L, XL, XXL. Consulta la tabla de tallas antes de comprar. La satisfacción
        del cliente es nuestra principal prioridad. No dude en enviar un correo electrónico a nuestro equipo de posventa
        si tiene alguna pregunta o inquietud.
  - ASIN: B0DZ75Y8TJ
    nombre: Traje de Flamenca Mujer Verde
    brand: Partilandia
    enlace: https://amzn.to/41hItbZ
    valoracion: 4.2
    descripcion: Disfraz de flamenca en color verde con lunares blancos. Corte clásico de vestido de sevillana.
    precio: "24,48\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/51a0Do1t-DL._SL500_.jpg
    imagenHeight: 454
    imagenWidth: 500
    lo_mejor: Buen diseño y precio asequible
    a_tener_en_cuenta: Es un disfraz más que un traje profesional
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41XBNkeg3vL._SL500_.jpg
        width: 250
        height: 500
      - url: https://m.media-amazon.com/images/I/51dDK9J0uEL._SL500_.jpg
        width: 500
        height: 454
    caracteristicasAmazon:
      - ✅ Incluye Vestido
      - ❌ No incluye Resto de complementos
      - ⭐ Muy demandado para Carnaval 🤴👸🧚‍♀️💃
  - ASIN: B019A3UAI4
    nombre: Traje de Flamenca Mujer Rojo
    brand: FIESTAS GUIRCA
    enlace: https://amzn.to/4lJZgwF
    valoracion: 4.2
    descripcion: Disfraz de flamenca en color rojo con lunares blancos. Corte clásico de vestido de sevillana.
    precio: "23,04\_€"
    lo_mejor: Buen diseño y precio asequible
    a_tener_en_cuenta: Es un disfraz más que un traje profesional
    precioOriginal: No especificado
    disponibilidad: En stock
    imagen: https://m.media-amazon.com/images/I/41efHDWplLL._SL500_.jpg
    imagenHeight: 500
    imagenWidth: 177
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41Ot9fsZhQL._SL500_.jpg
        width: 273
        height: 500
      - url: https://m.media-amazon.com/images/I/41IMGR+8LvL._SL500_.jpg
        width: 320
        height: 500
      - url: https://m.media-amazon.com/images/I/51CPXAT5V4L._SL500_.jpg
        width: 500
        height: 441
      - url: https://m.media-amazon.com/images/I/41IMGR+8LvL._SL500_.jpg
        width: 320
        height: 500
      - url: https://m.media-amazon.com/images/I/41RHy6MycfL._SL500_.jpg
        width: 320
        height: 500
      - url: https://m.media-amazon.com/images/I/41IMGR+8LvL._SL500_.jpg
        width: 320
        height: 500
      - url: https://m.media-amazon.com/images/I/41IMGR+8LvL._SL500_.jpg
        width: 320
        height: 500
    caracteristicasAmazon:
      - 'Contenido del disfraz de bailarina de flamenco española: Vestido. NO_INCLUIDO: Accesorios'
      - 'GUÍA DE TALLAS DE DISFRAZ: Mujer M 38-40'
      - 'MEDIDAS DEL DISFRAZ APROX: Busto 93 - 96 cm, cintura 73 - 75 cm, caderas 99,5 - 102 cm'
      - Este disfráz está hecho de Poliester y cumple con los estándares de seguridad
      - 'FIESTAS GUIRCA Disfraces de mujer adulto: una gran elección para tu fiesta temática.'
