productos:
  - ASIN: B01ETFVVQ8
    a_tener_en_cuenta: Viscoelástica + Sensopur HR
    brand: Imperial Confort
    caracteristicas:
      - Firmeza media/alta
      - Viscoelástica + Sensopur HR
      - 24 cm
      - Tratamientos higiénicos antiácaros
      - Buena transpiración y secado rápido
    descripcion: >-
      El colchón Oslo New me ha parecido una opción equilibrada si buscas firmeza media-alta con buen confort. Su núcleo
      Sensopur HR y el acolchado viscoelástico dan una sensación agradable al tumbarte, sin ser demasiado blando. Me
      gusta que incluya tratamientos higiénicos contra ácaros y bacterias, lo que aporta tranquilidad si eres alérgico.
      La transpirabilidad está bien conseguida gracias a sus materiales porosos. Además, es fácil de mantener, ya que
      seca rápido. Una alternativa correcta y fabricada en España, lo que siempre suma puntos en calidad y confianza.
    enlace: https://amzn.to/3TRyEgQ
    imagen: https://m.media-amazon.com/images/I/21h241WAwJL._SL500_.jpg
    lo_mejor: Media-Alta
    nombre: Imperial Confort Oslo New Viscoelástico
    valoracion: 4.3
    precio: "147,18\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31SuR0B5lEL._SL500_.jpg
        width: 500
        height: 199
      - url: https://m.media-amazon.com/images/I/21h241WAwJL._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/31CRE75aahL._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/31zzDDK8eLL._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/31TUxIj-T5L._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/41hguuLN1PL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 334
    imagenWidth: 500
  - ASIN: B0F38HGRY1
    a_tener_en_cuenta: Viscoelástica + HR multicapa
    brand: Todocama
    caracteristicas:
      - Firmeza media/alta
      - Viscoelástica + HR multicapa
      - 21 cm
      - Doble cara verano/invierno
      - Certificados Oeko-Tex y CertiPUR
    descripcion: >-
      Este colchón de Todocama me ha sorprendido por su buena relación calidad-precio. El núcleo HR con estructura de
      célula abierta aporta firmeza sin perder adaptabilidad, ideal para quienes quieren soporte sin hundirse. Tiene una
      cara de invierno y otra de verano, lo que lo hace versátil durante todo el año. La cara de invierno es mullida y
      cálida, mientras que la de verano es muy fresca gracias al tejido 3D. Un detalle que valoro mucho: cuenta con
      certificaciones como Oeko-Tex y CertiPUR, que garantizan calidad sin sustancias nocivas.
    enlace: https://amzn.to/44bnh9G
    imagen: https://m.media-amazon.com/images/I/313clh1+UqL._SL500_.jpg
    lo_mejor: Media-Alta
    nombre: Todocama Pure Flow Max Viscoelástico
    valoracion: 4.5
    precio: "89,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/316yWtLbzuL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/316tbVdzxDL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/214ZYRydSCL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/31d+zUn7iaL._SL500_.jpg
        width: 500
        height: 353
      - url: https://m.media-amazon.com/images/I/41apybtbMgL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/31dK7g8f6FL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/41xFYYohx2L._SL500_.jpg
        width: 500
        height: 333
    imagenHeight: 333
    imagenWidth: 500
  - ASIN: B07D2BX9BS
    a_tener_en_cuenta: HR + visco Bio Sense
    brand: Simpur Low Cost
    caracteristicas:
      - Firmeza media/alta
      - HR + visco Bio Sense
      - 30 cm
      - 13 zonas de confort ergonómico
      - Terapia de carbono antiolor
    descripcion: >-
      Si lo que buscas es un colchón viscoelástico alto, duradero y con excelente soporte, este Dream Repair es una
      pasada. Los 30 cm de altura lo convierten en una opción robusta y muy cómoda. La combinación de capas
      viscoelásticas y HR ofrece una tumbada ergonómica. Incorpora 13 zonas de confort que se notan sobre todo si tienes
      problemas de espalda o duermes en varias posturas. Además, los materiales están pensados para reducir el calor y
      la humedad, y cuenta con terapia de carbono que combate los malos olores. Es un colchón de gama alta que se nota
      desde la primera noche.
    enlace: https://amzn.to/4eyKdmL
    imagen: https://m.media-amazon.com/images/I/51WTGpRrUQL._SL500_.jpg
    lo_mejor: Media-Alta
    nombre: Simpur Dream Repair Viscoelástico
    valoracion: 4.6
    precio: "194,00\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31HCf5Ops4L._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/41BEBpyty9L._SL500_.jpg
        width: 500
        height: 334
      - url: https://m.media-amazon.com/images/I/41ezw+ASG3L._SL500_.jpg
        width: 500
        height: 311
      - url: https://m.media-amazon.com/images/I/311nxbmZBVL._SL500_.jpg
        width: 500
        height: 343
      - url: https://m.media-amazon.com/images/I/51S3KpEteTL._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/41FNdCM+yhL._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/51dKWEI571L._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/41FNdCM+yhL._SL500_.jpg
        width: 500
        height: 268
    imagenHeight: 305
    imagenWidth: 500
  - ASIN: B07RP81T79
    a_tener_en_cuenta: Muelles ensacados + viscoelástica
    brand: Simpur Low Cost
    caracteristicas:
      - Firmeza alta
      - Muelles ensacados + viscoelástica
      - 30 cm
      - 9 capas con sistema Multi Progress
      - Alta transpiración con grafeno
    descripcion: >-
      Este Simpur Visco Spring Magestic es uno de los colchones que más me ha sorprendido en cuanto a soporte y
      adaptabilidad. Los muelles ensacados junto con sus 9 capas lo convierten en un colchón robusto, con independencia
      de lechos real. Los materiales viscoelásticos de alta densidad se adaptan muy bien sin hacerte sentir hundido. Su
      transpiración es excelente, ideal si eres caluroso, y cuenta con tratamientos hipoalergénicos. Es una opción
      firme, cómoda y duradera, con 30 cm de grosor y buenos acabados.
    enlace: https://amzn.to/3TPb3xc
    imagen: https://m.media-amazon.com/images/I/31Rq86R8SNL._SL500_.jpg
    lo_mejor: Alta
    nombre: Simpur Visco Spring Magestic Muelles Ensacados + Viscoelástico
    valoracion: 4.4
    precio: "218,00\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41cGARpdVuL._SL500_.jpg
        width: 500
        height: 373
      - url: https://m.media-amazon.com/images/I/41+Hu3KRzBL._SL500_.jpg
        width: 500
        height: 375
      - url: https://m.media-amazon.com/images/I/51Jz3bzZuFL._SL500_.jpg
        width: 500
        height: 375
      - url: https://m.media-amazon.com/images/I/518OBjN-ESL._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/51ID+3mLKhL._SL500_.jpg
        width: 500
        height: 268
      - url: https://m.media-amazon.com/images/I/518OBjN-ESL._SL500_.jpg
        width: 500
        height: 268
    imagenHeight: 375
    imagenWidth: 500
  - ASIN: B016AFQAD4
    a_tener_en_cuenta: Memory foam + HR
    brand: Dormio
    caracteristicas:
      - Firme
      - Memory foam + HR
      - 21 cm
      - Tejido 3D transpirable
      - Tratamiento antiácaros y antibacterias
    descripcion: >-
      El Dormio Zafiro es un colchón básico pero cumplidor. Es una buena elección si buscas algo económico sin renunciar
      a un mínimo de confort. Tiene viscoelástica en la parte superior y un núcleo que evita deformaciones, manteniendo
      la firmeza con el paso del tiempo. La ventilación es correcta gracias al tejido 3D lateral y el tratamiento
      antiácaros es un buen plus. Aunque no tiene muchas capas, cumple su función con buena adaptabilidad para su rango
      de precio. Ideal como colchón juvenil o de uso ocasional en segundas residencias.
    enlace: https://amzn.to/4lrM1A0
    imagen: https://m.media-amazon.com/images/I/31HISKU4EpL._SL500_.jpg
    lo_mejor: Media-Alta
    nombre: Dormio Zafiro Viscoelástico
    valoracion: 4.2
    precio: "101,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41inzjZCfWL._SL500_.jpg
        width: 500
        height: 326
      - url: https://m.media-amazon.com/images/I/31HN0PWlZnL._SL500_.jpg
        width: 500
        height: 232
      - url: https://m.media-amazon.com/images/I/416u96KiAbL._SL500_.jpg
        width: 333
        height: 500
      - url: https://m.media-amazon.com/images/I/2169wcxRFOL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/41Bh9UdslSL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/4168o-yQMHL._SL500_.jpg
        width: 333
        height: 500
      - url: https://m.media-amazon.com/images/I/41+C3XvaEzL._SL500_.jpg
        width: 333
        height: 500
      - url: https://m.media-amazon.com/images/I/516oT-WHMOL._SL500_.jpg
        width: 500
        height: 336
      - url: https://m.media-amazon.com/images/I/419xtfzevXL._SL500_.jpg
        width: 500
        height: 322
      - url: https://m.media-amazon.com/images/I/41Re2DU8iKL._SL500_.jpg
        width: 333
        height: 500
    imagenHeight: 312
    imagenWidth: 500
  - ASIN: B08YB77MQW
    a_tener_en_cuenta: Memory foam + espuma Breath Soft
    brand: ZZ DON DESCANSO
    caracteristicas:
      - Firmeza media-alta
      - Memory foam + espuma Breath Soft
      - 26 cm
      - Reversible y transpirable
      - Tejido Aloe Vera con núcleo Gravitas Core
    descripcion: >-
      El colchón Mulhacén de Don Descanso me ha parecido una opción muy equilibrada y transpirable. Su núcleo ergonómico
      reparte el peso de forma uniforme y ayuda a mantener una postura saludable. Lo mejor es que es reversible, así que
      puedes girarlo cada cierto tiempo y prolongar su vida útil. El tejido Aloe Vera aporta suavidad y frescor al
      tacto, ideal para quienes buscan un descanso más natural. Recomiendo este modelo especialmente si valoras la
      higiene y una firmeza media-alta sin renunciar al confort.
    enlace: https://amzn.to/4l8fgYW
    imagen: https://m.media-amazon.com/images/I/3189Nk0BdoL._SL500_.jpg
    lo_mejor: Media-Alta
    nombre: ZZ Don Descanso Mulhacén Viscoelástico
    valoracion: 4.4
    precio: "147,40\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31yen3k9fFL._SL500_.jpg
        width: 500
        height: 225
      - url: https://m.media-amazon.com/images/I/41h8qSxsQ4L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41IN3asfWUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/4189iT6js3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41-EryeZQfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41OYPp5Sz9L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Qu5YKDIwL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31YZkiDa2NL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0B9BX7R2R
    a_tener_en_cuenta: Memory foam + HR FoamTech
    brand: Cecotec
    caracteristicas:
      - Firmeza alta
      - Memory foam + HR FoamTech
      - 21 cm
      - Cara verano/invierno con tejido PureCare
      - Triple protección e higiene
    descripcion: >-
      Este modelo de Cecotec combina firmeza alta con buen confort gracias a su capa de ViscoCare. El núcleo FoamTech
      proporciona una base resistente y uniforme, lo que se nota al tumbarte. Tiene dos caras diferenciadas, lo que lo
      hace más versátil durante el año. También es hipoalergénico y se entrega al vacío para facilitar el transporte. Un
      colchón moderno, con buena relación calidad-precio y muy recomendable si buscas soporte sólido.
    enlace: https://amzn.to/3Tgk16F
    imagen: https://m.media-amazon.com/images/I/41InZTIv-vL._SL500_.jpg
    lo_mejor: Alta
    nombre: Cecotec Flow ViscoCare 1900 Viscoelástico
    valoracion: 4.3
    precio: "89,90\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51Ax9W+Kd2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31VKaFJNALL._SL500_.jpg
        width: 500
        height: 205
      - url: https://m.media-amazon.com/images/I/31Oap+P9pqL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31T6fpYFgxL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51BOBQ5tSaL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41sE1bJZ+FL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B07L9F6DMD
    a_tener_en_cuenta: Visco carbono + biocerámica
    brand: ROYAL SLEEP
    caracteristicas:
      - Firmeza alta
      - Visco carbono + biocerámica
      - 25 cm
      - Efecto antiestrés y cara verano/invierno
      - Alta gama con tejidos resistentes
    descripcion: >-
      El Royal Sleep es un colchón de gama alta que destaca por su firmeza y efecto antiestrés. Tiene una capa de visco
      carbono que ayuda a eliminar la electricidad estática y mejora la relajación. También cuenta con biocerámica y
      buena transpiración en la cara de verano. Es reversible y está fabricado íntegramente en España, lo que le da un
      plus de confianza. Muy recomendado si tienes el sueño ligero y buscas una superficie estable y sin sobresaltos.
    enlace: https://amzn.to/4lCLETB
    imagen: https://m.media-amazon.com/images/I/51xHQM5pq5L._SL500_.jpg
    lo_mejor: Alta
    nombre: Royal Sleep Ceramic Plus Viscoelástico + Carbono
    valoracion: 4.6
    precio: "179,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31w59SeSMQL._SL500_.jpg
        width: 500
        height: 197
      - url: https://m.media-amazon.com/images/I/31HhEmyB7sL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51gsTZzWpyL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31EwhaYWv3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/519vjCXx0KL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/61OyZnPArfL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/613XhhQVDCL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41zat4rA5LL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41QgJufwIQL._SL500_.jpg
        width: 500
        height: 281
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B07YDV2D7S
    a_tener_en_cuenta: Viscoelástica + HR
    brand: PIKOLIN
    caracteristicas:
      - Firmeza alta
      - Viscoelástica + HR
      - 24 cm
      - Triple barrera higiénica
      - Independencia de lechos real
    descripcion: >-
      El Pikolin Leah es un colchón que transmite calidad desde que lo abres. Tiene una firmeza alta que se nota estable
      y agradable, ideal para quien no quiere hundimientos. La independencia de lechos es efectiva y su triple barrera
      higiénica es perfecta para personas alérgicas. Se adapta bien a cualquier postura, y aunque es firme, la capa
      viscoelástica suaviza la tumbada. Sin duda, una gran opción si quieres algo duradero y con garantía de una marca
      de toda la vida.
    enlace: https://amzn.to/3IajSPK
    imagen: https://m.media-amazon.com/images/I/41D2T-pgNOL._SL500_.jpg
    lo_mejor: Alta
    nombre: Pikolin Leah
    valoracion: 4.7
    precio: "299,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51ckIimpS2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41S0a13SsAL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41H8Zyz3hNL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/61gTV7Yf8BL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51n1sWpJHsL._SL500_.jpg
        width: 379
        height: 500
      - url: https://m.media-amazon.com/images/I/51h7xovFFBL._SL500_.jpg
        width: 500
        height: 381
    imagenHeight: 500
    imagenWidth: 500
titulo_a_tener_en_cuenta: Material principal
titulo_lo_mejor: Firmeza
