- bloques:
  - subtitulo: ✔️ ¿Por qué recomiendo Khadi?
    texto: Es una de las marcas que más uso en mi centro de belleza. Funciona especialmente
      bien en mujeres que vienen de años usando tintes químicos y buscan pasarse a
      lo natural.
  - subtitulo: 🌿 Ingredientes y fórmula ayurvédica
    texto: Sus barros combinan henna, índigo, cassia y plantas revitalizantes como
      amla o neem, con una base 100% vegetal y sin aditivos.
  - subtitulo: 👩‍🔬 Mi experiencia profesional
    texto: He visto cómo incluso cabellos dañados o sin brillo recuperan fuerza y
      color natural tras varias aplicaciones. Me encanta el tono Castaño Medio, pero
      el Cobre también deja reflejos preciosos.
  colores:
  - ASIN: B00SGZ8JSQ
    color: '#f5e083'
    link: https://amzn.to/43llhdj
    nombre: Rubio toque dorado
  - ASIN: B00AFAYQ3W
    color: '#dddddd'
    link: https://amzn.to/4j6VZoX
    nombre: Neutral, sin color
  - ASIN: B07ZRCRS8D
    color: '#b87333'
    link: https://amzn.to/3SKojmg
    nombre: Cobre
  - ASIN: B003TNOSXK
    color: '#cccccc'
    link: https://amzn.to/3YQtp40
    nombre: Rojizo
  - ASIN: B07G5BZYD4
    color: '#f0c14b'
    link: https://amzn.to/4k2GNKM
    nombre: Castaño dorado
  - ASIN: B00SGZHQSA
    color: '#f5e083'
    link: https://amzn.to/4mn7N9x
    nombre: Rubio Claro
  - ASIN: B07G56NP3M
    color: '#a8753f'
    link: https://amzn.to/3FgeeKS
    nombre: Castaño Medio
  - ASIN: B003TNR1WK
    color: '#e6d3a3'
    link: https://amzn.to/3SGPiiD
    nombre: Castaño Claro
  - ASIN: B01AT9FI80
    color: '#8b5d33'
    link: https://amzn.to/3H21nfW
    nombre: Castaño Avellana
  - ASIN: B01676KZCS
    color: '#8b5d33'
    link: https://amzn.to/4dnxgvz
    nombre: Castaño Oscuro
  - ASIN: B0773GQPDK
    color: '#f5e083'
    link: https://amzn.to/4kuYK4L
    nombre: Rubio Oscuro Ceniza
  - ASIN: B07G58NBMG
    color: '#8b5d33'
    link: https://amzn.to/3ZfaEYn
    nombre: Castaño Ceniza
  - ASIN: B00Q6S2DYQ
    color: '#3f51b5'
    link: https://amzn.to/4mijjTv
    nombre: Indigo Puro
  - ASIN: B003TNR1U2
    color: '#1c1c1c'
    link: https://amzn.to/43sSjZ1
    nombre: Negro
  - ASIN: B003TNIWPU
    color: '#c0392b'
    link: https://amzn.to/4kqpao0
    nombre: Rojo Puro
  - ASIN: B07GYN7RFR
    color: '#f5e083'
    link: https://amzn.to/3FgGexW
    nombre: Rubio Miel Amanecer
  - ASIN: B00SGZCXRO
    color: '#f5e083'
    link: https://amzn.to/45iRZ1o
    nombre: Rubio Medio
  - ASIN: B0C4T9CCCN
    color: '#a52a2a'
    link: https://amzn.to/4j6WEXp
    nombre: Caoba
  - ASIN: B097BQV4LD
    color: '#a0c4ff'
    link: https://amzn.to/4jdG8oG
    nombre: Color prep
  emoji: 🌿
  recomendado: true
  titulo: 'Khadi: Coloración Ayurvédica 100% Vegetal'
- bloques:
  - subtitulo: ✔️ ¿Por qué la recomiendo?
    texto: Es una marca veterana y muy versátil. Tiene tonos cálidos y fríos que se
      adaptan a diferentes bases de cabello. Mis clientas suelen elegirla cuando quieren
      algo natural, pero con variedad.
  - subtitulo: 🧪 Mezcla equilibrada de plantas
    texto: Sus fórmulas combinan henna con cassia, amla y otras plantas. No engrasan,
      no resecan y son aptas para cuero cabelludo sensible.
  - subtitulo: 💬 Experiencia con clientas
    texto: Los tonos Castaño Cobrizo y Caoba Oscuro son ideales en mujeres de piel
      clara. Dejan el pelo suelto, con un color natural y sin residuos.
  - subtitulo: ⏱️ Tiempo recomendado
    texto: Al menos una hora de exposición para fijar bien el pigmento. Se nota mucho
      la diferencia si se respeta el tiempo.
  colores:
  - ASIN: B00V6AFQPM
    color: '#a52a2a'
    link: https://amzn.to/43noMzE
    nombre: Super Caoba Oscuro
  - ASIN: B00DN9F7BW
    color: '#e6d3a3'
    link: https://amzn.to/43ri63H
    nombre: Castaño Claro
  - ASIN: B00DN9F8K2
    color: '#8b5d33'
    link: https://amzn.to/44MEtmE
    nombre: Castaño Oscuro
  - ASIN: B01HSPUOYG
    color: '#f5e083'
    link: https://amzn.to/4jg4GgR
    nombre: Rubio Intenso
  - ASIN: B00DN9FBFY
    color: '#1c1c1c'
    link: https://amzn.to/4329gdQ
    nombre: Negro
  - ASIN: B00LJ4052Y
    color: '#a8753f'
    link: https://amzn.to/3ZfbPqL
    nombre: Castaño Medio
  - ASIN: B00DN9FEQA
    color: '#f5e083'
    link: https://amzn.to/4kw9kbH
    nombre: Rubio Ceniza
  - ASIN: B00DN9N64M
    color: '#8b5d33'
    link: https://amzn.to/4k6SKiI
    nombre: Castaño Caoba
  - ASIN: B079DQ4N6Y
    color: '#8b5d33'
    link: https://amzn.to/4drXzRl
    nombre: Castaño Cobrizo
  - ASIN: B00DN9F6AE
    color: '#a52a2a'
    link: https://amzn.to/3FgfNbI
    nombre: Caoba Oscuro
  - ASIN: B0CRRZ5GJ5
    color: '#cccccc'
    link: https://amzn.to/43mdMml
    nombre: Chocolate
  - ASIN: B0CRS36BK2
    color: '#c0392b'
    link: https://amzn.to/43oNpMI
    nombre: Rojo Burdeos
  - ASIN: B00DN9F5A0
    color: '#a52a2a'
    link: https://amzn.to/4msYzbW
    nombre: Super Caoba Luminoso
  - ASIN: B00V6AHO4I
    color: '#8b5d33'
    link: https://amzn.to/3Znub8M
    nombre: Castaño Intenso
  - ASIN: B00DN9FHCQ
    color: '#f5e083'
    link: https://amzn.to/4mlKv3F
    nombre: Rubio Dorado
  - ASIN: B00V6AHKLU
    color: '#3f51b5'
    link: https://amzn.to/432t8xo
    nombre: Indigo
  - ASIN: B0CRS1MSBT
    color: '#a52a2a'
    link: https://amzn.to/3SGpjI2
    nombre: Caoba Intenso
  - ASIN: B0CRS21KQ3
    color: '#a52a2a'
    link: https://amzn.to/3H05Hw6
    nombre: Caoba Natural
  - ASIN: B07Z6NNNKX
    color: '#e6e6e6'
    link: https://amzn.to/4ktVVRq
    nombre: Sidr Tratamiento Capilar Natural
  - ASIN: B07Z6NDKN9
    color: '#e6e6e6'
    link: https://amzn.to/4ko59OO
    nombre: Manjistha Tratamiento Capilar Natural
  - ASIN: B07Z6NDVPJ
    color: '#e6e6e6'
    link: https://amzn.to/3EZJwpn
    nombre: Brahmi Tratamiento Capilar Natural
  - ASIN: B00DN9I534
    color: '#aed581'
    link: https://amzn.to/4dswcXd
    nombre: Tratamiento Capilar Ayurvédico Amla
  - ASIN: B00DN9FDVG
    color: '#b2dfdb'
    link: https://amzn.to/3GZRTSl
    nombre: Fortalecedor de Cabello
  emoji: 🌺
  recomendado: true
  titulo: 'Radhe Shyam: Coloración 100% Natural con Tradición'
- bloques:
  - subtitulo: ✔️ ¿Qué ofrece esta marca?
    texto: Es una opción económica pero eficaz. Perfecta para quienes quieren iniciarse
      en el mundo de los pigmentos naturales sin gastar mucho, pero sin renunciar
      a resultados visibles.
  - subtitulo: 🌿 Ingredientes y textura
    texto: Contiene henna, índigo y amla. Tiene una textura muy fina, fácil de aplicar
      y de aclarar, lo cual agradecen mucho las clientas con cabello seco.
  - subtitulo: 💬 Opinión tras probarla
    texto: El tono Caoba es muy versátil para bases castañas que quieren un toque
      rojizo elegante. Además, el índigo de esta marca funciona muy bien para cubrir
      canas en dos pasos.
  - subtitulo: 💡 Ideal para...
    texto: Personas con cuero cabelludo sensible que quieren una solución sencilla,
      sin perfumes ni químicos, pero con buenos resultados.
  colores:
  - ASIN: B0BYGVSTVN
    color: '#a52a2a'
    link: https://amzn.to/44FnFxL
    nombre: Caoba
  - ASIN: B0BYGKV6G5
    color: '#8b5d33'
    link: https://amzn.to/3SIg8H7
    nombre: Castaño Oscuro
  - ASIN: B08ZYG5H29
    color: '#cccccc'
    link: https://amzn.to/4drWMjl
    nombre: Índigo
  emoji: 🍃
  recomendado: false
  titulo: 'Real Earth: Barros Orgánicos para un Cabello Saludable'
- bloques:
  - subtitulo: ✔️ ¿Qué es?
    texto: Este producto combina dos hierbas, la henna y el índigo, para proporcionar
      un hermoso tono de cabello.
  - subtitulo: 🌿 Cómo la utilizo en mi centro
    texto: Muchas veces combinada con aceites esenciales para mejorar su fijación
      y aroma. La aplico especialmente en cabellos débiles o con caída.
  - subtitulo: ⏱️ Recomendaciones de uso
    texto: Es importante dejarla actuar al menos una hora para que el pigmento se
      fije bien. Cuanto más tiempo se deje, mayor será la intensidad del color.
  colores:
  - ASIN: B09SZCTP7F
    color: '#8b5d33'
    link: https://amzn.to/3HgKD4r
    nombre: Castaño Oscuro
  - ASIN: B09SZBR8Z7
    color: '#e6d3a3'
    link: https://amzn.to/4kl9SS9
    nombre: Castaño Claro
  - ASIN: B09SZC4BH8
    color: '#8b5d33'
    link: https://amzn.to/4ko4e0O
    nombre: Castaño
  - ASIN: B09QD436MY
    color: '#b87333'
    link: https://amzn.to/4moBWFg
    nombre: Rojo cobre
  - ASIN: B0D6WJF6GL
    color: '#f5e083'
    link: https://amzn.to/4je8q2z
    nombre: Rubio Natural
  - ASIN: B0CHMR6MXX
    color: '#cccccc'
    link: https://amzn.to/4moe4BQ
    nombre: Neutro
  emoji: 🌸
  recomendado: false
  titulo: 'Henna y 3x Indigo: Tradición Natural para el Cuidado Capilar'