- emoji: 🌿
  titulo: 'Khadi: Coloración Ayurvédica 100% Vegetal'
  recomendado: true
  bloques:
  - subtitulo: ✔️ ¿Por qué recomiendo Khadi?
    texto: Es una de las marcas que más uso en mi centro de belleza. Funciona especialmente
      bien en mujeres que vienen de años usando tintes químicos y buscan pasarse a
      lo natural.
  - subtitulo: 🌿 Ingredientes y fórmula ayurvédica
    texto: Sus barros combinan henna, índigo, cassia y plantas revitalizantes como
      amla o neem, con una base 100% vegetal y sin aditivos.
  - subtitulo: 👩‍🔬 Mi experiencia profesional
    texto: He visto cómo incluso cabellos dañados o sin brillo recuperan fuerza y
      color natural tras varias aplicaciones. Me encanta el tono Castaño Medio, pero
      el Cobre también deja reflejos preciosos.
  colores:
  - nombre: Rubio toque dorado
    link: https://amzn.to/43llhdj
    color: '#f5e083'
  - nombre: Neutral, sin color
    link: https://amzn.to/4j6VZoX
    color: '#dddddd'
  - nombre: Cobre
    link: https://amzn.to/3SKojmg
    color: '#b87333'
  - nombre: Rojizo
    link: https://amzn.to/3YQtp40
    color: '#cccccc'
  - nombre: Castaño dorado
    link: https://amzn.to/4k2GNKM
    color: '#f0c14b'
  - nombre: Rubio Claro
    link: https://amzn.to/4mn7N9x
    color: '#f5e083'
  - nombre: Castaño Medio
    link: https://amzn.to/3FgeeKS
    color: '#a8753f'
  - nombre: Castaño Claro
    link: https://amzn.to/3SGPiiD
    color: '#e6d3a3'
  - nombre: Castaño Avellana
    link: https://amzn.to/3H21nfW
    color: '#8b5d33'
  - nombre: Castaño Oscuro
    link: https://amzn.to/4dnxgvz
    color: '#8b5d33'
  - nombre: Rubio Oscuro Ceniza
    link: https://amzn.to/4kuYK4L
    color: '#f5e083'
  - nombre: Castaño Ceniza
    link: https://amzn.to/3ZfaEYn
    color: '#8b5d33'
  - nombre: Indigo Puro
    link: https://amzn.to/4mijjTv
    color: '#3f51b5'
  - nombre: Negro
    link: https://amzn.to/43sSjZ1
    color: '#1c1c1c'
  - nombre: Rojo Puro
    link: https://amzn.to/4kqpao0
    color: '#c0392b'
  - nombre: Rubio Miel Amanecer
    link: https://amzn.to/3FgGexW
    color: '#f5e083'
  - nombre: Rubio Medio
    link: https://amzn.to/45iRZ1o
    color: '#f5e083'
  - nombre: Caoba
    link: https://amzn.to/4j6WEXp
    color: '#a52a2a'
  - nombre: Color prep
    link: https://amzn.to/4jdG8oG
    color: '#a0c4ff'
- emoji: 🌺
  titulo: 'Radhe Shyam: Coloración 100% Natural con Tradición'
  recomendado: true
  bloques:
  - subtitulo: ✔️ ¿Por qué la recomiendo?
    texto: Es una marca veterana y muy versátil. Tiene tonos cálidos y fríos que se
      adaptan a diferentes bases de cabello. Mis clientas suelen elegirla cuando quieren
      algo natural, pero con variedad.
  - subtitulo: 🧪 Mezcla equilibrada de plantas
    texto: Sus fórmulas combinan henna con cassia, amla y otras plantas. No engrasan,
      no resecan y son aptas para cuero cabelludo sensible.
  - subtitulo: 💬 Experiencia con clientas
    texto: Los tonos Castaño Cobrizo y Caoba Oscuro son ideales en mujeres de piel
      clara. Dejan el pelo suelto, con un color natural y sin residuos.
  - subtitulo: ⏱️ Tiempo recomendado
    texto: Al menos una hora de exposición para fijar bien el pigmento. Se nota mucho
      la diferencia si se respeta el tiempo.
  colores:
  - nombre: Super Caoba Oscuro
    link: https://amzn.to/43noMzE
    color: '#a52a2a'
  - nombre: Castaño Claro
    link: https://amzn.to/43ri63H
    color: '#e6d3a3'
  - nombre: Castaño Oscuro
    link: https://amzn.to/44MEtmE
    color: '#8b5d33'
  - nombre: Rubio Intenso
    link: https://amzn.to/4jg4GgR
    color: '#f5e083'
  - nombre: Negro
    link: https://amzn.to/4329gdQ
    color: '#1c1c1c'
  - nombre: Castaño Medio
    link: https://amzn.to/3ZfbPqL
    color: '#a8753f'
  - nombre: Rubio Ceniza
    link: https://amzn.to/4kw9kbH
    color: '#f5e083'
  - nombre: Castaño Caoba
    link: https://amzn.to/4k6SKiI
    color: '#8b5d33'
  - nombre: Castaño Cobrizo
    link: https://amzn.to/4drXzRl
    color: '#8b5d33'
  - nombre: Caoba Oscuro
    link: https://amzn.to/3FgfNbI
    color: '#a52a2a'
  - nombre: Chocolate
    link: https://amzn.to/43mdMml
    color: '#cccccc'
  - nombre: Rojo Burdeos
    link: https://amzn.to/43oNpMI
    color: '#c0392b'
  - nombre: Super Caoba Luminoso
    link: https://amzn.to/4msYzbW
    color: '#a52a2a'
  - nombre: Castaño Intenso
    link: https://amzn.to/3Znub8M
    color: '#8b5d33'
  - nombre: Rubio Dorado
    link: https://amzn.to/4mlKv3F
    color: '#f5e083'
  - nombre: Indigo
    link: https://amzn.to/432t8xo
    color: '#3f51b5'
  - nombre: Caoba Intenso
    link: https://amzn.to/3SGpjI2
    color: '#a52a2a'
  - nombre: Caoba Natural
    link: https://amzn.to/3H05Hw6
    color: '#a52a2a'
  - nombre: Sidr Tratamiento Capilar Natural
    link: https://amzn.to/4ktVVRq
    color: '#e6e6e6'
  - nombre: Manjistha Tratamiento Capilar Natural
    link: https://amzn.to/4ko59OO
    color: '#e6e6e6'
  - nombre: Brahmi Tratamiento Capilar Natural
    link: https://amzn.to/3EZJwpn
    color: '#e6e6e6'
  - nombre: Tratamiento Capilar Ayurvédico Amla
    link: https://amzn.to/4dswcXd
    color: '#aed581'
  - nombre: Fortalecedor de Cabello
    link: https://amzn.to/3GZRTSl
    color: '#b2dfdb'
- emoji: 🍃
  titulo: 'Real Earth: Barros Orgánicos para un Cabello Saludable'
  recomendado: false
  bloques:
  - subtitulo: ✔️ ¿Qué ofrece esta marca?
    texto: Es una opción económica pero eficaz. Perfecta para quienes quieren iniciarse
      en el mundo de los pigmentos naturales sin gastar mucho, pero sin renunciar
      a resultados visibles.
  - subtitulo: 🌿 Ingredientes y textura
    texto: Contiene henna, índigo y amla. Tiene una textura muy fina, fácil de aplicar
      y de aclarar, lo cual agradecen mucho las clientas con cabello seco.
  - subtitulo: 💬 Opinión tras probarla
    texto: El tono Caoba es muy versátil para bases castañas que quieren un toque
      rojizo elegante. Además, el índigo de esta marca funciona muy bien para cubrir
      canas en dos pasos.
  - subtitulo: 💡 Ideal para...
    texto: Personas con cuero cabelludo sensible que quieren una solución sencilla,
      sin perfumes ni químicos, pero con buenos resultados.
  colores:
  - nombre: Caoba
    link: https://amzn.to/44FnFxL
    color: '#a52a2a'
  - nombre: Castaño Oscuro
    link: https://amzn.to/3SIg8H7
    color: '#8b5d33'
  - nombre: Índigo
    link: https://amzn.to/4drWMjl
    color: '#cccccc'
- emoji: 🌸
  titulo: 'Henna y 3x Indigo: Tradición Natural para el Cuidado Capilar'
  recomendado: false
  bloques:
  - subtitulo: ✔️ ¿Qué es?
    texto: Este producto combina dos hierbas, la henna y el índigo, para proporcionar
      un hermoso tono de cabello.
  - subtitulo: 🌿 Cómo la utilizo en mi centro
    texto: Muchas veces combinada con aceites esenciales para mejorar su fijación
      y aroma. La aplico especialmente en cabellos débiles o con caída.
  - subtitulo: ⏱️ Recomendaciones de uso
    texto: Es importante dejarla actuar al menos una hora para que el pigmento se
      fije bien. Cuanto más tiempo se deje, mayor será la intensidad del color.
  colores:
  - nombre: Castaño Oscuro
    link: https://amzn.to/3HgKD4r
    color: '#8b5d33'
  - nombre: Castaño Claro
    link: https://amzn.to/4kl9SS9
    color: '#e6d3a3'
  - nombre: Castaño
    link: https://amzn.to/4ko4e0O
    color: '#8b5d33'
  - nombre: Rojo cobre
    link: https://amzn.to/4moBWFg
    color: '#b87333'
  - nombre: Rubio Natural
    link: https://amzn.to/4je8q2z
    color: '#f5e083'
  - nombre: Neutro
    link: https://amzn.to/4moe4BQ
    color: '#cccccc'
