productos:
  - ASIN: B097BPPYVR
    a_tener_en_cuenta: Reversible, 2 lados de diferente firmeza, funda lavable hasta 60º, 40 x 40 x 6cm
    brand: TECNOCOLCHÓN
    caracteristicas:
      - Muy cómodo al sentarse
      - Buena transpiración
      - Ligero y fácil de mover
      - Ideal para uso doméstico o en oficina
      - No hace ruido ni se deforma
    descripcion: >-
      Este cojín me ha parecido ideal para quienes buscan comodidad y suavidad desde el primer momento. El material
      viscoelástico se adapta bien sin hundirse, y la funda transpirable es un plus si vas a estar muchas horas sentado.
      Lo he usado en silla de escritorio y sillón, y en ambas se nota el alivio en la base. No lo recomendaría para
      personas con mucho peso, ya que puede parecer demasiado blando, pero para uso diario es muy agradable.
    enlace: https://amzn.to/3H34MuM
    imagen: https://m.media-amazon.com/images/I/41yElvEBVvS._SL500_.jpg
    lo_mejor: Viscoelástica
    nombre: TECNOCOLCHÓN Visco Air
    valoracion: 5
    precio: Sin precio
    precioOriginal: No especificado
    disponibilidad: Sin info
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/61ZD9X7HMQS._SL500_.jpg
        width: 500
        height: 464
      - url: https://m.media-amazon.com/images/I/61Pe34DVKuS._SL500_.jpg
        width: 500
        height: 487
      - url: https://m.media-amazon.com/images/I/51l3J3+hiKS._SL500_.jpg
        width: 490
        height: 500
      - url: https://m.media-amazon.com/images/I/51R2ESfXANS._SL500_.jpg
        width: 487
        height: 500
      - url: https://m.media-amazon.com/images/I/31AnN0xdo1L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/318F0J6CGoL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 280
    imagenWidth: 500
  - ASIN: B0DBWKDXKM
    a_tener_en_cuenta: Cuadrado con funda impermeable, Incluye 2 fundas extras, asa de transporte, 40 x 40 x 8cm
    brand: SILKORA
    caracteristicas:
      - Antideslizante
      - Compacto y fácil de transportar
      - Funda lavable
      - Material de buena densidad
      - No se deforma con facilidad
    descripcion: >-
      Este modelo es compacto, antideslizante y cómodo para sesiones no muy largas. Me ha parecido muy práctico para
      llevar de una silla a otra, aunque algo estrecho si tienes una complexión grande. El acabado de la funda es muy
      bueno, y no se mueve fácilmente al sentarse. Para uso diario moderado o como cojín de prevención, va muy bien.
    enlace: https://amzn.to/4khgj8o
    imagen: https://m.media-amazon.com/images/I/31di9IIVx0L._SL500_.jpg
    lo_mejor: Viscoelástica + capa de gel
    nombre: SILKORA® Premium
    valoracion: 5
    precio: "35,99\_€"
    precioOriginal: "39,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51pWbJhnLwL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41m+6DZcldL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518ruFuAUqL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/412MZMrwxUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/510Ur4dHwWL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51c6efLRr4L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B085TSG7G9
    a_tener_en_cuenta: Rectangular, Funda lavable, transpirable, impermeable y antideslizante, 42 x 42 x 8cm
    brand: PEPE Mobility
    caracteristicas:
      - Muy buena relación calidad-precio
      - Altura correcta (8 cm)
      - Funda resistente
      - Viscoelástica adaptable
      - Ideal para uso doméstico
    descripcion: >-
      Este cojín es uno de los más equilibrados de la gama media. Buena altura, densidad correcta y sensación cómoda al
      apoyar. Lo he probado durante días en silla rígida y de oficina, y no se ha hundido ni ha generado calor. La funda
      no es impermeable, pero sí transpirable y resistente. Para personas que buscan un buen cojín sin gastar demasiado,
      lo veo ideal.
    enlace: https://amzn.to/4mt1Rfe
    imagen: https://m.media-amazon.com/images/I/21dP6Er5jrL._SL500_.jpg
    lo_mejor: Viscoelástica + espuma de poliuretano
    nombre: PEPE Mobility
    valoracion: 4.5
    precio: "24,99\_€"
    precioOriginal: "27,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31g9oYDCJkL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41puyLluX6L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41PvpZbDzTL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31JsSOQqT+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31K9859ShRL._SL500_.jpg
        width: 500
        height: 343
    imagenHeight: 361
    imagenWidth: 500
  - ASIN: B0C375Q756
    a_tener_en_cuenta: Rectangular, Mejora la postura, funda lavable y transpirable, 42 x 42 x 8cm
    brand: VALENTIA MEDICAL
    caracteristicas:
      - Buena combinación visco + HR
      - Ideal para largas jornadas sentado
      - No se hunde ni calienta
      - Funda lavable y resistente
      - Se adapta al cuerpo sin deformarse
    descripcion: >-
      Este cojín combina firmeza y adaptación. La capa superior de viscoelástica se nota mullida, pero por debajo la
      espuma Viscoelástica aporta soporte. Lo he usado en silla de ruedas y en una butaca durante 3 días completos, y no
      se ha deformado ni recalentado. Me parece una opción excelente para quienes buscan confort sin renunciar a soporte
      firme.
    enlace: https://amzn.to/4mGbSpA
    imagen: https://m.media-amazon.com/images/I/41aCb5RXR2L._SL500_.jpg
    lo_mejor: Viscoelástica + espuma HR
    nombre: VALENTIA MEDICAL Visco + HR
    valoracion: 4.5
    precio: "25,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41olPMWEILL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41VFC9DvvLL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51PoLSQcR6L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51wiqSFWNPL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51J0o-ElWuL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B097DJTK7Z
    a_tener_en_cuenta: Cuadrado con agujero central, Prevención de úlceras por presión, ideal para coxis, 40 x 38cm
    brand: Mobiclinic
    caracteristicas:
      - Hueco central que reduce presión
      - Ligero y cómodo
      - Funda transpirable y desmontable
      - Se adapta a sillas estándar y ruedas
      - Buena opción para uso preventivo
    descripcion: >-
      Este modelo está claramente pensado para aliviar presión en el coxis o el área sacra. La forma con hueco central
      se nota al sentarse y ayuda a quienes tienen molestias al apoyar. Lo he probado en una silla estándar y en una
      silla de oficina, y funciona mejor en superficies estables.
    enlace: https://amzn.to/3HkJKI7
    imagen: https://m.media-amazon.com/images/I/21lHIc9XfwL._SL500_.jpg
    lo_mejor: Espuma anatómica
    nombre: Mobiclinic con hueco central
    valoracion: 4.5
    precio: "26,95\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31CcRYdzq1S._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51NYmytkRVL._SL500_.jpg
        width: 500
        height: 472
      - url: https://m.media-amazon.com/images/I/51JBmkw0MzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/417wkWKxPvL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/216x9JIh7EL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B08541P7GX
    a_tener_en_cuenta: Redondo con agujero central, Alivia presión en coxis, funda lavable, 39 x 39cm
    brand: OrtoPrime
    caracteristicas:
      - Diseño ergonómico con hueco posterior
      - Muy cómodo en sesiones medias
      - Funda lavable incluida
      - No se desliza
      - Ligero
    descripcion: >-
      Este cojín tiene una forma en U clásica, con la parte trasera recortada para liberar presión en el coxis. Es una
      solución sencilla pero efectiva. Ideal para llevar a la oficina o usar en casa en silla rígida. No es el más
      acolchado, pero su forma alivia bastante.
    enlace: https://amzn.to/4jk6x4h
    imagen: https://m.media-amazon.com/images/I/41x4wIHdyKL._SL500_.jpg
    lo_mejor: Espuma anatómica
    nombre: OrtoPrime para Coxis
    valoracion: 4.5
    precio: "24,90\_€"
    precioOriginal: "31,90\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41i79fHmSLL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/416BDP0XY2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41dTkA0BkdL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41AloVZKrjL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41MFyHcX0jL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51iT3NcAs+L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Fx3XClUUL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51YB75w-2CL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 408
    imagenWidth: 500
  - ASIN: B09DBRRSKN
    a_tener_en_cuenta: Forma de herradura, Diseño ergonómico, distribuye el peso de forma homogénea, 40 x 40 x 8cm
    brand: OrtoPrime
    caracteristicas:
      - Diseño anatómico
      - Ventilación trasera
      - Funda suave y lavable
      - Ideal para sillas rígidas
      - Ligero
    descripcion: >-
      Este cojín tiene un diseño envolvente que ayuda a repartir el peso y mantener el cuerpo centrado. Me ha parecido
      cómodo para personas que necesitan un poco más de guía postural, pero sin ser rígido. Similar a un cojín de viaje
      anatómico, pero para sillas.
    enlace: https://amzn.to/4kaQiaY
    imagen: https://m.media-amazon.com/images/I/31MFFWzJq4L._SL500_.jpg
    lo_mejor: Espuma anatómica
    nombre: OrtoPrime Herradura
    valoracion: 4.5
    precio: "26,90\_€"
    precioOriginal: "31,90\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51BiHQ33f2L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/511EW+A5diL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51EDCNiDDyL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41ZqUpsjCSL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Rk7h-iZzL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Uq1A3bNpL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/31aNxhyF4SL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 405
    imagenWidth: 500
  - ASIN: B07Y5LMGB3
    a_tener_en_cuenta: Rectangular con ranuras, Alivia presión en coxis, funda lavable y transpirable, 40 x 39 x 8cm
    brand: OrtoPrime
    caracteristicas:
      - Canales que distribuyen presión
      - Buena ventilación
      - Firme pero cómodo
      - Buena altura (8 cm)
      - Ideal para uso prolongado
    descripcion: >-
      Tiene canales longitudinales en la espuma que ayudan a distribuir la presión y mejorar la ventilación. Me ha
      parecido firme pero confortable. Es ideal para quienes pasan muchas horas sentados sin querer algo muy blando.
    enlace: https://amzn.to/4k6Ikjh
    imagen: https://m.media-amazon.com/images/I/31DHZpi0ObL._SL500_.jpg
    lo_mejor: Espuma anatómica
    nombre: OrtoPrime Ranurado
    valoracion: 4.5
    precio: "26,90\_€"
    precioOriginal: "31,90\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51jx55V7WhL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51XCva13HyL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/416uCLnmWWL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41fzi9dT4tL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41TyiTVk3JL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41fXa8tMKZL._SL500_.jpg
        width: 500
        height: 453
      - url: https://m.media-amazon.com/images/I/51LYH4HPYnL._SL500_.jpg
        width: 500
        height: 483
    imagenHeight: 384
    imagenWidth: 500
  - ASIN: B09QSSZRTR
    a_tener_en_cuenta: Rectangular, Mejora la postura, funda lavable y transpirable, 41 x 41 x 7cm
    brand: KMINA
    caracteristicas:
      - Gran firmeza
      - Buena estabilidad
      - Funda antideslizante y lavable
      - Ideal para silla de ruedas
      - No genera calor
    descripcion: >-
      Tiene una combinación de espuma técnica con viscoelástica, y se nota más firme que otros modelos. Me ha parecido
      especialmente útil para personas que pasan muchas horas al día en silla de ruedas. Es estable y fiable, aunque
      puede parecer duro al principio.
    enlace: https://amzn.to/3Sd9MQ3
    imagen: https://m.media-amazon.com/images/I/31MeBKbsMPL._SL500_.jpg
    lo_mejor: Viscoelástica
    nombre: KMINA Cojín Antiescaras
    valoracion: 4.5
    precio: "49,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/31AZmGOU7PL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/414sYN1uMQL._SL500_.jpg
        width: 500
        height: 333
      - url: https://m.media-amazon.com/images/I/21xUTJ8usgL._SL500_.jpg
        width: 500
        height: 336
      - url: https://m.media-amazon.com/images/I/21Ejs8h2gIL._SL500_.jpg
        width: 500
        height: 346
      - url: https://m.media-amazon.com/images/I/41N9YjkiOtL._SL500_.jpg
        width: 500
        height: 374
    imagenHeight: 397
    imagenWidth: 500
  - ASIN: B0B12QS64Z
    a_tener_en_cuenta: Rectangular, Mejora la postura, funda lavable y transpirable, 42 x 42 x 8cm
    brand: VALENTIA MEDICAL
    caracteristicas:
      - Muy firme
      - Ideal para uso prolongado
      - Funda resistente
      - Soporta hasta 100 kg
      - Buena opción institucional o doméstica
    descripcion: >-
      Modelo simple pero efectivo. Su espuma Viscoelástica es firme, resistente y no se hunde. Me parece una gran opción
      si priorizas la durabilidad. Para quienes buscan soporte sólido sin florituras, este es un cojín fiable y muy
      estable incluso tras largas horas de uso.
    enlace: https://amzn.to/3Fcmpb7
    imagen: https://m.media-amazon.com/images/I/41TJUa9s3NL._SL500_.jpg
    lo_mejor: Viscoelástica
    nombre: VALENTIA MEDICAL Viscoelástica firme
    valoracion: 5
    precio: "31,99\_€"
    precioOriginal: No especificado
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/51jJxBUVbyL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41OURogkHML._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41Ifn5sCq6L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51wiqSFWNPL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51J0o-ElWuL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0F53TT2DS
    a_tener_en_cuenta: Rectangular, Mejora la postura, funda lavable y transpirable, 42 x 42 x 8cm
    brand: VALENTIA MEDICAL
    caracteristicas:
      - Firme
      - Ideal para uso moderado
      - Funda resistente
      - Buena opción institucional o doméstica
    descripcion: >-
      Mismo modelo que el anterior pero con una espuma menos firme. Su espuma Viscoelástica es resistente y no se hunde
      pero no aguanta tanto peso como el anterior.
    enlace: https://amzn.to/3YW3eZL
    imagen: https://m.media-amazon.com/images/I/315IqCo7+lL._SL500_.jpg
    lo_mejor: Viscoelástica
    nombre: VALENTIA MEDICAL Viscoelástica
    valoracion: 4.5
    precio: "26,99\_€"
    precioOriginal: "29,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/41EtSmDuikL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/4108CP58TVL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51PAXIx3E-L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51HR8CtOAFL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51iTlt+YuvL._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
  - ASIN: B0BLF43FY4
    a_tener_en_cuenta: Cuadrado, Previene activamente escaras, úlceras e irritaciones, 43 x 43cm
    brand: dumald
    caracteristicas:
      - Espuma densa y resistente
      - Buen grosor (8 cm)
      - Soporte firme sin hundirse
      - Se adapta bien tras unos minutos
      - Ideal para sillas de ruedas
    descripcion: >-
      Este cojín está bien construido, con buena densidad y grosor. Me ha sorprendido por su rigidez inicial, pero tras
      unos minutos se adapta al cuerpo. Lo destacaría para personas que quieren una base firme pero que no sea dura. Su
      punto débil es que no tiene cremallera en la funda.
    enlace: https://amzn.to/3H7s0Ac
    imagen: https://m.media-amazon.com/images/I/51htk50xR8L._SL500_.jpg
    lo_mejor: Cojín de aire
    nombre: dumald Cojín Antiescaras
    valoracion: 4.5
    precio: "49,99\_€"
    precioOriginal: "54,99\_€"
    disponibilidad: En stock
    imagenesVariantes:
      - url: https://m.media-amazon.com/images/I/517RDdeOQKL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/518WqTN7L3L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/41kUZs2k2kL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51Y3N9s7f8L._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51bmnNdd-iL._SL500_.jpg
        width: 500
        height: 500
      - url: https://m.media-amazon.com/images/I/51RzOXAT72L._SL500_.jpg
        width: 500
        height: 500
    imagenHeight: 500
    imagenWidth: 500
titulo_a_tener_en_cuenta: Características
titulo_lo_mejor: Material
