productos:
- nombre: TECNOCOLCHÓN Visco Air
  brand: TECNOCOLCHÓN
  imagen: images/cojin-antiescaras-tecnocolchon.webp
  valoracion: 5.0
  descripcion: Este cojín me ha parecido ideal para quienes buscan comodidad y suavidad
    desde el primer momento. El material viscoelástico se adapta bien sin hundirse,
    y la funda transpirable es un plus si vas a estar muchas horas sentado. Lo he
    usado en silla de escritorio y sillón, y en ambas se nota el alivio en la base.
    No lo recomendaría para personas con mucho peso, ya que puede parecer demasiado
    blando, pero para uso diario es muy agradable.
  caracteristicas:
  - Muy cómodo al sentarse
  - Buena transpiración
  - Ligero y fácil de mover
  - Ideal para uso doméstico o en oficina
  - No hace ruido ni se deforma
  enlace: https://amzn.to/3H34MuM
  lo_mejor: Viscoelástica
  a_tener_en_cuenta: Reversible, 2 lados de diferente firmeza
- nombre: SILKORA® Premium
  brand: SILKORA®
  imagen: images/cojin-antiescaras-silkora-premium.webp
  valoracion: 5.0
  descripcion: Este modelo es compacto, antideslizante y cómodo para sesiones no muy
    largas. Me ha parecido muy práctico para llevar de una silla a otra, aunque algo
    estrecho si tienes una complexión grande. El acabado de la funda es muy bueno,
    y no se mueve fácilmente al sentarse. Para uso diario moderado o como cojín de
    prevención, va muy bien.
  caracteristicas:
  - Antideslizante
  - Compacto y fácil de transportar
  - Funda lavable
  - Material de buena densidad
  - No se deforma con facilidad
  enlace: https://amzn.to/4khgj8o
  lo_mejor: Viscoelástica + capa de gel
  a_tener_en_cuenta: Cuadrado con funda impermeable
- nombre: PEPE Mobility
  brand: PEPE
  imagen: images/cojin-antiescaras-pepe-mobility.webp
  valoracion: 4.5
  descripcion: Este cojín es uno de los más equilibrados de la gama media. Buena altura,
    densidad correcta y sensación cómoda al apoyar. Lo he probado durante días en
    silla rígida y de oficina, y no se ha hundido ni ha generado calor. La funda no
    es impermeable, pero sí transpirable y resistente. Para personas que buscan un
    buen cojín sin gastar demasiado, lo veo ideal.
  caracteristicas:
  - Muy buena relación calidad-precio
  - Altura correcta (8 cm)
  - Funda resistente
  - Viscoelástica adaptable
  - Ideal para uso doméstico
  enlace: https://amzn.to/4mt1Rfe
  lo_mejor: Viscoelástica + espuma de poliuretano
  a_tener_en_cuenta: Rectangular
- nombre: VALENTIA MEDICAL Visco + HR
  brand: VALENTIA
  imagen: images/cojin-antiescaras-valentia-medical.webp
  valoracion: 4.5
  descripcion: Este cojín combina firmeza y adaptación. La capa superior de viscoelástica
    se nota mullida, pero por debajo la espuma Viscoelástica aporta soporte. Lo he
    usado en silla de ruedas y en una butaca durante 3 días completos, y no se ha
    deformado ni recalentado. Me parece una opción excelente para quienes buscan confort
    sin renunciar a soporte firme.
  caracteristicas:
  - Buena combinación visco + HR
  - Ideal para largas jornadas sentado
  - No se hunde ni calienta
  - Funda lavable y resistente
  - Se adapta al cuerpo sin deformarse
  enlace: https://amzn.to/4mGbSpA
  lo_mejor: Viscoelástica + espuma HR
  a_tener_en_cuenta: Rectangular
- nombre: Mobiclinic® con hueco central
  brand: Mobiclinic®
  imagen: placeholder.webp
  valoracion: 4.5
  descripcion: Este modelo está claramente pensado para aliviar presión en el coxis
    o el área sacra. La forma con hueco central se nota al sentarse y ayuda a quienes
    tienen molestias al apoyar. Lo he probado en una silla estándar y en una silla
    de oficina, y funciona mejor en superficies estables.
  caracteristicas:
  - Hueco central que reduce presión
  - Ligero y cómodo
  - Funda transpirable y desmontable
  - Se adapta a sillas estándar y ruedas
  - Buena opción para uso preventivo
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
- nombre: OrtoPrime para Coxis
  brand: OrtoPrime
  imagen: placeholder.webp
  valoracion: 4.5
  descripcion: Este cojín tiene una forma en U clásica, con la parte trasera recortada
    para liberar presión en el coxis. Es una solución sencilla pero efectiva. Ideal
    para llevar a la oficina o usar en casa en silla rígida. No es el más acolchado,
    pero su forma alivia bastante.
  caracteristicas:
  - Diseño ergonómico con hueco posterior
  - Muy cómodo en sesiones medias
  - Funda lavable incluida
  - No se desliza
  - Ligero
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
- nombre: OrtoPrime Herradura
  brand: OrtoPrime
  imagen: images/cojin-antiescaras-ortoprime-herradura.webp
  valoracion: 4.5
  descripcion: Este cojín tiene un diseño envolvente que ayuda a repartir el peso
    y mantener el cuerpo centrado. Me ha parecido cómodo para personas que necesitan
    un poco más de guía postural, pero sin ser rígido. Similar a un cojín de viaje
    anatómico, pero para sillas.
  caracteristicas:
  - Diseño anatómico
  - Ventilación trasera
  - Funda suave y lavable
  - Ideal para sillas rígidas
  - Ligero
  enlace: https://amzn.to/4kaQiaY
  lo_mejor: Espuma anatómica
  a_tener_en_cuenta: Forma de herradura
- nombre: OrtoPrime Ranurado
  brand: OrtoPrime
  imagen: images/cojin-antiescaras-ortoprime.webp
  valoracion: 4.5
  descripcion: Tiene canales longitudinales en la espuma que ayudan a distribuir la
    presión y mejorar la ventilación. Me ha parecido firme pero confortable. Es ideal
    para quienes pasan muchas horas sentados sin querer algo muy blando.
  caracteristicas:
  - Canales que distribuyen presión
  - Buena ventilación
  - Firme pero cómodo
  - Buena altura (8 cm)
  - Ideal para uso prolongado
  enlace: https://amzn.to/4k6Ikjh
  lo_mejor: Espuma anatómica
  a_tener_en_cuenta: Rectangular con ranuras
- nombre: KMINA Cojín Antiescaras
  brand: KMINA
  imagen: placeholder.webp
  valoracion: 4.5
  descripcion: Tiene una combinación de espuma técnica con viscoelástica, y se nota
    más firme que otros modelos. Me ha parecido especialmente útil para personas que
    pasan muchas horas al día en silla de ruedas. Es estable y fiable, aunque puede
    parecer duro al principio.
  caracteristicas:
  - Gran firmeza
  - Buena estabilidad
  - Funda antideslizante y lavable
  - Ideal para silla de ruedas
  - No genera calor
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
- nombre: VALENTIA MEDICAL Viscoelástica firme
  brand: VALENTIA
  imagen: placeholder.webp
  valoracion: 5.0
  descripcion: Modelo simple pero efectivo. Su espuma Viscoelástica es firme, resistente
    y no se hunde. Me parece una gran opción si priorizas la durabilidad. Para quienes
    buscan soporte sólido sin florituras, este es un cojín fiable y muy estable incluso
    tras largas horas de uso.
  caracteristicas:
  - Muy firme
  - Ideal para uso prolongado
  - Funda resistente
  - Soporta hasta 100 kg
  - Buena opción institucional o doméstica
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
- nombre: VALENTIA MEDICAL Viscoelástica
  brand: VALENTIA
  imagen: placeholder.webp
  valoracion: 4.5
  descripcion: Mismo modelo que el anterior pero con una espuma menos firme. Su espuma
    Viscoelástica es resistente y no se hunde pero no aguanta tanto peso como el anterior.
  caracteristicas:
  - Firme
  - Ideal para uso moderado
  - Funda resistente
  - Buena opción institucional o doméstica
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
- nombre: dumald Cojín Antiescaras
  brand: dumald
  imagen: placeholder.webp
  valoracion: 4.5
  descripcion: Este cojín está bien construido, con buena densidad y grosor. Me ha
    sorprendido por su rigidez inicial, pero tras unos minutos se adapta al cuerpo.
    Lo destacaría para personas que quieren una base firme pero que no sea dura. Su
    punto débil es que no tiene cremallera en la funda.
  caracteristicas:
  - Espuma densa y resistente
  - Buen grosor (8 cm)
  - Soporte firme sin hundirse
  - Se adapta bien tras unos minutos
  - Ideal para sillas de ruedas
  enlace: ''
  lo_mejor: ''
  a_tener_en_cuenta: ''
